"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";
import { makeDisplayOptions, type DisplayOption } from "@/lib/options";
import AddWordSheet from "@/components/add-word-sheet";

type DailyItem={sequence:number;priority:number;reason:string;quiz_date:string;status:string;question_id:string;topic:string;word:string;question:string;question_type:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_key:string;explanation:string;tip:string;usage_note:string;example_sentence:string;memory_aid:string;related_words:string;source_file:string;source_page:string;starred:boolean;difficult:boolean};
type DailyResult={ok:boolean;total:number;completed:number;remaining:number;batch_date:string;target_is_maximum:boolean;items:DailyItem[]};
type AnswerState={selectedDisplayKey:string;correct:boolean;correctCanonicalKey:string};
const positionKey=(date:string)=>`revision-v2:english:daily:${date}:current-question`;
export default function DailyPage(){
 const ready=useAuthGuard(),router=useRouter();const [batch,setBatch]=useState<DailyResult|null>(null);const [idx,setIdx]=useState(0);const [answers,setAnswers]=useState<Record<string,AnswerState>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState("");const started=useRef(Date.now());const optionCache=useRef(new Map<string,DisplayOption[]>());
 useEffect(()=>{if(!ready)return;optionCache.current.clear();setAnswers({});rpc<DailyResult>("english_resume_daily").then(x=>{let next=0;try{const saved=localStorage.getItem(positionKey(x.batch_date));const found=x.items.findIndex(i=>i.question_id===saved);if(found>=0)next=found;}catch{}setBatch(x);setIdx(next);if(x.items[next])try{localStorage.setItem(positionKey(x.batch_date),x.items[next].question_id);}catch{}started.current=Date.now();}).catch((e:any)=>setError(e.message));},[ready]);
 const item=batch?.items?.[idx];const answerState=item?answers[item.question_id]:undefined;const options=useMemo(()=>{if(!item)return[];const hit=optionCache.current.get(item.question_id);if(hit)return hit;const made=makeDisplayOptions(item.question_type,[{key:"A",text:item.option_a},{key:"B",text:item.option_b},{key:"C",text:item.option_c},{key:"D",text:item.option_d}]);optionCache.current.set(item.question_id,made);return made;},[item?.question_id,item?.question_type,item?.option_a,item?.option_b,item?.option_c,item?.option_d]);const correctDisplayKey=answerState?options.find(o=>o.canonicalKey===answerState.correctCanonicalKey)?.key||answerState.correctCanonicalKey:"";
 function move(next:number){const target=batch?.items?.[next];if(!target)return;setIdx(next);setError("");try{localStorage.setItem(positionKey(batch!.batch_date),target.question_id);}catch{}started.current=Date.now();window.scrollTo({top:0,behavior:"smooth"});}
 async function answer(option:DisplayOption){if(!item||busy||answerState)return;setBusy(true);setError("");try{const out=await rpc<any>("english_submit_answer",{p_question_id:item.question_id,p_selected_key:option.canonicalKey,p_time_seconds:Math.max(0,Math.min(180,(Date.now()-started.current)/1000)),p_marked_revision:item.starred,p_attempt_id:`v2-${item.question_id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,p_module:"daily"});setAnswers(a=>({...a,[item.question_id]:{selectedDisplayKey:option.key,correct:!!out.is_correct,correctCanonicalKey:String(out.correct_key||item.correct_key).toUpperCase()}}));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function mark(){if(!item)return;const next=!item.starred;setBatch(b=>b?{...b,items:b.items.map((x,i)=>i===idx?{...x,starred:next}:x)}:b);try{await rpc("english_set_starred",{p_question_id:item.question_id,p_starred:next});}catch(e:any){setBatch(b=>b?{...b,items:b.items.map((x,i)=>i===idx?{...x,starred:!next}:x)}:b);setError(e.message);}}
 async function mastered(){if(!item||!window.confirm("Mark Mastered only after spaced retention is proven?"))return;try{await rpc("english_set_mastered",{p_question_id:item.question_id,p_mastered:true,p_require_proven:true});if(idx<batch!.items.length-1)move(idx+1);else router.push("/english");}catch(e:any){setError(e.message||"Retention not proven yet");}}
 if(!ready||!batch)return <main className="center"><div className="muted">{error||"Loading Daily…"}</div></main>;
 if(!batch.items.length)return <main className="shell quiz"><div className="quiz-top"><Link className="btn ghost" href="/english">← Back</Link><div className="quiz-title"><div className="brand">Daily Practice</div></div><div/></div><div className="empty-state"><h2>Daily complete</h2><p className="muted">No currently actionable pending questions remain.</p></div></main>;
 if(!item)return <main className="shell"><div className="error-box">Daily position unavailable.</div></main>;
 return <main className="shell quiz quiz-with-tools"><div className="quiz-top"><Link className="btn ghost" href="/english">← Back</Link><div className="quiz-title"><div className="brand">Daily Practice</div><div className="quiz-count">{idx+1} / {batch.items.length}</div></div><div/></div><div className="progress"><span style={{width:`${((idx+1)/batch.items.length)*100}%`}}/></div><section className="quiz-card"><div className="quiz-meta"><span className="pill">{item.reason}</span><span className="pill">{item.topic}</span><span className="pill">{item.question_id}</span></div><div className="question-area">{item.word&&<div className="question-word">{item.word}</div>}<div className="question">{item.question}</div></div><div className="options">{options.map(o=>{let cls="option";if(answerState?.selectedDisplayKey===o.key)cls+=" selected";if(answerState&&o.canonicalKey===answerState.correctCanonicalKey)cls+=" correct";if(answerState&&answerState.selectedDisplayKey===o.key&&o.canonicalKey!==answerState.correctCanonicalKey)cls+=" wrong";return <button key={o.key} className={cls} onClick={()=>answer(o)} disabled={!!answerState||busy}><span className="option-key">{o.key}</span><span>{o.text}</span></button>;})}</div>{error&&<div className="result-wrap"><div className="error-box">{error}</div></div>}{answerState&&<div className="result-wrap"><div className={`result-head ${answerState.correct?"good-result":"bad-result"}`} style={{color:answerState.correct?"var(--ok)":"var(--bad)"}}><span className="result-dot"/><strong>{answerState.correct?"Correct":"Incorrect"}</strong><span className="spacer"/><span className="pill">Answer {correctDisplayKey}</span></div><div className="explanation">{item.explanation||"No explanation available."}{item.example_sentence?`\n\nExample: ${item.example_sentence}`:""}{item.usage_note?`\n\nUsage: ${item.usage_note}`:""}{item.tip?`\n\nTip: ${item.tip}`:""}{item.memory_aid?`\n\nRemember: ${item.memory_aid}`:""}</div></div>}</section><div className="quiz-tools"><button className={`btn ghost ${item.starred?"warn":""}`} onClick={mark}>{item.starred?"★ Marked":"☆ Mark"}</button><AddWordSheet questionId={item.question_id} initialWord={item.word||""} source="Daily Practice" label="📝 Add Word"/><button className="btn ghost" onClick={mastered}>✓ Mastered</button><button className="btn ghost" onClick={()=>router.push("/english")}>Ⅱ Pause</button></div><div className="quiz-nav"><button className="btn ghost" disabled={idx===0} onClick={()=>move(idx-1)}>← Previous</button><button className="btn primary" onClick={()=>idx<batch.items.length-1?move(idx+1):router.push("/english")}>{idx===batch.items.length-1?"Finish":"Next →"}</button></div></main>;
}
