"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";
import { makeDisplayOptions, type DisplayOption } from "@/lib/options";

type DailyItem={sequence:number;priority:number;reason:string;quiz_date:string;status:string;question_id:string;topic:string;word:string;question:string;question_type:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_key:string;explanation:string;tip:string;usage_note:string;example_sentence:string;memory_aid:string;related_words:string;source_file:string;source_page:string;starred:boolean;difficult:boolean};
type DailyResult={ok:boolean;total:number;completed:number;remaining:number;batch_date:string;target_is_maximum:boolean;items:DailyItem[]};
const positionKey=(date:string)=>`revision-v2:english:daily:${date}:current-question`;

export default function DailyPage(){
 const ready=useAuthGuard();const [batch,setBatch]=useState<DailyResult|null>(null);const [idx,setIdx]=useState(0);const [selected,setSelected]=useState("");const [result,setResult]=useState<{correct:boolean;correctCanonicalKey:string}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const started=useRef(Date.now());const optionCache=useRef(new Map<string,DisplayOption[]>());
 useEffect(()=>{if(!ready)return;optionCache.current.clear();rpc<DailyResult>("english_resume_daily").then(x=>{let next=0;try{const saved=localStorage.getItem(positionKey(x.batch_date));const found=x.items.findIndex(i=>i.question_id===saved);if(found>=0)next=found}catch{}setBatch(x);setIdx(next);if(x.items[next]){try{localStorage.setItem(positionKey(x.batch_date),x.items[next].question_id)}catch{}}started.current=Date.now()}).catch(e=>setError(e.message));},[ready]);
 const item=batch?.items?.[idx];const options=useMemo(()=>{if(!item)return[];const hit=optionCache.current.get(item.question_id);if(hit)return hit;const made=makeDisplayOptions(item.question_type,[{key:'A',text:item.option_a},{key:'B',text:item.option_b},{key:'C',text:item.option_c},{key:'D',text:item.option_d}]);optionCache.current.set(item.question_id,made);return made},[item?.question_id,item?.question_type,item?.option_a,item?.option_b,item?.option_c,item?.option_d]);
 const correctDisplayKey=result?options.find(o=>o.canonicalKey===result.correctCanonicalKey)?.key||result.correctCanonicalKey:"";
 function resetQuestion(next:number){const target=batch?.items?.[next];if(!target)return;setIdx(next);setSelected("");setResult(null);setError("");try{localStorage.setItem(positionKey(batch!.batch_date),target.question_id)}catch{}started.current=Date.now();}
 async function answer(option:DisplayOption){if(!item||busy||result)return;setSelected(option.key);setBusy(true);setError("");try{const attemptId=`v2-${item.question_id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const out=await rpc<any>("english_submit_answer",{p_question_id:item.question_id,p_selected_key:option.canonicalKey,p_time_seconds:Math.max(0,Math.min(180,(Date.now()-started.current)/1000)),p_marked_revision:item.starred,p_attempt_id:attemptId,p_module:"daily"});setResult({correct:!!out.is_correct,correctCanonicalKey:String(out.correct_key||item.correct_key)});}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function toggleStar(){if(!item)return;const next=!item.starred;setBatch(b=>b?{...b,items:b.items.map((x,i)=>i===idx?{...x,starred:next}:x)}:b);try{await rpc("english_set_starred",{p_question_id:item.question_id,p_starred:next})}catch(e:any){setBatch(b=>b?{...b,items:b.items.map((x,i)=>i===idx?{...x,starred:!next}:x)}:b);setError(e.message)}}
 async function toggleDifficult(){if(!item)return;const next=!item.difficult;setBatch(b=>b?{...b,items:b.items.map((x,i)=>i===idx?{...x,difficult:next}:x)}:b);try{await rpc("english_set_difficult",{p_question_id:item.question_id,p_difficult:next})}catch(e:any){setBatch(b=>b?{...b,items:b.items.map((x,i)=>i===idx?{...x,difficult:!next}:x)}:b);setError(e.message)}}
 if(!ready||!batch)return <main className="center"><div className="muted">{error||"Loading Daily…"}</div></main>;
 if(!batch.items.length)return <main className="shell"><div className="topbar"><Link className="btn" href="/english">← English</Link></div><div className="card"><h2>Daily complete</h2><p className="muted">No currently actionable pending questions remain.</p></div></main>;
 if(!item)return <main className="shell"><div className="topbar"><Link className="btn" href="/english">← English</Link></div><div className="card"><h2>Daily position unavailable</h2><p className="muted">Reload Daily to restore the current position.</p></div></main>;
 return <main className="shell quiz"><div className="topbar"><Link className="btn ghost" href="/english">← English</Link><div className="row"><span className="pill">{batch.batch_date}</span><span className="pill">{idx+1}/{batch.items.length}</span></div></div><div className="progress"><span style={{width:`${((idx+1)/batch.items.length)*100}%`}}/></div><section key={item.question_id} className="card stack quiz-card" style={{marginTop:14}}><div className="row"><span className="pill">{item.reason}</span><span className="pill">{item.topic}</span><span className="spacer"/><button className={`btn ${item.starred?'warn':''}`} onClick={toggleStar}>{item.starred?'★ Starred':'☆ Star'}</button><button className={`btn ${item.difficult?'warn':''}`} onClick={toggleDifficult}>{item.difficult?'Difficult ✓':'Difficult'}</button></div>{item.word&&<div className="word">{item.word}</div>}<div className="question">{item.question}</div><div className="options">{options.map(o=>{let cls='option';if(selected===o.key)cls+=' selected';if(result&&o.canonicalKey===result.correctCanonicalKey)cls+=' correct';if(result&&selected===o.key&&o.canonicalKey!==result.correctCanonicalKey)cls+=' wrong';return <button key={o.key} className={cls} onClick={()=>answer(o)} disabled={!!result||busy}><b>{o.key}.</b> {o.text}</button>})}</div>{error&&<div className="error">{error}</div>}{result&&<div className="stack"><div className="row"><strong>{result.correct?'Correct':'Incorrect'}</strong><span className="pill">Answer: {correctDisplayKey}</span></div><div className="explanation">{item.explanation||"No explanation available."}{item.example_sentence?`\n\nExample: ${item.example_sentence}`:""}{item.tip?`\n\nTip: ${item.tip}`:""}</div></div>}<div className="row"><button className="btn" disabled={idx===0} onClick={()=>resetQuestion(idx-1)}>Previous</button><span className="spacer"/><button className="btn primary" disabled={idx>=batch.items.length-1} onClick={()=>resetQuestion(idx+1)}>Next</button></div></section></main>
}
