const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(process.cwd(),'apps-script');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const fail=m=>{console.error(`\n❌ ${m}`);process.exitCode=1};
const ok=m=>console.log(`✅ ${m}`);
const need=(t,n,l)=>t.includes(n)?ok(l):fail(`${l} — missing: ${n}`);
const required=['Code.gs','DailyV2.gs','Demand.gs','NewPractice.gs','SourcePractice.gs','TopicPractice.gs','HinduVocab.gs','DashboardStats.gs','ProgressStats.gs','Saved.gs','Index.html','Styles.html','AppJS.html','QuizJS.html','FastUI.html','TopicUI.html','NewPracticeUI.html','HinduUI.html','SourceUI.html','DemandUI.html','DashboardUI.html','SavedUI.html','appsscript.json'];
required.forEach(f=>fs.existsSync(path.join(root,f))?ok(`File present: ${f}`):fail(`Required Apps Script file missing: ${f}`));
if(process.exitCode)process.exit(process.exitCode);
const server=['Code.gs','DailyV2.gs','Demand.gs','NewPractice.gs','SourcePractice.gs','TopicPractice.gs','HinduVocab.gs','DashboardStats.gs','ProgressStats.gs','Saved.gs'];
const front=['AppJS.html','QuizJS.html','FastUI.html','TopicUI.html','NewPracticeUI.html','HinduUI.html','SourceUI.html','DemandUI.html','DashboardUI.html','SavedUI.html'];
server.forEach(f=>{try{new vm.Script(read(f),{filename:f});ok(`Server JavaScript syntax: ${f}`)}catch(e){fail(`Server JavaScript syntax failed in ${f}: ${e.message}`)}});
front.forEach(f=>{try{const js=read(f).replace(/^\s*<script[^>]*>/i,'').replace(/<\/script>\s*$/i,'');new vm.Script(js,{filename:f});ok(`Frontend JavaScript syntax: ${f}`)}catch(e){fail(`Frontend JavaScript syntax failed in ${f}: ${e.message}`)}});
let manifest={};try{manifest=JSON.parse(read('appsscript.json'));ok('appsscript.json is valid JSON')}catch(e){fail(e.message)}
if(manifest.runtimeVersion==='V8')ok('Apps Script V8 runtime preserved');else fail('V8 runtime required');
if(manifest.webapp?.access==='ANYONE')ok('Web app access preserved as ANYONE');else fail('webapp.access must be ANYONE');
if(manifest.webapp?.executeAs==='USER_DEPLOYING')ok('Web app executes as deploying user');else fail('webapp.executeAs must be USER_DEPLOYING');
const code=read('Code.gs'),daily=read('DailyV2.gs'),demand=read('Demand.gs'),np=read('NewPractice.gs'),source=read('SourcePractice.gs'),topic=read('TopicPractice.gs'),hindu=read('HinduVocab.gs'),dash=read('DashboardStats.gs'),progress=read('ProgressStats.gs'),saved=read('Saved.gs'),index=read('Index.html'),app=read('AppJS.html'),quiz=read('QuizJS.html'),fast=read('FastUI.html'),tui=read('TopicUI.html'),nui=read('NewPracticeUI.html'),dui=read('DemandUI.html'),sui=read('SourceUI.html'),hui=read('HinduUI.html'),dbui=read('DashboardUI.html'),savedui=read('SavedUI.html');
need(code,"spreadsheetId: '1IgUGQZu6sp1STBCX6gyI5pHayLGVpmYYrkKGYdwkjak'",'Live English spreadsheet preserved');
['function doGet(','function getPracticeBatch(','function submitAnswer(','function setMarked(','function markMastered('].forEach(x=>need(code,x,x));
['function getBootstrapV2(','function getDailyBatchV2(','syncDailyCompletionsFromPerformanceV2_','pendingFromPrevious',"const DAILY_V2_HISTORY='Daily_History'"].forEach(x=>need(daily,x,x));
['function getDemandBatches(','function getDemandPracticeBatch(','function submitHinduAnswer(','function getHinduPracticeProgress('].forEach(x=>need(demand,x,x));
['function getNewPracticeHub(','function getNewPracticeBatch(','function getNewPracticeItems(','MY_SAVED_WORDS'].forEach(x=>need(np,x,x));
['function getSourceHub(','function getSourcePracticeBatch(','function getSourceItems(','THE_HINDU'].forEach(x=>need(source,x,x));
['function getTopicPracticeHub(','function getTopicPracticeBatch(','function getTopicPracticeItems(','started','newCount'].forEach(x=>need(topic,x,x));
['function addHinduToVocab(','function getSavedHinduQuestionIds('].forEach(x=>need(hindu,x,x));
need(dash,'function getTodayActivityCount(','Today activity API');
['function getEncounterProgress(','todayNew','categories'].forEach(x=>need(progress,x,x));
['function captureMyWord(','autoMeaningForMyWord_','api.dictionaryapi.dev','function getStarredQuestionList(','function promoteMyWordToPractice(','My_Words'].forEach(x=>need(saved,x,x));
['id="homeView"','id="dailyStartBtn"','id="todayDoneBadge"',"include('FastUI')","include('TopicUI')","include('NewPracticeUI')","include('SavedUI')",'Loading daily plan…','onclick="EPApp.openSaved()"','onclick="EPSaved.openCapture()"'].forEach(x=>need(index,x,x));
['getBootstrapV2','getDailyBatchV2','Complete Previous Target','Fresh-first:'].forEach(x=>need(app,x,x));
["EPApp.call('submitAnswer'",'function next()','function pause()'].forEach(x=>need(quiz,x,x));
['prefetch','source:hub','topic:hub','saved:hub'].forEach(x=>need(fast,x,x));
['Topic Practice','Started','New','Random','View All'].forEach(x=>need(tui,x,x));
['All New Practice','View All','Practice All','Weak','Random'].forEach(x=>need(nui,x,x));
need(dui,'[10,20,50,100]','Demand random sizes 10/20/50/100');
['View All','Practice All','Weak','Random','THE_HINDU'].forEach(x=>need(sui,x,x));
['Practice Again · Round','hindu:today'].forEach(x=>need(hui,x,x));
['getTodayActivityCount','getEncounterProgress','optimisticDailyProgress','data-tab="progress"','repeat(5,1fr)'].forEach(x=>need(dbui,x,x));
['Starred Questions','My Words','View All','Practice All','chooseCount','Add to Practice','openCapture'].forEach(x=>need(savedui,x,x));
if(process.exitCode){console.error('\nValidation failed. Deployment must not proceed.');process.exit(process.exitCode)}
console.log('\n✅ English application contract validation passed.');
