const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(process.cwd(),'apps-script');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const fail=m=>{console.error(`\n❌ ${m}`);process.exitCode=1};
const ok=m=>console.log(`✅ ${m}`);
const need=(t,n,l)=>t.includes(n)?ok(l):fail(`${l} — missing: ${n}`);
const required=['Code.gs','DailyV2.gs','Demand.gs','NewPractice.gs','NewPracticeLive.gs','SourcePractice.gs','TopicPractice.gs','HinduVocab.gs','DashboardStats.gs','ProgressStats.gs','Saved.gs','StarredRevision.gs','MyWordTypes.gs','MyWordReconcile.gs','StarredRevisionDetail.gs','Index.html','Styles.html','AppJS.html','QuizJS.html','FastUI.html','TopicUI.html','NewPracticeUI.html','HinduUI.html','SourceUI.html','DemandUI.html','DashboardUI.html','SavedUI.html','MyWordsFinalUI.html','StarredRevisionUI.html','AddWordTypeUI.html','StarredViewDetailUI.html','appsscript.json'];
required.forEach(f=>fs.existsSync(path.join(root,f))?ok(`File present: ${f}`):fail(`Required Apps Script file missing: ${f}`));
if(process.exitCode)process.exit(process.exitCode);
const server=['Code.gs','DailyV2.gs','Demand.gs','NewPractice.gs','NewPracticeLive.gs','SourcePractice.gs','TopicPractice.gs','HinduVocab.gs','DashboardStats.gs','ProgressStats.gs','Saved.gs','StarredRevision.gs','MyWordTypes.gs','MyWordReconcile.gs','StarredRevisionDetail.gs'];
const front=['AppJS.html','QuizJS.html','FastUI.html','TopicUI.html','NewPracticeUI.html','HinduUI.html','SourceUI.html','DemandUI.html','DashboardUI.html','SavedUI.html','MyWordsFinalUI.html','StarredRevisionUI.html','AddWordTypeUI.html','StarredViewDetailUI.html'];
server.forEach(f=>{try{new vm.Script(read(f),{filename:f});ok(`Server JavaScript syntax: ${f}`)}catch(e){fail(`Server JavaScript syntax failed in ${f}: ${e.message}`)}});
front.forEach(f=>{try{const js=read(f).replace(/<\/?script[^>]*>/gi,'');new vm.Script(js,{filename:f});ok(`Frontend JavaScript syntax: ${f}`)}catch(e){fail(`Frontend JavaScript syntax failed in ${f}: ${e.message}`)}});
let manifest={};try{manifest=JSON.parse(read('appsscript.json'));ok('appsscript.json is valid JSON')}catch(e){fail(e.message)}
if(manifest.runtimeVersion==='V8')ok('Apps Script V8 runtime preserved');else fail('V8 runtime required');
if(manifest.webapp?.access==='ANYONE')ok('Web app access preserved as ANYONE');else fail('webapp.access must be ANYONE');
if(manifest.webapp?.executeAs==='USER_DEPLOYING')ok('Web app executes as deploying user');else fail('webapp.executeAs must be USER_DEPLOYING');
const code=read('Code.gs'),daily=read('DailyV2.gs'),demand=read('Demand.gs'),np=read('NewPractice.gs'),npl=read('NewPracticeLive.gs'),source=read('SourcePractice.gs'),topic=read('TopicPractice.gs'),hindu=read('HinduVocab.gs'),dash=read('DashboardStats.gs'),progress=read('ProgressStats.gs'),saved=read('Saved.gs'),starred=read('StarredRevision.gs'),typed=read('MyWordTypes.gs'),reconcile=read('MyWordReconcile.gs'),srdetail=read('StarredRevisionDetail.gs'),index=read('Index.html'),app=read('AppJS.html'),quiz=read('QuizJS.html'),fast=read('FastUI.html'),tui=read('TopicUI.html'),nui=read('NewPracticeUI.html'),dui=read('DemandUI.html'),sui=read('SourceUI.html'),hui=read('HinduUI.html'),dbui=read('DashboardUI.html'),savedui=read('SavedUI.html'),mwui=read('MyWordsFinalUI.html'),srui=read('StarredRevisionUI.html'),awt=read('AddWordTypeUI.html'),srv=read('StarredViewDetailUI.html');
need(code,"spreadsheetId: '1IgUGQZu6sp1STBCX6gyI5pHayLGVpmYYrkKGYdwkjak'",'Live English spreadsheet preserved');
['function doGet(','function getPracticeBatch(','function submitAnswer(','function setMarked(','function markMastered('].forEach(x=>need(code,x,x));
['function getBootstrapV2(','function getDailyBatchV2(','syncDailyCompletionsFromPerformanceV2_','pendingFromPrevious',"const DAILY_V2_HISTORY='Daily_History'"].forEach(x=>need(daily,x,x));
['function getDemandBatches(','function getDemandPracticeBatch(','function submitHinduAnswer(','function getHinduPracticeProgress('].forEach(x=>need(demand,x,x));
['function getNewPracticeHub(','function getNewPracticeBatch(','function getNewPracticeItems(','MY_SAVED_WORDS'].forEach(x=>need(np,x,x));
['function getNewPracticeHubLive(','function getNewPracticeBatchLive(','function newPracticePermanentPool_','function newPracticeType_','SPELL','Spelling Mistakes','function newPracticeSource_','newPracticeNewWordOrder_','getMyWordPracticeMeta_','reconcileReadyMyWordsFast_(false)'].forEach(x=>need(npl,x,x));
['function getSourceHub(','function getSourcePracticeBatch(','function getSourceItems(','THE_HINDU'].forEach(x=>need(source,x,x));
['function getTopicPracticeHub(','function getTopicPracticeBatch(','function getTopicPracticeItems(','started','newCount'].forEach(x=>need(topic,x,x));
['function addHinduToVocab(','function getSavedHinduQuestionIds(','captureHinduInMyWords_'].forEach(x=>need(hindu,x,x));
need(dash,'function getTodayActivityCount(','Today activity API');
['function getEncounterProgress(','todayNew','categories'].forEach(x=>need(progress,x,x));
['function captureMyWord(','Pending GPT','function setMyWordGPTEnrichment(','promoteMyWordToPractice(id)','function getPendingMyWords(','function getStarredQuestionList(','function promoteMyWordToPractice(','My_Words'].forEach(x=>need(saved,x,x));
['function getStarredRevisionHub(','function getStarredRevisionGroup(','function getStarredRevisionItems(','function getStarredRevisionBatch(','function logStarredRevisionFromUi(','Starred_Revision_Log',"label:'Days '","label:'Month '"].forEach(x=>need(starred,x,x));
['function captureMyWordTyped(','My_Word_Types','Spelling Mistakes','One Word Substitution','Phrasal Verbs','Idioms & Phrases','function getMyWordPracticeMeta_','function getMyWordPracticeTypeMap_','function myWordTypeToNewPractice_'].forEach(x=>need(typed,x,x));
['function reconcileReadyMyWordsFast_(','LockService.getScriptLock()','MYWORD_RECONCILE_SECONDS=45','block.setValues(data)','function reconcileReadyMyWords()','GPT_Status','Practice_Question_ID','myWordPracticeSpec_(type)'].forEach(x=>need(reconcile,x,x));
['function getStarredRevisionQuestionDetail(','readOnly:true'].forEach(x=>need(srdetail,x,x));
['id="homeView"','id="dailyStartBtn"','id="todayDoneBadge"',"include('FastUI')","include('TopicUI')","include('NewPracticeUI')","include('SavedUI')","include('MyWordsFinalUI')","include('StarredRevisionUI')","include('AddWordTypeUI')","include('StarredViewDetailUI')",'EPMyWordsUX.quickAdd()','EPStarredRevision.open()','Starred Revision','Loading daily plan…','onclick="EPApp.openSaved()"','onclick="EPSaved.openCapture()"'].forEach(x=>need(index,x,x));
['getBootstrapV2','getDailyBatchV2','Complete Previous Target','Fresh-first:'].forEach(x=>need(app,x,x));
["EPApp.call('submitAnswer'",'function next()','function pause()'].forEach(x=>need(quiz,x,x));
['window.EPFast','prefetch','source:hub','topic:hub','saved:hub'].forEach(x=>need(fast,x,x));
['Topic Practice','Started','New','Random','View All'].forEach(x=>need(tui,x,x));
['All New Practice','Practice by type','View All','Practice All','Practice New','Weak','Random','Starred','All Sources','getNewPracticeHubLive','getNewPracticeBatchLive'].forEach(x=>need(nui,x,x));
need(dui,'[10,20,50,100]','Demand random sizes 10/20/50/100');
['View All','Practice All','Weak','Random','kind===\'hindu\''].forEach(x=>need(sui,x,x));
['Practice Again · Round','hindu:today'].forEach(x=>need(hui,x,x));
['getTodayActivityCount','getEncounterProgress','optimisticDailyProgress','data-tab="progress"','repeat(5,1fr)','EPFast.get(\'progress\')'].forEach(x=>need(dbui,x,x));
['Starred Questions','My Words','Review','Pending GPT','onclick="EPSaved.addToPractice','openCapture'].forEach(x=>need(savedui,x,x));
['Pending enrichment','In Practice','quickAdd','saveQuick','saveEdit','Edit Saved Word'].forEach(x=>need(mwui,x,x));
['All Starred Revision','Day-wise Focus','Practice All','Practice New','Weak','Random','Mastered','getStarredRevisionHub','getStarredRevisionBatch','logStarredRevisionFromUi','__starredRevisionWrapped'].forEach(x=>need(srui,x,x));
['V','SM','OWS','PV','I/P','captureMyWordTyped','Dashboard Quick Add','EPSaved.saveCapture'].forEach(x=>need(awt,x,x));
['tap any question to view answer','getStarredRevisionQuestionDetail','View only · does not affect attempts or accuracy','EPStarredRevision.view=view'].forEach(x=>need(srv,x,x));
if(process.exitCode){console.error('\nValidation failed. Deployment must not proceed.');process.exit(process.exitCode)}
console.log('\n✅ English application contract validation passed.');
