"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import QuizRunner from "@/components/quiz-runner";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";

type SetRow={id:string;name:string;count:number;weakStarted:number;notes?:string;createdAt?:string;sourceOrigin?:string;promptRef?:string;categoryTag?:string;topicTag?:string;resumeIndex:number;completed:boolean;pinned:boolean;lastOpenedAt?:string;completedAt?:string};
type Pick={s:SetRow;mode:"weak"|"random"|"all";initialIndex:number};
export default function DemandPage(){
 const ready=useAuthGuard();const [rows,setRows]=useState<SetRow[]>([]);const [pick,setPick]=useState<Pick|null>(null);const [error,setError]=useState("");
 async function refresh(){setRows(await rpc<SetRow[]>("english_get_demand_sets"));}
 useEffect(()=>{if(ready)refresh().catch((e:any)=>setError(e.message));},[ready]);
 const load=useCallback(()=>pick?rpc<any[]>("english_get_demand_batch",{p_set_id:pick.s.id,p_mode:pick.mode,p_count:pick.mode==="all"?100:30}):Promise.resolve([]),[pick]);
 async function openSet(s:SetRow,mode:Pick["mode"]){setError("");try{const restart=s.completed&&mode==="all";await rpc("english_set_demand_state",{p_set_id:s.id,p_resume_index:restart?0:null,p_completed:restart?false:null,p_pinned:null});setPick({s:{...s,resumeIndex:restart?0:s.resumeIndex,completed:restart?false:s.completed},mode,initialIndex:mode==="all"&&!restart?s.resumeIndex||0:0});}catch(e:any){setError(e.message);}}
 async function togglePin(s:SetRow){const next=!s.pinned;setRows(x=>x.map(r=>r.id===s.id?{...r,pinned:next}:r));try{await rpc("english_set_demand_state",{p_set_id:s.id,p_resume_index:null,p_completed:null,p_pinned:next});await refresh();}catch(e:any){setError(e.message);setRows(x=>x.map(r=>r.id===s.id?{...r,pinned:!next}:r));}}
 function exitSet(){setPick(null);void refresh().catch(()=>{});}
 if(!ready)return <main className="center"><div className="muted">Checking session…</div></main>;
 if(pick)return <QuizRunner title={`${pick.s.name} · ${pick.mode}`} backHref="/english/demand" load={load} module="demand" initialIndex={pick.initialIndex} onPause={(index)=>rpc("english_set_demand_state",{p_set_id:pick.s.id,p_resume_index:index,p_completed:false,p_pinned:null})} onFinish={()=>rpc("english_set_demand_state",{p_set_id:pick.s.id,p_resume_index:0,p_completed:true,p_pinned:null})} onExit={exitSet}/>;
 return <main className="shell"><div className="topbar"><Link className="btn ghost" href="/english/practice">← Practice</Link><div><div className="brand">Demand Sets</div><div className="muted">Permanent custom practice sets. Existing questions stay canonical; set membership never duplicates them.</div></div></div>{error&&<div className="error-box">{error}</div>}<div className="study-list">{rows.length?rows.map(s=><article className="card stack" key={s.id}><div className="row"><div style={{minWidth:0,flex:1}}><h3 style={{margin:0}}>{s.name}</h3><div className="muted" style={{fontSize:11,marginTop:4}}>{s.count} questions · {s.weakStarted} weak/started{s.createdAt?` · ${new Date(s.createdAt).toLocaleDateString()}`:""}</div></div><button className={`btn ghost ${s.pinned?"warn":""}`} onClick={()=>togglePin(s)} aria-label={s.pinned?"Unpin set":"Pin set"}>{s.pinned?"★":"☆"}</button></div>{s.notes&&<div className="muted" style={{fontSize:12,lineHeight:1.45}}>{s.notes}</div>}<div className="row">{s.categoryTag&&<span className="pill">{s.categoryTag}</span>}{s.topicTag&&<span className="pill">{s.topicTag}</span>}{s.sourceOrigin&&<span className="pill">{s.sourceOrigin}</span>}<span className={`pill ${s.completed?"good":""}`}>{s.completed?"Completed":s.resumeIndex>0?`Resume Q${s.resumeIndex+1}`:"Not completed"}</span></div><div className="row"><button className="btn soft" disabled={!s.weakStarted} onClick={()=>openSet(s,"weak")}>Weak</button><button className="btn soft" onClick={()=>openSet(s,"random")}>Random</button><button className="btn primary" onClick={()=>openSet(s,"all")}>{s.completed?"Restart All":s.resumeIndex>0?"Resume All":"Practice All"}</button></div>{s.promptRef&&<small className="muted">Origin: {s.promptRef}</small>}</article>):<div className="empty-state"><h3>No Demand Sets yet</h3><p className="muted">Future GPT-created sets will appear here after canonical questions and set membership are inserted.</p></div>}</div></main>;
}
