"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";
type Summary={questions:number;main:number;rapidRecall:number;attempted:number;starred:number;difficult:number;notes:number};
export default function GkHome(){const ready=useAuthGuard();const[s,setS]=useState<Summary|null>(null);const[error,setError]=useState("");
useEffect(()=>{if(!ready)return;rpc<Summary>("gk_home_summary").then(setS).catch(e=>setError(e?.message||"GK is unavailable"));},[ready]);
if(!ready)return <main className="subject-home"><div className="loading-copy">Checking session…</div></main>;
return <main className="subject-home"><section className="subject-home-inner"><Link href="/" className="eyebrow">‹ Revision</Link><div className="subject-home-title"><strong>GK</strong><span>General Knowledge revision</span></div>{error&&<div className="error-box">{error}</div>}<section className="daily-hero"><span className="eyebrow">GK intelligence</span><h1>Build recall that sticks.</h1><p>{s?s.attempted+" attempted · "+s.starred+" starred · "+s.difficult+" difficult":"Loading your progress…"}</p></section><div className="subject-stack"><Link href="/gk/quiz?lane=MAIN" className="subject-choice active"><span className="subject-icon">M</span><span><b>Main</b><small>{s?.main??475} questions · full GK practice</small></span><i>›</i></Link><Link href="/gk/quiz?lane=RAPID" className="subject-choice active"><span className="subject-icon">R</span><span><b>Rapid Recall</b><small>{s?.rapidRecall??430} questions · fast revision</small></span><i>›</i></Link><Link href="/gk/quiz?lane=MAIN&filter=difficult" className="subject-choice"><span className="subject-icon">⚡</span><span><b>Difficult</b><small>Practice your marked challenges</small></span><i>›</i></Link><Link href="/gk/quiz?lane=MAIN&filter=starred" className="subject-choice"><span className="subject-icon">★</span><span><b>Starred</b><small>Return to saved questions</small></span><i>›</i></Link><Link href="/gk/quiz?lane=MAIN&filter=notes" className="subject-choice"><span className="subject-icon">▤</span><span><b>Notes</b><small>{s?.notes??3} saved notes</small></span><i>›</i></Link></div></section></main>}