"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { gkRpc, subscribeGkFresh } from "@/lib/gk-rpc";
import { useAuthGuard } from "@/lib/use-auth";
import type { GkProgress } from "@/lib/gk-types";

type SubjectInsight={subject:string;total:number;seen:number;unseen:number;persistentWeak:number;weak:number;fragile:number;mastered:number;guessed:number;unseenHighYield:number;retention:number;coverage:number;attention_score:number};
type SeriesInsight={seriesId:string;seriesKind:string;title:string;total:number;exposed:number;weak:number;mastered:number;completion:number;retention:number};
type Dashboard={ok:boolean;overview:{readiness:number;retention:number;bankExposure:number;provenKnowledge:number;weakBurden:number;persistentWeak:number;unresolvedGuesses:number;due:number;teacherContentCompletion:number;questionBankExposure:number;knowledgeRetention:number};needsAttention:SubjectInsight[];strongest:SubjectInsight[];subjects:SubjectInsight[];seriesProgress:SeriesInsight[];thisWeek:{factsSeen:number;weakResolved:number;unresolvedGuesses:number}};
type LearningSupport={verified_explanation?:string;exam_trap?:string;memory_tip?:string;confusion_contrast?:string;verification_status?:string;verification_source?:string;last_verified_at?:string;[key:string]:unknown};
type Story={ok:boolean;conceptId?:string;title?:string;subject?:string;history?:{questions:number;attempts:number;correct:number;wrong:number;guessed:number;firstSeen?:string;lastAttempt?:string;nextRecall?:string;currentState?:string};sources?:Array<{seriesTitle:string;seriesKind:string;lectureKey?:string;sourceLabel?:string;sourcePage?:string;sourceDate?:string}>;questions?:Array<{questionId:string;topic:string;state:string;attempts:number;wrong:number;guessed:number;nextRecall?:string}>;learningSupport?:LearningSupport;confusions?:Array<{label?:string;conceptA:string;conceptB:string;evidenceCount:number;verified:boolean}>};

const num=(v:unknown)=>Number(v||0);
const pct=(v:unknown)=>`${Math.round(num(v)*10)/10}%`;
const quiz=(p:Record<string,string|number>)=>`/gk/quiz?${new URLSearchParams(Object.entries(p).map(([k,v])=>[k,String(v)]))}`;
function dateLabel(v?:string){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"});}
function Metric({value,label,copy}:{value:string|number;label:string;copy?:string}){return <div className="gk-intel-metric"><strong>{value}</strong><span>{label}</span>{copy&&<small>{copy}</small>}</div>}
function ProgressBar({value}:{value:number}){return <div className="gk-intel-bar"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}

export default function GkIntelligencePage(){
 const ready=useAuthGuard();
 const[dash,setDash]=useState<Dashboard|null>(null),[legacy,setLegacy]=useState<GkProgress|null>(null),[story,setStory]=useState<Story|null>(null),[subject,setSubject]=useState(""),[error,setError]=useState("");
 useEffect(()=>{if(!ready)return;const p=new URLSearchParams(window.location.search);setSubject(p.get("subject")||"");const concept=p.get("concept")||"",question=p.get("question")||"",storyArgs={p_concept_id:concept||null,p_question_id:question||null};let live=true;setError("");setStory(null);const unsubDash=subscribeGkFresh<Dashboard>("gk_get_intelligence_dashboard",undefined,x=>{if(live&&x?.ok)setDash(x)}),unsubProgress=subscribeGkFresh<GkProgress>("gk_get_progress",undefined,x=>{if(live&&x?.ok)setLegacy(x)}),unsubStory=concept||question?subscribeGkFresh<Story>("gk_get_knowledge_story",storyArgs,x=>{if(live&&x?.ok)setStory(x)}):()=>{};Promise.allSettled([
   gkRpc<Dashboard>("gk_get_intelligence_dashboard").then(x=>{if(live&&x?.ok)setDash(x)}),
   gkRpc<GkProgress>("gk_get_progress").then(x=>{if(live&&x?.ok)setLegacy(x)}),
   concept||question?gkRpc<Story>("gk_get_knowledge_story",storyArgs).then(x=>{if(live)setStory(x)}):Promise.resolve()
 ]).then(rows=>{if(live&&rows.some(x=>x.status==="rejected"))setError("Some GK intelligence could not be refreshed.")});return()=>{live=false;unsubDash();unsubProgress();unsubStory();};},[ready]);
 const selected=useMemo(()=>dash?.subjects.find(x=>x.subject===subject)||null,[dash,subject]);
 if(!ready)return <main className="gk-intel-page"><div className="loading-copy">Checking session…</div></main>;
 if(!dash)return <main className="gk-intel-page"><div className="loading-copy">Loading GK intelligence…</div>{error&&<p>{error}</p>}</main>;
 if(story?.ok)return <KnowledgeStory story={story}/>;
 if(selected)return <SubjectDetail row={selected} weakConcepts={(legacy?.weakConcepts||[]).filter(x=>x.subject===selected.subject)}/>;
 const o=dash.overview,worst=dash.needsAttention?.[0],best=dash.strongest?.[0];
 return <main className="gk-intel-page">
  <section className="gk-intel-title"><div><span>Progress</span><h1>GK Readiness</h1><p>Course completion, bank exposure and retained knowledge are measured separately.</p></div><Link href="/gk/sprint" className="gk-intel-primary">Open SSC GK Sprint</Link></section>
  {error&&<div className="gk-intel-notice">{error}</div>}
  <section className="gk-intel-kpis">
   <Metric value={pct(o.readiness)} label="GK readiness" copy="Composite exam-readiness signal"/>
   <Metric value={pct(o.retention)} label="Retention" copy="Spaced recall accuracy"/>
   <Metric value={pct(o.bankExposure)} label="Bank exposure" copy="Questions genuinely seen"/>
   <Metric value={o.weakBurden} label="Weak burden" copy={`${o.persistentWeak} persistent · ${o.unresolvedGuesses} unresolved guesses`}/>
  </section>
  <section className="gk-intel-grid2">
   <article className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Needs Attention</span><h2>{worst?.subject||"No critical subject"}</h2></div>{worst&&<b>{worst.persistentWeak>0?"Critical":"Needs work"}</b>}</div>{worst&&<><p>{worst.persistentWeak} persistent weak · {worst.weak+worst.fragile} weak/fragile · {worst.guessed} unresolved guesses</p><div className="gk-intel-actions"><a href={`/gk/intelligence?subject=${encodeURIComponent(worst.subject)}`}>View insight</a><Link href={quiz({mode:"weak",lane:"MIXED",subject:worst.subject,count:20,title:`${worst.subject} · Weak Repair`})}>Practice weak</Link></div></>}</article>
   <article className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Strongest</span><h2>{best?.subject||"Build more evidence"}</h2></div>{best&&<b>{pct(best.retention)}</b>}</div>{best&&<><p>{pct(best.coverage)} exposed · {best.mastered} proven mastered</p><ProgressBar value={best.retention}/></>}</article>
  </section>
  <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>This Week</span><h2>Learning movement</h2></div></div><div className="gk-intel-week"><Metric value={dash.thisWeek.factsSeen} label="Facts seen"/><Metric value={dash.thisWeek.weakResolved} label="Weak resolved"/><Metric value={dash.thisWeek.unresolvedGuesses} label="Unresolved guesses"/></div></section>
  <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Different truths</span><h2>Progress is not one percentage</h2></div></div><div className="gk-intel-progress-truth">
   <div><span>Teacher Content Completion</span><b>{pct(o.teacherContentCompletion)}</b><ProgressBar value={o.teacherContentCompletion}/></div>
   <div><span>Question Bank Exposure</span><b>{pct(o.questionBankExposure)}</b><ProgressBar value={o.questionBankExposure}/></div>
   <div><span>Knowledge Retention</span><b>{pct(o.knowledgeRetention)}</b><ProgressBar value={o.knowledgeRetention}/></div>
   <div><span>Proven Knowledge</span><b>{pct(o.provenKnowledge)}</b><ProgressBar value={o.provenKnowledge}/></div>
  </div></section>
  <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Teacher Course</span><h2>Series progress</h2></div><Link href="/gk/teacher">Open Teacher PYQ</Link></div><div className="gk-intel-series">{dash.seriesProgress.map(x=><div className="gk-intel-seriesrow" key={x.seriesId}><div><b>{x.title}</b><small>{x.seriesKind.replaceAll("_"," ")} · {x.exposed}/{x.total} exposed · {x.weak} weak</small></div><strong>{pct(x.completion)}</strong><ProgressBar value={x.completion}/></div>)}</div></section>
  <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>SSC Coverage Matrix</span><h2>Subject readiness</h2></div><small>Tap for detail</small></div><div className="gk-intel-subjects">{dash.subjects.map(x=><a href={`/gk/intelligence?subject=${encodeURIComponent(x.subject)}`} className="gk-intel-subject" key={x.subject}><div><b>{x.subject}</b><small>{x.seen}/{x.total} seen · retention {pct(x.retention)} · {x.unseenHighYield} unseen teacher PYQ</small></div><span>{x.persistentWeak?`${x.persistentWeak} PW`:x.weak+x.fragile?`${x.weak+x.fragile} weak`:"›"}</span></a>)}</div></section>
  {(legacy?.weakConcepts?.length||0)>0&&<section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Knowledge Story</span><h2>Concepts that need repair</h2></div></div><div className="gk-intel-subjects">{legacy!.weakConcepts.slice(0,10).map(x=><a href={`/gk/intelligence?concept=${encodeURIComponent(x.conceptId)}`} className="gk-intel-subject" key={x.conceptId}><div><b>{x.topic||x.conceptId}</b><small>{x.subject} · {x.persistentWeak} persistent · {x.weak} weak · retention {pct(x.retentionAccuracy)}</small></div><span>Story ›</span></a>)}</div></section>}
 </main>;
}

function SubjectDetail({row,weakConcepts}:{row:SubjectInsight;weakConcepts:GkProgress["weakConcepts"]}){
 return <main className="gk-intel-page"><div className="gk-intel-back"><Link href="/gk/intelligence">← Progress</Link></div><section className="gk-intel-title"><div><span>Subject detail</span><h1>{row.subject}</h1><p>Coverage and retention stay separate; weak evidence remains actionable.</p></div><Link className="gk-intel-primary" href={quiz({mode:"weak",lane:"MIXED",subject:row.subject,count:20,title:`${row.subject} · Weak Repair`})}>Practice Weak</Link></section><section className="gk-intel-kpis"><Metric value={pct(row.coverage)} label="Coverage"/><Metric value={row.seen} label="Seen"/><Metric value={pct(row.retention)} label="Retention"/><Metric value={row.persistentWeak} label="Persistent Weak"/></section><section className="gk-intel-card"><div className="gk-intel-progress-truth"><div><span>Weak</span><b>{row.weak}</b></div><div><span>Fragile</span><b>{row.fragile}</b></div><div><span>Proven Mastered</span><b>{row.mastered}</b></div><div><span>Unseen Teacher PYQ</span><b>{row.unseenHighYield}</b></div></div></section><section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Weak Topics</span><h2>Repair by concept</h2></div></div><div className="gk-intel-subjects">{weakConcepts.length?weakConcepts.slice(0,20).map(x=><a href={`/gk/intelligence?concept=${encodeURIComponent(x.conceptId)}`} className="gk-intel-subject" key={x.conceptId}><div><b>{x.topic||x.conceptId}</b><small>{x.persistentWeak} persistent · {x.weak} weak · retention {pct(x.retentionAccuracy)}</small></div><span>Story ›</span></a>):<div className="gk-intel-empty">No weak concept family is currently surfaced for this subject.</div>}</div></section><div className="gk-intel-actions"><Link href={quiz({mode:"new",lane:"MAIN",subject:row.subject,count:20,title:`${row.subject} · Topic-wise PYQ`})}>Topic-wise PYQ</Link><Link href={quiz({mode:"random",lane:"MIXED",subject:row.subject,count:25,title:`${row.subject} · Mixed Retrieval`})}>Mixed retrieval</Link></div></main>;
}

function KnowledgeStory({story}:{story:Story}){
 const h=story.history||{questions:0,attempts:0,correct:0,wrong:0,guessed:0};
 const support:LearningSupport=story.learningSupport||{};
 return <main className="gk-intel-page"><div className="gk-intel-back"><Link href="/gk/intelligence">← Progress</Link></div><section className="gk-intel-title"><div><span>Knowledge Story</span><h1>{story.title||story.conceptId||"Concept"}</h1><p>{story.subject||"GK"} · one knowledge family across every teacher/source appearance.</p></div>{story.conceptId&&<Link className="gk-intel-primary" href={quiz({mode:"weak",lane:"MIXED",concept:story.conceptId,count:20,title:`${story.title||"Concept"} · Repair`})}>Practice concept</Link>}</section><section className="gk-intel-kpis"><Metric value={h.attempts} label="Attempts"/><Metric value={h.correct} label="Correct"/><Metric value={h.wrong} label="Wrong"/><Metric value={h.guessed} label="Guessed"/></section><section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Current evidence</span><h2>{h.currentState||"Learning"}</h2></div><b>Next recall {dateLabel(h.nextRecall)}</b></div><div className="gk-intel-timeline"><div><span>First seen</span><b>{dateLabel(h.firstSeen)}</b></div><div><span>Last attempt</span><b>{dateLabel(h.lastAttempt)}</b></div><div><span>Questions in family</span><b>{h.questions}</b></div></div></section><section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Sources</span><h2>Teacher provenance</h2></div></div><div className="gk-intel-subjects">{(story.sources||[]).map((s,i)=><div className="gk-intel-subject" key={`${s.seriesTitle}-${s.lectureKey}-${i}`}><div><b>{s.seriesTitle}</b><small>{[s.lectureKey,s.sourceLabel,s.sourcePage&&`Page ${s.sourcePage}`].filter(Boolean).join(" · ")}</small></div><span>{s.seriesKind?.replaceAll("_"," ")}</span></div>)}</div></section>{Object.keys(support).length>0&&<section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Learning support</span><h2>Verified enrichment</h2></div></div>{support.verified_explanation&&<p><b>Explanation:</b> {support.verified_explanation}</p>}{support.exam_trap&&<p><b>Exam trap:</b> {support.exam_trap}</p>}{support.memory_tip&&<p><b>Memory tip:</b> {support.memory_tip}</p>}{support.confusion_contrast&&<p><b>Contrast:</b> {support.confusion_contrast}</p>}<small>{support.verification_status||"UNVERIFIED"} · Teacher content remains the authority.</small></section>}{(story.confusions?.length||0)>0&&<section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Confusion engine</span><h2>Nearby concepts</h2></div></div><div className="gk-intel-subjects">{story.confusions!.map((c,i)=><div className="gk-intel-subject" key={i}><div><b>{c.label||`${c.conceptA} ↔ ${c.conceptB}`}</b><small>{c.evidenceCount} evidence signals</small></div><span>{c.verified?"Verified":"Review"}</span></div>)}</div></section>}</main>;
}
