const MATHS = Object.freeze({
  TITLE: 'Maths Revision',
  SHEETS: { QUESTIONS:'Questions', STATE:'State', ATTEMPTS:'Attempts', NOTES:'Notes', SETTINGS:'Settings', GENERATED:'Generated_Practice', PLAN:'Chapter_Plan' },
  DEFAULTS: { current_day:1, today_chapter:'Coordinate Geometry', daily_chapter_size:30, daily_reinforcement_size:10, practice_more_size:20, keep_chapter_until_introduced:true }
});

function doGet(){
  ensureMathsInfrastructure_();
  return HtmlService.createHtmlOutputFromFile('Index')
    .setTitle(MATHS.TITLE)
    .addMetaTag('viewport','width=device-width, initial-scale=1, viewport-fit=cover')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}
function setupMathsRevision(){ensureMathsInfrastructure_();return getBootstrap()}
function getBootstrap(){ensureMathsInfrastructure_();const q=getQuestions_(),s=getStateMap_();return{ok:true,title:MATHS.TITLE,dashboard:buildDashboard_(q,s),chapters:buildChapters_(q,s),library:buildLibrary_(q,s),filters:buildFilters_(q.concat(getGenerated_())),settings:getSettings_()}}

function getQuiz(r){ensureMathsInfrastructure_();r=r||{};const mode=String(r.mode||'daily'),state=getStateMap_(),qs=mode==='generated'?getGenerated_():getQuestions_();let pool=[],title='Maths Revision';
if(mode==='daily'){const c=String(getSetting_('today_chapter',MATHS.DEFAULTS.today_chapter)),n=Number(getSetting_('daily_chapter_size',30)),rn=Number(getSetting_('daily_reinforcement_size',10)),e=qs.filter(q=>active_(q)&&q.chapter===c&&!isMastered_(state[q.question_id])),fresh=shuffle_(e.filter(q=>!Number((state[q.question_id]||{}).attempts||0))),seen=shuffle_(e.filter(q=>Number((state[q.question_id]||{}).attempts||0)>0));pool=fresh.slice(0,n);if(pool.length<n)pool=pool.concat(seen.slice(0,n-pool.length));if(rn>0){const sup=qs.filter(q=>active_(q)&&q.chapter!==c&&!isMastered_(state[q.question_id])&&(isMarked_(state[q.question_id])||['Fraction Patterns','Calculation Patterns','Triplets'].includes(q.chapter)));pool=unique_(pool.concat(shuffle_(sup).slice(0,rn)))}title='Day '+getSetting_('current_day',1)+' · '+c}
if(mode==='practice_more'){const c=String(r.chapter||getSetting_('today_chapter',MATHS.DEFAULTS.today_chapter)),n=Number(r.count||getSetting_('practice_more_size',20));pool=shuffle_(qs.filter(q=>active_(q)&&q.chapter===c&&!isMastered_(state[q.question_id]))).slice(0,n);title='Practice More · '+c}
if(mode==='chapter'){const c=String(r.chapter||'');pool=qs.filter(q=>active_(q)&&q.chapter===c);title=c+' · Complete Bank'}
if(mode==='library'){const c=String(r.cluster||'Formula');pool=filterLibrary_(qs,state,c);title='Library · '+c}
if(mode==='ondemand'||mode==='generated'){pool=shuffle_(filterOnDemand_(qs,state,r)).slice(0,Math.max(1,Number(r.count||20)));title=mode==='generated'?'Generated Practice':'On Demand'}
pool=unique_(pool);if(!pool.length)return{ok:false,message:'No eligible questions found.'};const notes=getNotesMap_();return{ok:true,mode,title,questions:pool.map(q=>toClientQuestion_(q,state[q.question_id],notes[q.question_id]||''))}}

function saveQuestionAction(p){ensureMathsInfrastructure_();p=p||{};const id=String(p.questionId||'');if(!id)throw new Error('Missing question ID');const patch={};if(Object.prototype.hasOwnProperty.call(p,'mastered'))patch.mastered=!!p.mastered;if(Object.prototype.hasOwnProperty.call(p,'marked'))patch.marked=!!p.marked;if(p.recordAttempt){patch.attempt=true;patch.result=String(p.result||'seen');patch.responseSec=Number(p.responseSec||0)}const st=upsertState_(id,patch);if(p.recordAttempt)getSheet_(MATHS.SHEETS.ATTEMPTS).appendRow([Utilities.getUuid(),new Date(),id,String(p.result||'seen'),Number(p.responseSec||0),String(p.mode||''),!!st.mastered,!!st.marked]);return{ok:true,state:st}}
function saveNote(id,note){ensureMathsInfrastructure_();id=String(id||'');const sh=getSheet_(MATHS.SHEETS.NOTES),rows=sheetObjects_(sh),f=rows.find(r=>String(r.question_id)===id),t=String(note||'');if(f)sh.getRange(f.__row,2,1,2).setValues([[t,new Date()]]);else sh.appendRow([id,t,new Date(),false]);return{ok:true,note:t}}
function completeDailySession(){ensureMathsInfrastructure_();advanceDailyPlan_();const q=getQuestions_(),s=getStateMap_();return{ok:true,dashboard:buildDashboard_(q,s)}}

function buildDashboard_(qs,s){const c=String(getSetting_('today_chapter',MATHS.DEFAULTS.today_chapter)),a=qs.filter(q=>active_(q)&&q.chapter===c),m=a.filter(q=>isMastered_(s[q.question_id])).length,f=a.filter(q=>!isMastered_(s[q.question_id])&&!Number((s[q.question_id]||{}).attempts||0)).length;return{day:Number(getSetting_('current_day',1)),todayChapter:c,total:qs.filter(active_).length,mastered:qs.filter(q=>active_(q)&&isMastered_(s[q.question_id])).length,marked:qs.filter(q=>active_(q)&&isMarked_(s[q.question_id])).length,chapterTotal:a.length,chapterMastered:m,chapterRemaining:a.length-m,freshRemaining:f,generated:getGenerated_().length}}
function buildChapters_(qs,s){const m={};qs.filter(active_).forEach(q=>{const c=q.chapter||'Other';if(!m[c])m[c]={chapter:c,total:0,mastered:0,remaining:0,topics:{}};m[c].total++;isMastered_(s[q.question_id])?m[c].mastered++:m[c].remaining++;const t=q.topic||'General';m[c].topics[t]=(m[c].topics[t]||0)+1});return Object.values(m).sort((a,b)=>a.chapter.localeCompare(b.chapter))}
function buildLibrary_(qs,s){const n=getNotesMap_();return{formulas:qs.filter(q=>String(q.card_type).toLowerCase()==='formula').length,methods:qs.filter(q=>['method','pattern','trap'].includes(String(q.card_type).toLowerCase())).length,fractions:qs.filter(q=>/fraction/i.test((q.chapter||'')+' '+(q.topic||''))).length,triplets:qs.filter(q=>/triplet/i.test((q.chapter||'')+' '+(q.topic||''))).length,marked:qs.filter(q=>isMarked_(s[q.question_id])).length,notes:Object.keys(n).filter(id=>String(n[id]||'').trim()).length,recent:Math.min(20,qs.length)}}
function buildFilters_(qs){const u=a=>Array.from(new Set(a.filter(Boolean).map(String))).sort((a,b)=>a.localeCompare(b));return{chapters:u(qs.map(q=>q.chapter)),topics:u(qs.map(q=>q.topic)),subtopics:u(qs.map(q=>q.subtopic)),cardTypes:u(qs.map(q=>q.card_type)),difficulties:u(qs.map(q=>q.difficulty))}}
function filterLibrary_(qs,s,c){c=String(c||'').toLowerCase();if(c==='formula'||c==='formulas')return qs.filter(q=>String(q.card_type).toLowerCase()==='formula');if(c==='methods')return qs.filter(q=>['method','pattern','trap'].includes(String(q.card_type).toLowerCase()));if(c==='fractions')return qs.filter(q=>/fraction/i.test((q.chapter||'')+' '+(q.topic||'')));if(c==='triplets')return qs.filter(q=>/triplet/i.test((q.chapter||'')+' '+(q.topic||'')));if(c==='marked')return qs.filter(q=>isMarked_(s[q.question_id]));if(c==='notes'){const n=getNotesMap_(),ids=new Set(Object.keys(n).filter(id=>String(n[id]||'').trim()));return qs.filter(q=>ids.has(q.question_id))}if(c==='recent')return qs.slice(-20);return qs}
function filterOnDemand_(qs,s,r){return qs.filter(q=>active_(q)&&(!r.chapter||q.chapter===r.chapter)&&(!r.topic||q.topic===r.topic)&&(!r.subtopic||q.subtopic===r.subtopic)&&(!r.cardType||q.card_type===r.cardType)&&(!r.difficulty||q.difficulty===r.difficulty)&&(!r.markedOnly||isMarked_(s[q.question_id]))&&(!r.activeOnly||!isMastered_(s[q.question_id]))&&(!r.masteredOnly||isMastered_(s[q.question_id])))}
function toClientQuestion_(q,s,n){const triplet=/triplet/i.test((q.chapter||'')+' '+(q.topic||'')+' '+(q.subtopic||''));return{id:q.question_id,chapter:q.chapter,topic:q.topic,subtopic:q.subtopic,cardType:q.card_type,prompt:q.prompt,answer:q.answer,explanation:q.explanation,memoryCue:q.memory_cue,difficulty:q.difficulty,diagramType:triplet?'':q.diagram_type,diagramJson:triplet?'':q.diagram_json,sourceFile:q.source_file,sourcePage:q.source_page,mastered:isMastered_(s),marked:isMarked_(s),attempts:Number((s||{}).attempts||0),note:n||''}}

function advanceDailyPlan_(){const qs=getQuestions_().filter(active_),s=getStateMap_(),c=String(getSetting_('today_chapter',MATHS.DEFAULTS.today_chapter)),keep=bool_(getSetting_('keep_chapter_until_introduced',true)),unseen=qs.filter(q=>q.chapter===c&&!isMastered_(s[q.question_id])&&!Number((s[q.question_id]||{}).attempts||0));let next=c;if(!(keep&&unseen.length)){const p=sheetObjects_(getSheet_(MATHS.SHEETS.PLAN)).filter(r=>r.chapter&&String(r.status||'').toLowerCase()!=='continuous').sort((a,b)=>Number(a.order||999)-Number(b.order||999)),av=p.map(r=>String(r.chapter)).filter(x=>qs.some(q=>q.chapter===x&&!isMastered_(s[q.question_id])));if(av.length){const i=av.indexOf(c);next=av[(i+1+av.length)%av.length]}}setSetting_('current_day',Number(getSetting_('current_day',1))+1);setSetting_('today_chapter',next)}
function getQuestions_(){return sheetObjects_(getSheet_(MATHS.SHEETS.QUESTIONS)).filter(r=>r.question_id)}function getGenerated_(){return sheetObjects_(getSheet_(MATHS.SHEETS.GENERATED)).filter(r=>r.question_id)}
function getStateMap_(){const o={};sheetObjects_(getSheet_(MATHS.SHEETS.STATE)).forEach(r=>{if(r.question_id)o[String(r.question_id)]=r});return o}function getNotesMap_(){const o={};sheetObjects_(getSheet_(MATHS.SHEETS.NOTES)).forEach(r=>{if(r.question_id)o[String(r.question_id)]=String(r.note||'')});return o}
function upsertState_(id,p){const sh=getSheet_(MATHS.SHEETS.STATE),rows=sheetObjects_(sh),f=rows.find(r=>String(r.question_id)===id),s=f?Object.assign({},f):{question_id:id,attempts:0,mastered:false,marked:false};if(p.attempt)s.attempts=Number(s.attempts||0)+1;if(Object.prototype.hasOwnProperty.call(p,'mastered'))s.mastered=!!p.mastered;if(Object.prototype.hasOwnProperty.call(p,'marked'))s.marked=!!p.marked;if(p.attempt){s.last_attempt=new Date();s.last_result=p.result||'seen';s.last_response_sec=Number(p.responseSec||0)}const q=getQuestions_().concat(getGenerated_()).find(x=>x.question_id===id)||{},row=[id,Number(s.attempts||0),!!s.mastered,!!s.marked,s.last_attempt||'',s.last_result||'',Number(s.last_response_sec||0),q.chapter||'',q.topic||'',q.subtopic||''];f?sh.getRange(f.__row,1,1,row.length).setValues([row]):sh.appendRow(row);return{question_id:id,attempts:row[1],mastered:row[2],marked:row[3]}}
function getSettings_(){const o={};sheetObjects_(getSheet_(MATHS.SHEETS.SETTINGS)).forEach(r=>{if(r.key)o[String(r.key)]=r.value});return o}function getSetting_(k,d){const s=getSettings_();return Object.prototype.hasOwnProperty.call(s,k)?s[k]:d}function setSetting_(k,v){const sh=getSheet_(MATHS.SHEETS.SETTINGS),f=sheetObjects_(sh).find(r=>String(r.key)===String(k));f?sh.getRange(f.__row,2).setValue(v):sh.appendRow([k,v])}
function ensureMathsInfrastructure_(){const ss=SpreadsheetApp.getActive();ensureSheet_(ss,MATHS.SHEETS.QUESTIONS,['Question_ID','Chapter','Topic','Subtopic','Card_Type','Prompt','Answer','Explanation','Memory_Cue','Difficulty','Marked_Default','Mastered_Default','Diagram_Type','Diagram_JSON','Source_File','Source_Page','Source_URL','Status']);ensureSheet_(ss,MATHS.SHEETS.STATE,['Question_ID','Attempts','Mastered','Marked','Last_Attempt','Last_Result','Last_Response_Sec','Chapter','Topic','Subtopic']);ensureSheet_(ss,MATHS.SHEETS.ATTEMPTS,['Attempt_ID','Timestamp','Question_ID','Result','Response_Sec','Mode','Mastered_After','Marked_After']);ensureSheet_(ss,MATHS.SHEETS.NOTES,['Question_ID','Note','Updated_At','Pinned']);const st=ensureSheet_(ss,MATHS.SHEETS.SETTINGS,['Key','Value']);ensureSheet_(ss,MATHS.SHEETS.GENERATED,['Question_ID','Chapter','Topic','Subtopic','Card_Type','Prompt','Answer','Explanation','Memory_Cue','Difficulty','Marked_Default','Mastered_Default','Diagram_Type','Diagram_JSON','Source_File','Source_Page','Source_URL','Status']);ensureSheet_(ss,MATHS.SHEETS.PLAN,['Order','Chapter','Target_Per_Day','Status','Introduced','Mastered']);if(st.getLastRow()===1){Object.keys(MATHS.DEFAULTS).forEach(k=>st.appendRow([k,MATHS.DEFAULTS[k]]));st.appendRow(['app_title',MATHS.TITLE])}}
function ensureSheet_(ss,n,h){let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);return sh}function getSheet_(n){const sh=SpreadsheetApp.getActive().getSheetByName(n);if(!sh)throw new Error('Missing sheet: '+n);return sh}
function sheetObjects_(sh){if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v[0].map(key_);return v.slice(1).map((r,i)=>{const o={__row:i+2};h.forEach((x,j)=>o[x]=r[j]);return o})}
function key_(s){return String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}function bool_(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}function isMastered_(s){return!!(s&&bool_(s.mastered))}function isMarked_(s){return!!(s&&bool_(s.marked))}function active_(q){return String(q.status||'Active').toLowerCase()!=='inactive'}function shuffle_(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}function unique_(a){const s=new Set;return a.filter(q=>q&&q.question_id&&!s.has(q.question_id)&&s.add(q.question_id))}