"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import QuizRunner from "@/components/quiz-runner";
import { EnglishLoading } from "@/components/english-frame";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";

type Child={key:string;date:string;count:number;weak:number;keys?:string[]};
type Source={key:string;name:string;count:number;weak:number;recent:number;latest?:string;categorySummary?:string;children?:Child[]};
type Pick={keys:string[];name:string;mode:string;count:number};
type Pending={keys:string[];name:string;mode:string;available:number};
type Item={id:string;question_id?:string;word?:string;question?:string;weak?:boolean;started?:boolean;attempts?:number;date?:string;status?:string;starred?:boolean};
type Scope={kind:"date"|"month";name:string;keys:string[];count:number;weak:number;children?:Child[]};

const icon=(key:string)=>key==="HANDWRITTEN"?"✍️":key==="THE_HINDU"?"📰":key==="SCREENSHOTS"?"🖼️":"📚";
const niceDate=(value:string)=>{try{return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(`${value}T12:00:00+05:30`));}catch{return value;}};
const monthLabel=(value:string)=>{try{return new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(`${value}-15T12:00:00+05:30`));}catch{return value;}};
function isoDate(value?:string){const text=String(value||"").trim();let m=text.match(/(20\d{2})[-_/](\d{1,2})[-_/](\d{1,2})/);if(m)return `${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`;m=text.match(/(\d{1,2})[-\s](Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*[-\s](20\d{2})/i);if(m){const months=["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"];return `${m[3]}-${String(months.indexOf(m[2].slice(0,3).toLowerCase())+1).padStart(2,"0")}-${m[1].padStart(2,"0")}`;}return "";}
function childKeys(c:Child){return c.keys?.length?c.keys:[c.key];}
function normaliseSources(input:Source[]){const hinduRows=input.filter(s=>s.key==="THE_HINDU"||/the\s*hindu/i.test(`${s.key} ${s.name}`));if(!hinduRows.length)return input;const parent=hinduRows.find(s=>s.key==="THE_HINDU");const dates=new Map<string,Child>();for(const c of parent?.children||[])dates.set(c.date,{...c,keys:childKeys(c)});for(const s of hinduRows){if(s===parent)continue;const date=isoDate(s.latest)||isoDate(s.name)||isoDate(s.key);if(!date)continue;const hit=dates.get(date);if(hit){hit.keys=[...new Set([...childKeys(hit),s.key])];continue;}dates.set(date,{key:s.key,date,count:Number(s.count||0),weak:Number(s.weak||0),keys:[s.key]});}const children=[...dates.values()].sort((a,b)=>b.date.localeCompare(a.date));const childCount=children.reduce((n,c)=>n+c.count,0),childWeak=children.reduce((n,c)=>n+c.weak,0);const hindu:Source={key:"THE_HINDU",name:"The Hindu",count:Number(parent?.count||childCount),weak:Number(parent?.weak||childWeak),recent:Number(parent?.recent||0),latest:parent?.latest||children[0]?.date,categorySummary:parent?.categorySummary,children};const rest=input.filter(s=>!hinduRows.includes(s));rest.push(hindu);const rank=(s:Source)=>s.key==="HANDWRITTEN"?1:s.key==="THE_HINDU"?2:s.key==="SCREENSHOTS"?3:4;return rest.sort((a,b)=>rank(a)-rank(b)||String(b.latest||"").localeCompare(String(a.latest||""))||a.name.localeCompare(b.name));}
function monthsFrom(children:Child[]){const groups=new Map<string,Child[]>();for(const child of children){const key=child.date.slice(0,7);groups.set(key,[...(groups.get(key)||[]),child]);}return [...groups.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([month,days])=>({month,days,count:days.reduce((n,c)=>n+c.count,0),weak:days.reduce((n,c)=>n+c.weak,0),keys:[...new Set(days.flatMap(childKeys))]}));}
function uniqueRows<T extends {id?:string;question_id?:string}>(groups:T[][]){const map=new Map<string,T>();for(const row of groups.flat()){const id=String(row.id||row.question_id||"");if(id&&!map.has(id))map.set(id,row);}return [...map.values()];}

export default function SourcesPage(){
 const ready=useAuthGuard();const[rows,setRows]=useState<Source[]>([]);const[current,setCurrent]=useState<Source|null>(null);const[scope,setScope]=useState<Scope|null>(null);const[scopeParent,setScopeParent]=useState<Scope|null>(null);const[pick,setPick]=useState<Pick|null>(null);const[pending,setPending]=useState<Pending|null>(null);const[browse,setBrowse]=useState<{name:string;items:Item[]}|null>(null);const[returnHref,setReturnHref]=useState("/english/practice");const[error,setError]=useState("");
 useEffect(()=>{try{const p=new URLSearchParams(window.location.search).get("return");if(p?.startsWith("/english"))setReturnHref(p)}catch{}},[]);
 useEffect(()=>{if(ready)rpc<Source[]>("english_get_source_hub").then(x=>setRows(normaliseSources(Array.isArray(x)?x:[]))).catch((e:any)=>setError(e.message))},[ready]);
 const load=useCallback(async()=>{if(!pick)return[];const groups=await Promise.all(pick.keys.map(key=>rpc<any[]>("english_get_source_batch",{p_source_key:key,p_mode:"all",p_count:100})));let items=uniqueRows(groups).map((q:any)=>q.id? q:{...q,id:q.question_id});if(pick.mode==="new")items=items.filter((q:any)=>Number(q.attempts||0)===0||String(q.status||"")==="New");if(pick.mode==="weak")items=items.filter((q:any)=>["Persistent Weak","Weak","Fragile"].includes(String(q.status||""))||q.weak);if(pick.mode==="starred")items=items.filter((q:any)=>!!q.starred);if(pick.mode==="random")items=[...items].sort(()=>Math.random()-.5);return items.slice(0,Math.max(1,pick.count));},[pick]);
 if(!ready)return <EnglishLoading text="Checking session…"/>;
 if(pick)return <QuizRunner title={pick.name} backHref="/english/sources" load={load} module="source" onExit={()=>setPick(null)}/>;
 async function viewAll(keys:string[],name:string){try{const groups=await Promise.all(keys.map(key=>rpc<Item[]>("english_get_source_items",{p_source_key:key})));setBrowse({name,items:uniqueRows(groups)})}catch(e:any){setError(e.message)}}
 function start(keys:string[],name:string,mode:string,count:number){setPick({keys,name,mode,count})}
 function actions(x:{keys:string[];name:string;count:number;weak:number}){return <div className="legacy-actions"><button className="btn soft mini" disabled={!x.count} onClick={()=>void viewAll(x.keys,x.name)}>View All</button><button className="btn soft mini" disabled={!x.count} onClick={()=>start(x.keys,x.name,"all",x.count)}>Practice All</button><button className="btn soft mini" disabled={!x.count} onClick={()=>setPending({keys:x.keys,name:x.name,mode:"new",available:x.count})}>Practice New</button><button className="btn soft mini" disabled={!x.weak} onClick={()=>setPending({keys:x.keys,name:x.name,mode:"weak",available:x.weak})}>Weak</button><button className="btn soft mini" disabled={!x.count} onClick={()=>setPending({keys:x.keys,name:x.name,mode:"random",available:x.count})}>Random</button><button className="btn soft mini" disabled={!x.count} onClick={()=>setPending({keys:x.keys,name:x.name,mode:"starred",available:x.count})}>Starred</button></div>}
 function openDay(c:Child,parent:Scope|null=null){setScopeParent(parent);setScope({kind:"date",name:`The Hindu · ${niceDate(c.date)}`,keys:childKeys(c),count:c.count,weak:c.weak});}
 function openMonth(month:string,days:Child[],keys:string[],count:number,weak:number){setScopeParent(null);setScope({kind:"month",name:`The Hindu · ${monthLabel(month)}`,keys,count,weak,children:days});}
 const countSheet=pending?<Count pending={pending} close={()=>setPending(null)} run={n=>{start(pending.keys,pending.name,pending.mode,n);setPending(null)}}/>:null;
 if(browse)return <div className="legacy-subpage"><div className="legacy-subhead"><button className="btn ghost legacy-back" onClick={()=>setBrowse(null)}>← Back</button><div><h1>{browse.name} · View All</h1><p>{browse.items.length} items</p></div></div><div className="legacy-browse">{browse.items.map((x,i)=><article className="legacy-browse-item" key={x.question_id||x.id}><b>{i+1}. {x.word||x.question||x.id}</b>{x.word&&x.question?<div>{x.question}</div>:null}<div>{x.date?`${niceDate(x.date)} · `:""}{x.weak?"Weak · ":""}{x.started?"Started":"New"}</div></article>)}</div></div>;
 if(current){
  if(scope){return <div className="legacy-subpage"><div className="legacy-subhead"><button className="btn ghost legacy-back" onClick={()=>{if(scopeParent){setScope(scopeParent);setScopeParent(null)}else setScope(null)}}>← {scopeParent?monthLabel(String(scopeParent.name.match(/([A-Za-z]+\s20\d{2})/)?.[1]||"Month")):"The Hindu"}</button><div><h1>{scope.name}</h1><p>{scope.count} questions{scope.weak?` · ${scope.weak} weak`:""}</p></div></div><div className="legacy-card"><div className="source-group-note">Use the same six actions for this {scope.kind==="month"?"month":"day"}. Practice stays limited to this archive slice.</div>{actions(scope)}</div>{scope.kind==="month"&&scope.children?.length?<><h2 className="legacy-section-title">Dates in {scope.name.replace("The Hindu · ","")}</h2><div className="legacy-list">{scope.children.map(c=><button className="legacy-row" key={c.date} onClick={()=>openDay(c,scope)}><span className="legacy-row-copy"><b>📰 {niceDate(c.date)}</b><small>{c.count} questions{c.weak?` · ${c.weak} weak`:""}</small></span><span className="legacy-chevron">›</span></button>)}</div></>:null}{countSheet}</div>}
  if(current.key==="THE_HINDU"){const children=current.children||[],recent=children.slice(0,10),months=monthsFrom(children.slice(10)),allKeys=children.length?[...new Set(children.flatMap(childKeys))]:[current.key];return <div className="legacy-subpage"><div className="legacy-subhead"><button className="btn ghost legacy-back" onClick={()=>{setCurrent(null);setScope(null)}}>← All Sources</button><div><h1>📰 The Hindu</h1><p>{current.count} questions · {children.length} dated batches</p></div></div><div className="legacy-card"><div className="source-group-note">All Hindu vocabulary is kept under one source. Use the six actions below for the complete archive.</div>{actions({keys:allKeys,name:"The Hindu · All History",count:current.count,weak:current.weak})}</div><h2 className="legacy-section-title">Recent 10 Days</h2><div className="legacy-list">{recent.map(c=><button className="legacy-row" key={c.date} onClick={()=>openDay(c)}><span className="legacy-row-copy"><b>📰 {niceDate(c.date)}</b><small>{c.count} questions{c.weak?` · ${c.weak} weak`:""}</small></span><span className="legacy-chevron">›</span></button>)}</div>{months.length?<><h2 className="legacy-section-title">Monthly Archive</h2><div className="source-group-note">After the newest 10 dated batches, older Hindu content automatically stacks month-wise.</div><div className="legacy-list">{months.map(m=><button className="legacy-row" key={m.month} onClick={()=>openMonth(m.month,m.days,m.keys,m.count,m.weak)}><span className="legacy-row-copy"><b>🗂️ {monthLabel(m.month)}</b><small>{m.count} questions · {m.days.length} dated batches{m.weak?` · ${m.weak} weak`:""}</small></span><span className="legacy-chevron">›</span></button>)}</div></>:null}{countSheet}</div>}
  return <div className="legacy-subpage"><div className="legacy-subhead"><button className="btn ghost legacy-back" onClick={()=>setCurrent(null)}>← All Sources</button><div><h1>{icon(current.key)} {current.name}</h1><p>{current.count} questions{current.weak?` · ${current.weak} weak`:""}</p></div></div><div className="legacy-card">{actions({keys:[current.key],name:current.name,count:current.count,weak:current.weak})}</div>{countSheet}</div>
 }
 return <div className="legacy-subpage"><div className="legacy-subhead"><Link className="btn ghost legacy-back" href={returnHref}>← Back</Link><div><h1>Sources / PDFs</h1><p>Source → date → questions. The Hindu stays in one rolling archive.</p></div></div>{error&&<div className="error-box">{error}</div>}<div className="legacy-list">{rows.map(s=><button className="legacy-row" key={s.key} onClick={()=>{setCurrent(s);setScope(null);setScopeParent(null)}}><span className="legacy-row-copy"><b>{icon(s.key)} {s.name}</b><small>{s.count} questions{s.weak?` · ${s.weak} weak`:""}{s.key==="THE_HINDU"&&s.children?.length?` · ${s.children.length} dated batches`:""}</small></span><span className="legacy-chevron">›</span></button>)}</div></div>
}
function Count({pending,close,run}:{pending:Pending;close:()=>void;run:(n:number)=>void}){const label=pending.mode==="new"?"Practice New":pending.mode==="weak"?"Weak":pending.mode==="starred"?"Starred":"Random";return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="legacy-sheet"><h3>{pending.name} · {label}</h3><div className="legacy-muted">Choose number of questions</div><div className="legacy-counts">{[10,20,50,100].map(n=><button key={n} onClick={()=>run(n)}>{n}</button>)}</div><button className="btn ghost full-width" style={{marginTop:12}} onClick={close}>Cancel</button></div></div>}
