"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import QuizRunner from "@/components/quiz-runner";
import { EnglishLoading } from "@/components/english-frame";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";
type Child={key:string;date:string;count:number;weak:number};type Source={key:string;name:string;count:number;weak:number;recent:number;latest?:string;categorySummary?:string;children?:Child[]};type Pick={key:string;name:string;mode:string;count:number};type Pending={key:string;name:string;mode:string;available:number};type Item={id:string;question_id?:string;word?:string;question?:string;weak?:boolean;started?:boolean;attempts?:number;date?:string};
const icon=(key:string)=>key==="HANDWRITTEN"?"✍️":key==="THE_HINDU"?"📰":key==="SCREENSHOTS"?"🖼️":"📚";
const niceDate=(value:string)=>{try{return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(`${value}T12:00:00+05:30`));}catch{return value;}};
export default function SourcesPage(){const ready=useAuthGuard();const[rows,setRows]=useState<Source[]>([]);const[current,setCurrent]=useState<Source|null>(null);const[pick,setPick]=useState<Pick|null>(null);const[pending,setPending]=useState<Pending|null>(null);const[browse,setBrowse]=useState<{name:string;items:Item[]}|null>(null);const[returnHref,setReturnHref]=useState("/english/practice");const[error,setError]=useState("");useEffect(()=>{try{const p=new URLSearchParams(window.location.search).get("return");if(p?.startsWith("/english"))setReturnHref(p)}catch{}},[]);useEffect(()=>{if(ready)rpc<Source[]>("english_get_source_hub").then(setRows).catch((e:any)=>setError(e.message))},[ready]);const load=useCallback(()=>pick?rpc<any[]>("english_get_source_batch",{p_source_key:pick.key,p_mode:pick.mode,p_count:pick.count}):Promise.resolve([]),[pick]);if(!ready)return <EnglishLoading text="Checking session…"/>;if(pick)return <QuizRunner title={pick.name} backHref="/english/sources" load={load} module="source" onExit={()=>setPick(null)}/>;
 async function viewAll(key:string,name:string){try{setBrowse({name,items:await rpc<Item[]>("english_get_source_items",{p_source_key:key})})}catch(e:any){setError(e.message)}}
 function actions(key:string,name:string,count:number,weak:number){return <div className="legacy-actions four"><button className="btn soft mini" disabled={!count} onClick={()=>void viewAll(key,name)}>View All</button><button className="btn soft mini" disabled={!count} onClick={()=>setPick({key,name,mode:"all",count:100})}>Practice All</button><button className="btn soft mini" disabled={!weak} onClick={()=>setPending({key,name,mode:"weak",available:weak})}>Weak</button><button className="btn soft mini" disabled={!count} onClick={()=>setPending({key,name,mode:"random",available:count})}>Random</button></div>}
 if(browse)return <div className="legacy-subpage"><div className="legacy-subhead"><button className="btn ghost legacy-back" onClick={()=>setBrowse(null)}>← Sources</button><div><h1>{browse.name} · View All</h1><p>{browse.items.length} items</p></div></div><div className="legacy-browse">{browse.items.map((x,i)=><article className="legacy-browse-item" key={x.question_id||x.id}><b>{i+1}. {x.word||x.question||x.id}</b>{x.word&&x.question?<div>{x.question}</div>:null}<div>{x.date?`${niceDate(x.date)} · `:""}{x.weak?"Weak · ":""}{x.started?"Started":"New"}</div></article>)}</div></div>;
 if(current)return <div className="legacy-subpage"><div className="legacy-subhead"><button className="btn ghost legacy-back" onClick={()=>setCurrent(null)}>← All Sources</button><div><h1>{icon(current.key)} {current.name}</h1><p>{current.count} questions{current.weak?` · ${current.weak} weak`:""}</p></div></div>{current.key==="THE_HINDU"?<><div className="source-group-note">Hindu history is organised by the day it was added. Open one date to view or practise only that batch.</div><div className="legacy-card"><div className="legacy-row-copy"><b>All Hindu History</b><small>{current.count} questions across {current.children?.length||0} dated batches</small></div>{actions(current.key,"The Hindu · All History",current.count,current.weak)}</div><h2 className="legacy-section-title">Daily Batches</h2><div className="legacy-list">{current.children?.map(c=><article className="legacy-card source-date-card" key={c.key}><div className="source-date-head"><div><b>{niceDate(c.date)}</b><div className="legacy-muted">{c.count} words{c.weak?` · ${c.weak} weak`:""}</div></div><span className="pill">{c.date}</span></div>{actions(c.key,`The Hindu · ${niceDate(c.date)}`,c.count,c.weak)}</article>)}</div></>:<div className="legacy-card">{actions(current.key,current.name,current.count,current.weak)}</div>}{pending&&<Count pending={pending} close={()=>setPending(null)} run={n=>{setPick({key:pending.key,name:pending.name,mode:pending.mode,count:n});setPending(null)}}/>}</div>;
 return <div className="legacy-subpage"><div className="legacy-subhead"><Link className="btn ghost legacy-back" href={returnHref}>← Back</Link><div><h1>Sources / PDFs</h1><p>Source → batch/date → questions. PDFs, screenshots and Hindu history stay separated.</p></div></div>{error&&<div className="error-box">{error}</div>}<div className="legacy-list">{rows.map(s=><button className="legacy-row" key={s.key} onClick={()=>setCurrent(s)}><span className="legacy-row-copy"><b>{icon(s.key)} {s.name}</b><small>{s.count} questions{s.weak?` · ${s.weak} weak`:""}{s.key==="THE_HINDU"&&s.children?.length?` · ${s.children.length} dated batches`:""}</small></span><span className="legacy-chevron">›</span></button>)}</div></div>}
function Count({pending,close,run}:{pending:Pending;close:()=>void;run:(n:number)=>void}){return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="legacy-sheet"><h3>{pending.name} · {pending.mode==="weak"?"Weak":"Random"}</h3><div className="legacy-muted">{pending.available} available · choose questions</div><div className="legacy-counts">{[10,20,50,100].map(n=><button key={n} onClick={()=>run(n)}>{n}</button>)}</div><button className="btn ghost full-width" style={{marginTop:12}} onClick={close}>Cancel</button></div></div>}
