"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import QuizRunner from "@/components/quiz-runner";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";

type HistoryRow={type:string;label:string;fromDay:number;toDay:number;generated:number;practised:number;date?:string};
type Hub={version:string;dailyTarget:number;stats:{totalConcepts:number;exposed:number;exposurePercent:number;due:number;weak:number;recallWeak:number;difficult:number;starred:number;mastered:number;freshVariantChecks:number;eligible:number};today:{date:string;count:number;target:number;ready:boolean;sourceId:string};available:{smart:number;weak:number;difficult:number;starred:number;random:number;all:number};sizes:number[];history:HistoryRow[]};
type Pick={kind:"mastery"|"today"|"history";label:string;mode?:string;count?:number;fromDay?:number;toDay?:number};

export default function PhrasalPage(){
 const ready=useAuthGuard();const [hub,setHub]=useState<Hub|null>(null);const [pick,setPick]=useState<Pick|null>(null);const [error,setError]=useState("");
 useEffect(()=>{if(ready)rpc<Hub>("english_get_phrasal_hub").then(setHub).catch((e:any)=>setError(e.message))},[ready]);
 const load=useCallback(()=>{if(!pick)return Promise.resolve([]);if(pick.kind==="today")return rpc<any[]>("english_get_phrasal_today");if(pick.kind==="history")return rpc<any[]>("english_get_phrasal_history_batch",{p_from_day:pick.fromDay,p_to_day:pick.toDay});return rpc<any[]>("english_get_phrasal_batch",{p_mode:pick.mode,p_count:pick.count||20})},[pick]);
 if(!ready)return <main className="center"><div className="muted">Checking session…</div></main>;
 if(pick)return <QuizRunner title={pick.label} backHref="/english/phrasal" load={load} module={pick.kind==="today"?"phrasaldaily":"phrasalrevision"}/>;
 const s=hub?.stats,a=hub?.available;
 return <main className="shell"><div className="topbar"><Link className="btn ghost" href="/english">← English</Link><div><div className="brand">Phrasal Verb Mastery</div><div className="muted">Concept-first revision · recognition, recall and confusion intelligence.</div></div></div>{error&&<div className="card error">{error}</div>}<div className="grid"><div className="card"><h3>Bank Exposure</h3><div className="metric">{s?`${s.exposed}/${s.totalConcepts}`:"—"}</div><div className="muted">{s?`${s.exposurePercent}% exposed`:"Loading…"}</div></div><div className="card"><h3>Due</h3><div className="metric">{s?.due??"—"}</div><div className="muted">Concept-level due clock</div></div><div className="card"><h3>Weak</h3><div className="metric">{s?.weak??"—"}</div><div className="muted">Includes {s?.recallWeak??"—"} recall-weak</div></div><div className="card"><h3>Mastered</h3><div className="metric">{s?.mastered??"—"}</div><div className="muted">Central proven mastery</div></div></div><section className="card stack" style={{marginTop:16}}><div><h3>Smart Revision</h3><div className="muted">One concept per slot. The selector chooses the learning lane first, then the least-exposed preferred variant.</div></div><div className="row">{["smart","weak","difficult","starred","random"].map(m=><button key={m} className="btn" disabled={!a||Number(a[m as keyof typeof a]||0)===0} onClick={()=>setPick({kind:"mastery",mode:m,count:20,label:`Phrasal Verb · ${m[0].toUpperCase()+m.slice(1)}`})}>{m} {a?`(${a[m as keyof typeof a]})`:""}</button>)}<button className="btn" disabled={!a?.all} onClick={()=>setPick({kind:"mastery",mode:"all",count:100,label:"Phrasal Verb · Practice All"})}>all {a?`(${a.all})`:""}</button></div></section><section className="card stack" style={{marginTop:16}}><div className="row"><div><h3>Today&apos;s {hub?.today?.count||hub?.dailyTarget||20}</h3><div className="muted">{hub?.today?.ready?`${hub.today.count} permanent questions · ${hub.today.date}`:"Today’s permanent batch has not been added yet."}</div></div><span className="spacer"/><span className="pill">{hub?.today?.ready?"READY":"PENDING"}</span></div><button className="btn primary" disabled={!hub?.today?.ready} onClick={()=>setPick({kind:"today",label:`Phrasal Verb · Today's ${hub?.today?.count||20}`})}>Practice today</button></section><h3 style={{marginTop:24}}>Phrasal Daily History</h3><div className="stack">{hub?.history?.length?hub.history.map((h,i)=><div className="card row" key={`${h.type}-${h.fromDay}-${i}`}><div><strong>{h.label}</strong><div className="muted">{h.generated} generated · {h.practised} practised{h.date?` · ${h.date}`:""}</div></div><span className="spacer"/><button className="btn" disabled={!h.generated} onClick={()=>setPick({kind:"history",fromDay:h.fromDay,toDay:h.toDay,label:`Phrasal Verb · ${h.label}`})}>Practice</button></div>):<div className="card muted">No permanent Phrasal history yet.</div>}</div></main>
}
