-- English V2 final-30-day routing layer.
-- This is additive to question_state: canonical learning state remains authoritative.
-- Route state answers where/how to practise; it never duplicates a canonical question.

create table if not exists english.learning_route_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null references english.questions(question_id) on delete cascade,
  route text not null default 'unclassified' check (route in ('unclassified','starred_unresolved','fast_track','targeted')),
  fast_track_status text check (fast_track_status is null or fast_track_status in ('ready','waiting','mastered')),
  origins text[] not null default '{}'::text[],
  baseline_wrong integer not null default 0,
  entered_fast_track_at timestamptz,
  next_fast_track_check timestamptz,
  fast_track_mastered_at timestamptz,
  pending_failure_decision boolean not null default false,
  kept_failure_count integer not null default 0,
  last_failure_at timestamptz,
  targeted_at timestamptz,
  targeted_recovered_at timestamptz,
  starred_resolved_at timestamptz,
  last_route_reason text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id,question_id)
);

create table if not exists english.learning_route_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null references english.questions(question_id) on delete cascade,
  event_at timestamptz not null default now(),
  event_type text not null,
  from_route text,
  to_route text,
  origin text,
  reason text,
  event_key text unique,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists english_learning_route_state_route_idx on english.learning_route_state(user_id,route,fast_track_status,next_fast_track_check);
create index if not exists english_learning_route_state_origins_gin on english.learning_route_state using gin(origins);
create index if not exists english_learning_route_events_lookup_idx on english.learning_route_events(user_id,question_id,event_at desc);
create index if not exists english_learning_route_events_origin_idx on english.learning_route_events(user_id,origin,to_route,event_at desc);

alter table english.learning_route_state enable row level security;
alter table english.learning_route_events enable row level security;
revoke all on english.learning_route_state from public,anon,authenticated;
revoke all on english.learning_route_events from public,anon,authenticated;
grant all on english.learning_route_state to service_role;
grant all on english.learning_route_events to service_role;

create or replace function english.route_add_origin(p_origins text[],p_origin text)
returns text[] language sql immutable as $$
select case when nullif(btrim(coalesce(p_origin,'')),'') is null then coalesce(p_origins,'{}'::text[])
 else array(select distinct x from unnest(coalesce(p_origins,'{}'::text[])||array[btrim(p_origin)]) x where nullif(x,'') is not null order by x) end;
$$;

create or replace function english.route_event(
 p_user_id uuid,p_question_id text,p_event_type text,p_from text,p_to text,p_origin text,p_reason text,
 p_metadata jsonb default '{}'::jsonb,p_event_key text default null
) returns void language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
begin
 insert into english.learning_route_events(user_id,question_id,event_type,from_route,to_route,origin,reason,metadata,event_key)
 values(p_user_id,p_question_id,p_event_type,p_from,p_to,nullif(btrim(coalesce(p_origin,'')),''),p_reason,coalesce(p_metadata,'{}'::jsonb),p_event_key)
 on conflict(event_key) where event_key is not null do nothing;
end $$;

create or replace function english.route_has_active_star(p_user_id uuid,p_question_id text)
returns boolean language sql stable security definer
set search_path=pg_catalog,english,auth as $$
select coalesce((select e.action='STAR' from english.star_events e where e.user_id=p_user_id and e.question_id=p_question_id order by e.event_at desc,e.id desc limit 1),false);
$$;

create or replace function english.route_is_saved(p_user_id uuid,p_question_id text)
returns boolean language sql stable security definer
set search_path=pg_catalog,english,auth as $$
select exists(select 1 from english.saved_items s where s.user_id=p_user_id and s.active and s.practice_question_id=p_question_id);
$$;

create or replace function english.route_targeted_reason(p_user_id uuid,p_question_id text)
returns text language plpgsql stable security definer
set search_path=pg_catalog,english,auth as $$
declare s english.question_state%rowtype; d boolean:=false; r english.learning_route_state%rowtype;
begin
 select * into s from english.question_state where user_id=p_user_id and question_id=p_question_id;
 select coalesce(difficult,false) into d from english.difficult_state where user_id=p_user_id and question_id=p_question_id;
 if not found then d:=false; end if;
 select * into r from english.learning_route_state where user_id=p_user_id and question_id=p_question_id;
 if coalesce(s.mastered,false) then return ''; end if;
 if d then return 'Difficult'; end if;
 if r.route='targeted' then return coalesce(nullif(r.last_route_reason,''),'Targeted'); end if;
 if coalesce(s.status,'New') in ('Persistent Weak','Weak','Fragile') then
   if r.route='fast_track' and (r.pending_failure_decision or r.kept_failure_count=1)
      and coalesce(s.wrong,0)<=coalesce(r.baseline_wrong,0)+1 then return ''; end if;
   return coalesce(s.status,'Weak');
 end if;
 if r.route='fast_track' then
   if coalesce(s.wrong,0)>coalesce(r.baseline_wrong,0)+coalesce(r.kept_failure_count,0) then return 'New wrong evidence'; end if;
 else
   if coalesce(s.wrong,0)>0 then return 'Unresolved wrong history'; end if;
 end if;
 return '';
end $$;

create or replace function english.route_to_fast_track(
 p_user_id uuid,p_question_id text,p_origin text,p_reason text,p_force_recovery boolean default false
) returns jsonb language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
declare old english.learning_route_state%rowtype; s english.question_state%rowtype; v_reason text; v_origins text[]; v_wrong integer:=0; v_now timestamptz:=now();
begin
 select * into s from english.question_state where user_id=p_user_id and question_id=p_question_id;
 v_wrong:=coalesce(s.wrong,0);
 if coalesce(s.mastered,false) then return jsonb_build_object('ok',false,'reason','already-mastered'); end if;
 if english.route_has_active_star(p_user_id,p_question_id) and coalesce(p_origin,'')<>'From Starred' then
   return jsonb_build_object('ok',false,'reason','starred-unresolved');
 end if;
 v_reason:=english.route_targeted_reason(p_user_id,p_question_id);
 if not p_force_recovery and nullif(v_reason,'') is not null then return jsonb_build_object('ok',false,'reason',v_reason); end if;
 select * into old from english.learning_route_state where user_id=p_user_id and question_id=p_question_id;
 v_origins:=english.route_add_origin(coalesce(old.origins,'{}'::text[]),p_origin);
 insert into english.learning_route_state(user_id,question_id,route,fast_track_status,origins,baseline_wrong,entered_fast_track_at,next_fast_track_check,fast_track_mastered_at,pending_failure_decision,kept_failure_count,targeted_recovered_at,last_route_reason,updated_at)
 values(p_user_id,p_question_id,'fast_track','ready',v_origins,v_wrong,v_now,v_now,null,false,0,case when old.route='targeted' then v_now else old.targeted_recovered_at end,p_reason,v_now)
 on conflict(user_id,question_id) do update set
   route='fast_track',fast_track_status='ready',origins=v_origins,baseline_wrong=v_wrong,
   entered_fast_track_at=v_now,next_fast_track_check=v_now,fast_track_mastered_at=null,
   pending_failure_decision=false,kept_failure_count=0,
   targeted_recovered_at=case when english.learning_route_state.route='targeted' then v_now else english.learning_route_state.targeted_recovered_at end,
   last_route_reason=p_reason,updated_at=v_now;
 perform english.route_event(p_user_id,p_question_id,case when old.route='targeted' then 'RECOVER' else 'ROUTE' end,old.route,'fast_track',p_origin,p_reason,
   jsonb_build_object('baselineWrong',v_wrong),null);
 return jsonb_build_object('ok',true,'route','fast_track','status','ready','origins',v_origins);
end $$;

create or replace function english.route_to_targeted(
 p_user_id uuid,p_question_id text,p_origin text,p_reason text
) returns jsonb language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
declare old english.learning_route_state%rowtype; v_origins text[]; v_now timestamptz:=now();
begin
 select * into old from english.learning_route_state where user_id=p_user_id and question_id=p_question_id;
 v_origins:=english.route_add_origin(coalesce(old.origins,'{}'::text[]),p_origin);
 insert into english.learning_route_state(user_id,question_id,route,fast_track_status,origins,baseline_wrong,entered_fast_track_at,next_fast_track_check,fast_track_mastered_at,pending_failure_decision,kept_failure_count,last_failure_at,targeted_at,last_route_reason,updated_at)
 values(p_user_id,p_question_id,'targeted',null,v_origins,coalesce((select wrong from english.question_state where user_id=p_user_id and question_id=p_question_id),0),old.entered_fast_track_at,null,old.fast_track_mastered_at,false,0,old.last_failure_at,coalesce(old.targeted_at,v_now),p_reason,v_now)
 on conflict(user_id,question_id) do update set
   route='targeted',fast_track_status=null,origins=v_origins,next_fast_track_check=null,pending_failure_decision=false,kept_failure_count=0,
   targeted_at=coalesce(english.learning_route_state.targeted_at,v_now),last_route_reason=p_reason,updated_at=v_now;
 if old.route is distinct from 'targeted' then
   perform english.route_event(p_user_id,p_question_id,'ROUTE',old.route,'targeted',p_origin,p_reason,'{}'::jsonb,null);
 end if;
 return jsonb_build_object('ok',true,'route','targeted','reason',p_reason,'origins',v_origins);
end $$;

create or replace function english.route_unstar_for_resolution(p_user_id uuid,p_question_id text,p_reason text)
returns void language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
begin
 if english.route_has_active_star(p_user_id,p_question_id) then
   insert into english.star_events(user_id,question_id,event_at,starred_date,day_no,action)
   values(p_user_id,p_question_id,now(),(now() at time zone 'Asia/Kolkata')::date,null,'UNSTAR');
   update english.learning_route_state set starred_resolved_at=now(),updated_at=now() where user_id=p_user_id and question_id=p_question_id;
   perform english.route_event(p_user_id,p_question_id,'STAR_RESOLVED',null,null,'From Starred',p_reason,'{}'::jsonb,null);
 end if;
end $$;

create or replace function english.route_after_attempt_trigger()
returns trigger language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
declare
 q english.questions%rowtype; r english.learning_route_state%rowtype; d boolean:=false; v_module text:=lower(coalesce(new.module,''));
 v_attempts integer:=0; v_wrong integer:=0; v_ft_wrong integer:=0; v_ft_clean_days integer:=0; v_required integer:=1;
 v_saved boolean:=false; v_star boolean:=false; v_star_at timestamptz; v_day date:=(new.attempted_at at time zone 'Asia/Kolkata')::date;
begin
 select * into q from english.questions where question_id=new.question_id;
 if not found or not q.active then return new; end if;
 select * into r from english.learning_route_state where user_id=new.user_id and question_id=new.question_id;
 select coalesce(difficult,false) into d from english.difficult_state where user_id=new.user_id and question_id=new.question_id;
 if not found then d:=false; end if;
 v_saved:=english.route_is_saved(new.user_id,new.question_id);
 select e.action='STAR',e.event_at into v_star,v_star_at from english.star_events e where e.user_id=new.user_id and e.question_id=new.question_id order by e.event_at desc,e.id desc limit 1;
 if not found then v_star:=false;v_star_at:=null; end if;
 select count(*)::int,count(*) filter(where not coalesce(correct,false))::int into v_attempts,v_wrong from english.attempts where user_id=new.user_id and question_id=new.question_id;

 if v_module='fasttrack' and r.route='fast_track' then
   if coalesce(new.correct,false) then
     select count(distinct (a.attempted_at at time zone 'Asia/Kolkata')::date)::int
       into v_ft_clean_days from english.attempts a
       where a.user_id=new.user_id and a.question_id=new.question_id and lower(coalesce(a.module,''))='fasttrack'
         and coalesce(a.correct,false) and a.attempted_at>=coalesce(r.entered_fast_track_at,'epoch'::timestamptz);
     v_required:=case when exists(select 1 from unnest(coalesce(r.origins,'{}'::text[])) x where x='From Starred' or x like 'Recovered %') then 2 else 1 end;
     update english.learning_route_state set
       pending_failure_decision=false,
       fast_track_status=case when v_ft_clean_days>=v_required then 'mastered' else 'waiting' end,
       next_fast_track_check=case when v_ft_clean_days>=v_required then null else now()+interval '2 days' end,
       fast_track_mastered_at=case when v_ft_clean_days>=v_required then coalesce(fast_track_mastered_at,now()) else fast_track_mastered_at end,
       last_route_reason=case when v_ft_clean_days>=v_required then 'Fast Track verification complete' else 'Waiting for spaced Fast Track check' end,
       updated_at=now()
     where user_id=new.user_id and question_id=new.question_id;
     perform english.route_event(new.user_id,new.question_id,'VERIFY','fast_track','fast_track',null,'Clean Fast Track recall',jsonb_build_object('cleanDays',v_ft_clean_days,'required',v_required),null);
   else
     select count(*)::int into v_ft_wrong from english.attempts a where a.user_id=new.user_id and a.question_id=new.question_id and lower(coalesce(a.module,''))='fasttrack' and not coalesce(a.correct,false) and a.attempted_at>=coalesce(r.entered_fast_track_at,'epoch'::timestamptz);
     update english.learning_route_state set last_failure_at=now(),updated_at=now() where user_id=new.user_id and question_id=new.question_id;
     perform english.route_event(new.user_id,new.question_id,'FAIL','fast_track','fast_track',null,'Fast Track recall missed',jsonb_build_object('failureCount',v_ft_wrong),null);
     if v_ft_wrong>=2 then
       perform english.route_to_targeted(new.user_id,new.question_id,'Fast Track Failure','Repeated Fast Track failure');
     else
       update english.learning_route_state set pending_failure_decision=true,fast_track_status='ready',next_fast_track_check=null,last_route_reason='Fast Track failure needs learner decision',updated_at=now()
       where user_id=new.user_id and question_id=new.question_id;
     end if;
   end if;
   return new;
 end if;

 if v_star then
   if not coalesce(new.correct,false) then
     perform english.route_unstar_for_resolution(new.user_id,new.question_id,'Starred recall failed');
     perform english.route_to_targeted(new.user_id,new.question_id,'From Starred','Starred recall failed');
     return new;
   elsif v_star_at is not null and v_day>(v_star_at at time zone 'Asia/Kolkata')::date then
     perform english.route_unstar_for_resolution(new.user_id,new.question_id,'Spaced clean Starred recall');
     if v_wrong=0 and not d then
       perform english.route_to_fast_track(new.user_id,new.question_id,'From Starred','Starred uncertainty resolved by spaced clean recall',true);
     else
       perform english.route_to_targeted(new.user_id,new.question_id,'From Starred','Starred item retains negative learning evidence');
     end if;
     return new;
   end if;
 end if;

 if not coalesce(new.correct,false) then
   if r.route='fast_track' then
     perform english.route_to_targeted(new.user_id,new.question_id,'Fast Track','Negative evidence outside Fast Track verification');
   elsif v_saved then
     perform english.route_to_targeted(new.user_id,new.question_id,'From My Saved','Saved-item recall failed');
   elsif v_module='bankcoverage' then
     perform english.route_to_targeted(new.user_id,new.question_id,'Bank Coverage','Bank Coverage discovery failed');
   end if;
   return new;
 end if;

 if v_module='bankcoverage' and v_attempts=1 and v_wrong=0 and english.is_genuine_bank_question(q) and not d and not v_star then
   perform english.route_to_fast_track(new.user_id,new.question_id,'Bank Coverage','First-time clean Bank Coverage discovery',false);
 end if;
 if v_saved and v_wrong=0 and not d and not v_star then
   select * into r from english.learning_route_state where user_id=new.user_id and question_id=new.question_id;
   if not found or r.route in ('unclassified','fast_track') then
     perform english.route_to_fast_track(new.user_id,new.question_id,'From My Saved','Clean Saved-item evidence',false);
   end if;
 end if;
 return new;
end $$;

drop trigger if exists english_learning_route_after_attempt on english.attempts;
create trigger english_learning_route_after_attempt after insert on english.attempts for each row execute function english.route_after_attempt_trigger();

create or replace function english.route_after_question_state_trigger()
returns trigger language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
declare r english.learning_route_state%rowtype; reason text; d boolean:=false; clean_days integer:=0; wrong_after integer:=0;
begin
 if coalesce(new.mastered,false) then return new; end if;
 select * into r from english.learning_route_state where user_id=new.user_id and question_id=new.question_id;
 if coalesce(new.last_marked,false) and (not found or r.route='fast_track' or r.route='unclassified') then
   insert into english.learning_route_state(user_id,question_id,route,fast_track_status,origins,baseline_wrong,last_route_reason,updated_at)
   values(new.user_id,new.question_id,'starred_unresolved',null,english.route_add_origin(coalesce(r.origins,'{}'::text[]),'From Starred'),coalesce(new.wrong,0),'Active Starred uncertainty',now())
   on conflict(user_id,question_id) do update set route='starred_unresolved',fast_track_status=null,origins=english.route_add_origin(english.learning_route_state.origins,'From Starred'),last_route_reason='Active Starred uncertainty',updated_at=now();
   if r.route='fast_track' then perform english.route_event(new.user_id,new.question_id,'ROUTE','fast_track','starred_unresolved','From Starred','Learner expressed uncertainty','{}'::jsonb,null); end if;
   return new;
 end if;
 reason:=english.route_targeted_reason(new.user_id,new.question_id);
 if nullif(reason,'') is not null then
   perform english.route_to_targeted(new.user_id,new.question_id,case when reason='Difficult' then 'Difficult' else 'Central Intelligence' end,reason);
   return new;
 end if;
 select * into r from english.learning_route_state where user_id=new.user_id and question_id=new.question_id;
 if r.route='targeted' and new.status in ('Strong','Proven Mastered') and coalesce(new.last_result,false) then
   select coalesce(difficult,false) into d from english.difficult_state where user_id=new.user_id and question_id=new.question_id;
   if not found then d:=false; end if;
   if not d and not english.route_has_active_star(new.user_id,new.question_id) then
     select count(distinct (a.attempted_at at time zone 'Asia/Kolkata')::date)::int,
            count(*) filter(where not coalesce(a.correct,false))::int
       into clean_days,wrong_after
     from english.attempts a where a.user_id=new.user_id and a.question_id=new.question_id and a.attempted_at>=coalesce(r.targeted_at,now()) and coalesce(a.correct,false);
     select count(*)::int into wrong_after from english.attempts a where a.user_id=new.user_id and a.question_id=new.question_id and a.attempted_at>=coalesce(r.targeted_at,now()) and not coalesce(a.correct,false);
     if clean_days>=2 and wrong_after=0 then
       perform english.route_to_fast_track(new.user_id,new.question_id,'Recovered Targeted','Targeted item recovered with spaced clean evidence',true);
     end if;
   end if;
 end if;
 return new;
end $$;

drop trigger if exists english_learning_route_after_state on english.question_state;
create trigger english_learning_route_after_state after insert or update of status,wrong,last_marked,mastered,last_result on english.question_state for each row execute function english.route_after_question_state_trigger();

create or replace function english.route_after_difficult_trigger()
returns trigger language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
begin
 if coalesce(new.difficult,false) then
   if english.route_has_active_star(new.user_id,new.question_id) then
     perform english.route_unstar_for_resolution(new.user_id,new.question_id,'Difficult overrides Starred uncertainty');
     perform english.recompute_question_state(new.user_id,new.question_id);
   end if;
   perform english.route_to_targeted(new.user_id,new.question_id,'Difficult','Learner marked Difficult');
 end if;
 return new;
end $$;

drop trigger if exists english_learning_route_after_difficult on english.difficult_state;
create trigger english_learning_route_after_difficult after insert or update of difficult on english.difficult_state for each row execute function english.route_after_difficult_trigger();

create or replace function english.bootstrap_learning_routes(p_user_id uuid)
returns jsonb language plpgsql security definer
set search_path=pg_catalog,english,auth as $$
declare x record; ft integer:=0; tg integer:=0; su integer:=0; mastered integer:=0; extra integer:=0; v_origins text[]; v_target boolean; v_saved boolean; v_any_star boolean;
begin
 for x in
   select s.question_id,s.status,s.attempts,s.wrong,s.mastered,coalesce(d.difficult,false) difficult,
          english.route_has_active_star(p_user_id,s.question_id) active_star,english.is_genuine_bank_question(q) genuine
   from english.question_state s join english.questions q on q.question_id=s.question_id and q.active
   left join english.difficult_state d on d.user_id=p_user_id and d.question_id=s.question_id
   where s.user_id=p_user_id and s.attempts>0
     and (english.is_genuine_bank_question(q) or english.route_is_saved(p_user_id,s.question_id) or s.last_marked or exists(select 1 from english.star_events se where se.user_id=p_user_id and se.question_id=s.question_id))
   order by s.question_id
 loop
   if exists(select 1 from english.learning_route_state r where r.user_id=p_user_id and r.question_id=x.question_id) then continue; end if;
   v_saved:=english.route_is_saved(p_user_id,x.question_id);
   v_any_star:=exists(select 1 from english.star_events se where se.user_id=p_user_id and se.question_id=x.question_id);
   v_origins:='{}'::text[];
   if x.genuine then v_origins:=english.route_add_origin(v_origins,'Historical Clean Bank'); end if;
   if v_saved then v_origins:=english.route_add_origin(v_origins,'From My Saved'); end if;
   if v_any_star then v_origins:=english.route_add_origin(v_origins,'From Starred'); end if;
   if x.mastered then mastered:=mastered+case when x.genuine then 1 else 0 end; continue; end if;
   v_target:=x.status in ('Persistent Weak','Weak','Fragile') or x.difficult or coalesce(x.wrong,0)>0;
   if v_target then
     insert into english.learning_route_state(user_id,question_id,route,origins,baseline_wrong,targeted_at,last_route_reason,updated_at)
     values(p_user_id,x.question_id,'targeted',v_origins,coalesce(x.wrong,0),now(),case when x.difficult then 'Difficult' when x.status in ('Persistent Weak','Weak','Fragile') then x.status else 'Unresolved wrong history' end,now());
     perform english.route_event(p_user_id,x.question_id,'BOOTSTRAP',null,'targeted',case when x.active_star then 'From Starred' when v_saved then 'From My Saved' else 'Historical Bank' end,
       case when x.difficult then 'Difficult' when x.status in ('Persistent Weak','Weak','Fragile') then x.status else 'Unresolved wrong history' end,'{}'::jsonb,
       'bootstrap:'||p_user_id::text||':'||x.question_id||':targeted');
     if x.active_star then perform english.route_unstar_for_resolution(p_user_id,x.question_id,'Historical Targeted evidence overrides Active Starred'); perform english.recompute_question_state(p_user_id,x.question_id); end if;
     tg:=tg+case when x.genuine then 1 else 0 end;
   elsif x.active_star then
     insert into english.learning_route_state(user_id,question_id,route,origins,baseline_wrong,last_route_reason,updated_at)
     values(p_user_id,x.question_id,'starred_unresolved',v_origins,coalesce(x.wrong,0),'Historical Active Starred uncertainty',now());
     perform english.route_event(p_user_id,x.question_id,'BOOTSTRAP',null,'starred_unresolved','From Starred','Historical Active Starred uncertainty','{}'::jsonb,
       'bootstrap:'||p_user_id::text||':'||x.question_id||':starred');
     su:=su+case when x.genuine then 1 else 0 end;
   else
     insert into english.learning_route_state(user_id,question_id,route,fast_track_status,origins,baseline_wrong,entered_fast_track_at,next_fast_track_check,last_route_reason,updated_at)
     values(p_user_id,x.question_id,'fast_track','ready',v_origins,coalesce(x.wrong,0),now(),now(),'Historical clean evidence; verification required',now());
     perform english.route_event(p_user_id,x.question_id,'BOOTSTRAP',null,'fast_track',case when v_saved then 'From My Saved' else 'Historical Clean Bank' end,'Historical clean evidence; verification required','{}'::jsonb,
       'bootstrap:'||p_user_id::text||':'||x.question_id||':fast_track');
     ft:=ft+case when x.genuine then 1 else 0 end;
   end if;
   if not x.genuine then extra:=extra+1; end if;
 end loop;
 return jsonb_build_object('ok',true,'genuineEvaluated',ft+tg+su+mastered,'fastTrackCandidates',ft,'targetedCandidates',tg,'starredUnresolved',su,'alreadyMastered',mastered,'additionalSavedOrStarred',extra);
end $$;

do $$ declare u record; begin for u in select id from auth.users loop perform english.bootstrap_learning_routes(u.id); end loop; end $$;

create or replace function public.english_get_learning_route_overview()
returns jsonb language sql stable security definer
set search_path=pg_catalog,public,english,auth as $$
with uid as (select auth.uid() id), ft as (
 select r.*,(r.fast_track_status='ready' or (r.fast_track_status='waiting' and r.next_fast_track_check<=now())) ready_now
 from english.learning_route_state r cross join uid where r.user_id=uid.id and r.route='fast_track'
), origins as (
 select o,count(*)::int total,count(*) filter(where f.fast_track_status='mastered')::int mastered,
   count(*) filter(where f.fast_track_status<>'mastered')::int remaining
 from ft f cross join lateral unnest(f.origins) o group by o
), starhist as (
 select count(distinct question_id) filter(where to_route='fast_track' and origin='From Starred')::int moved_fast,
        count(distinct question_id) filter(where to_route='targeted' and origin='From Starred')::int moved_targeted
 from english.learning_route_events e cross join uid where e.user_id=uid.id
), saved as (
 select distinct si.practice_question_id question_id from english.saved_items si cross join uid where si.user_id=uid.id and si.active and nullif(btrim(si.practice_question_id),'') is not null
), savestats as (
 select count(*)::int total,
  count(*) filter(where r.route='fast_track')::int fast_track,
  count(*) filter(where r.route='fast_track' and r.fast_track_status='mastered')::int fast_mastered,
  count(*) filter(where r.route='fast_track' and r.fast_track_status<>'mastered')::int fast_remaining,
  count(*) filter(where r.route='targeted')::int targeted,
  count(*) filter(where r.route is null or r.route in ('unclassified','starred_unresolved'))::int unclassified
 from saved s left join english.learning_route_state r on r.user_id=(select id from uid) and r.question_id=s.question_id
), savedhist as (
 select count(distinct e.question_id) filter(where e.to_route='targeted')::int ever_targeted,
        count(distinct e.question_id) filter(where e.to_route='targeted' and exists(select 1 from english.learning_route_state r where r.user_id=e.user_id and r.question_id=e.question_id and r.route<>'targeted'))::int recovered
 from english.learning_route_events e join saved s on s.question_id=e.question_id cross join uid where e.user_id=uid.id
), active_star as (select count(*)::int n from english.question_state s cross join uid where s.user_id=uid.id and s.last_marked and not s.mastered)
select case when (select id from uid) is null then jsonb_build_object('ok',false,'error','Authentication required') else jsonb_build_object(
 'ok',true,
 'fastTrack',jsonb_build_object(
   'total',(select count(*) from ft),'readyToVerify',(select count(*) from ft where ready_now and fast_track_status<>'mastered'),
   'waiting',(select count(*) from ft where fast_track_status='waiting' and not ready_now),'mastered',(select count(*) from ft where fast_track_status='mastered'),
   'remaining',(select count(*) from ft where fast_track_status<>'mastered'),
   'origins',coalesce((select jsonb_agg(jsonb_build_object('origin',o,'total',total,'mastered',mastered,'remaining',remaining) order by o) from origins),'[]'::jsonb)
 ),
 'starred',jsonb_build_object('active',(select n from active_star),'movedFastTrack',sh.moved_fast,'movedTargeted',sh.moved_targeted,
   'fastTrackMastered',(select count(*) from ft where 'From Starred'=any(origins) and fast_track_status='mastered'),
   'fastTrackRemaining',(select count(*) from ft where 'From Starred'=any(origins) and fast_track_status<>'mastered')),
 'saved',jsonb_build_object('total',ss.total,'fastTrack',ss.fast_track,'fastTrackMastered',ss.fast_mastered,'fastTrackRemaining',ss.fast_remaining,
   'targeted',ss.targeted,'everTargeted',coalesce(sh2.ever_targeted,0),'recoveredStable',coalesce(sh2.recovered,0),'stillLearning',ss.targeted,'unclassified',ss.unclassified)
) end
from starhist sh cross join savestats ss cross join savedhist sh2;
$$;

create or replace function public.english_get_fast_track_batch(p_count integer default 30,p_origin text default null)
returns jsonb language sql stable security definer
set search_path=pg_catalog,public,english,auth as $$
with r as (
 select x.*,case when x.fast_track_status='ready' then 0 else 1 end wait_ord
 from english.learning_route_state x
 where x.user_id=auth.uid() and x.route='fast_track' and x.fast_track_status<>'mastered'
   and (x.fast_track_status='ready' or x.next_fast_track_check<=now())
   and (p_origin is null or p_origin=any(x.origins))
   and nullif(english.route_targeted_reason(auth.uid(),x.question_id),'') is null
 order by wait_ord,x.next_fast_track_check nulls first,x.updated_at,x.question_id
 limit greatest(1,least(100,coalesce(p_count,30)))
)
select coalesce(jsonb_agg(english.question_payload(auth.uid(),r.question_id)||jsonb_build_object(
 'fastTrack',true,'fastTrackStatus',r.fast_track_status,'fastTrackOrigins',r.origins,'fastTrackReason',r.last_route_reason,
 'fastTrackNextCheck',r.next_fast_track_check,'fastTrackFailureDecision',r.pending_failure_decision
) order by r.wait_ord,r.next_fast_track_check nulls first,r.question_id),'[]'::jsonb) from r;
$$;

create or replace function public.english_get_fast_track_items(p_origin text default null,p_status text default 'all',p_limit integer default 100,p_offset integer default 0)
returns jsonb language sql stable security definer
set search_path=pg_catalog,public,english,auth as $$
with r as (
 select x.* from english.learning_route_state x where x.user_id=auth.uid() and x.route='fast_track'
  and (p_origin is null or p_origin=any(x.origins))
  and (lower(coalesce(p_status,'all'))='all' or (lower(p_status)='mastered' and x.fast_track_status='mastered') or (lower(p_status)='remaining' and x.fast_track_status<>'mastered'))
 order by case x.fast_track_status when 'ready' then 1 when 'waiting' then 2 else 3 end,x.updated_at desc,x.question_id
 limit greatest(1,least(250,coalesce(p_limit,100))) offset greatest(0,coalesce(p_offset,0))
)
select coalesce(jsonb_agg(english.question_payload(auth.uid(),r.question_id)||jsonb_build_object(
 'fastTrackStatus',r.fast_track_status,'fastTrackOrigins',r.origins,'fastTrackReason',r.last_route_reason,'fastTrackEnteredAt',r.entered_fast_track_at,
 'fastTrackNextCheck',r.next_fast_track_check,'fastTrackMasteredAt',r.fast_track_mastered_at,'routeHistory',coalesce((select jsonb_agg(jsonb_build_object('at',e.event_at,'type',e.event_type,'from',e.from_route,'to',e.to_route,'origin',e.origin,'reason',e.reason) order by e.event_at) from english.learning_route_events e where e.user_id=r.user_id and e.question_id=r.question_id),'[]'::jsonb)
) order by case r.fast_track_status when 'ready' then 1 when 'waiting' then 2 else 3 end,r.updated_at desc),'[]'::jsonb) from r;
$$;

create or replace function public.english_set_fast_track(p_question_id text,p_fast_track boolean default true)
returns jsonb language plpgsql security definer
set search_path=pg_catalog,public,english,auth as $$
declare uid uuid:=auth.uid(); r english.learning_route_state%rowtype; reason text;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 if not exists(select 1 from english.questions q where q.question_id=btrim(p_question_id) and q.active) then raise exception 'Question not found'; end if;
 if coalesce(p_fast_track,true) then
   reason:=english.route_targeted_reason(uid,btrim(p_question_id));
   if nullif(reason,'') is not null then return jsonb_build_object('ok',false,'reason',reason,'route','targeted'); end if;
   return english.route_to_fast_track(uid,btrim(p_question_id),'Manual Fast Track','Learner requested cheap verification',false);
 end if;
 select * into r from english.learning_route_state where user_id=uid and question_id=btrim(p_question_id);
 if found and r.route='fast_track' then
   update english.learning_route_state set route='unclassified',fast_track_status=null,next_fast_track_check=null,pending_failure_decision=false,last_route_reason='Removed from Fast Track',updated_at=now() where user_id=uid and question_id=btrim(p_question_id);
   perform english.route_event(uid,btrim(p_question_id),'UNROUTE','fast_track','unclassified','Manual Fast Track','Learner removed Fast Track','{}'::jsonb,null);
 end if;
 return jsonb_build_object('ok',true,'route','unclassified');
end $$;

create or replace function public.english_resolve_fast_track_failure(p_question_id text,p_add_targeted boolean)
returns jsonb language plpgsql security definer
set search_path=pg_catalog,public,english,auth as $$
declare uid uuid:=auth.uid(); r english.learning_route_state%rowtype;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 select * into r from english.learning_route_state where user_id=uid and question_id=btrim(p_question_id) and route='fast_track';
 if not found or not r.pending_failure_decision then return jsonb_build_object('ok',false,'reason','no-pending-fast-track-failure'); end if;
 if coalesce(p_add_targeted,false) then return english.route_to_targeted(uid,btrim(p_question_id),'Fast Track Failure','Learner approved Targeted Mastery after Fast Track miss'); end if;
 if r.kept_failure_count>=1 then return english.route_to_targeted(uid,btrim(p_question_id),'Fast Track Failure','Repeated Fast Track miss requires Targeted Mastery'); end if;
 update english.learning_route_state set pending_failure_decision=false,kept_failure_count=kept_failure_count+1,fast_track_status='ready',next_fast_track_check=now()+interval '1 day',last_route_reason='One Fast Track miss kept for confirmation',updated_at=now() where user_id=uid and question_id=btrim(p_question_id);
 perform english.route_event(uid,btrim(p_question_id),'KEEP','fast_track','fast_track','Fast Track Failure','Learner kept one-off miss in Fast Track; confirmation required','{}'::jsonb,null);
 return jsonb_build_object('ok',true,'route','fast_track','status','ready','confirmationRequired',true);
end $$;

create or replace function english.daily_reason(p_user_id uuid,p_question_id text,p_batch_date date)
returns text language sql stable security definer
set search_path=pg_catalog,english,auth as $$
with x as (
 select q,coalesce(s.attempts,0) attempts,coalesce(s.status,'New') state,s.next_review,coalesce(s.mastered,false) mastered,
        coalesce(s.last_marked,false) starred,coalesce(d.difficult,false) difficult,
        exists(select 1 from english.learning_route_state r where r.user_id=p_user_id and r.question_id=q.question_id and r.route='fast_track') fast_track
 from english.questions q
 left join english.question_state s on s.user_id=p_user_id and s.question_id=q.question_id
 left join english.difficult_state d on d.user_id=p_user_id and d.question_id=q.question_id
 where q.question_id=p_question_id
)
select case
 when not (q).active or mastered or fast_track then ''
 when attempts=0 and english.is_genuine_bank_question(q) then 'Controlled New'
 when next_review is null or next_review>((p_batch_date::timestamp+interval '1 day - 1 millisecond') at time zone 'Asia/Kolkata') then ''
 when state='Persistent Weak' then 'Persistent Weak'
 when state='Weak' then 'Weak'
 when state='Fragile' then 'Fragile'
 when difficult then 'Difficult Review'
 when starred then 'Marked Review'
 when state='Learning' then 'Learning'
 else 'Due Spaced Revision' end from x;
$$;

create or replace function public.english_get_revision_hub()
returns jsonb language sql stable security definer
set search_path=pg_catalog,public,english,auth as $$
with c as (
 select q.question_id,coalesce(s.status,'New') status,coalesce(s.attempts,0) attempts,coalesce(s.mastered,false) mastered,
   coalesce(d.difficult,false) difficult,coalesce(s.last_marked,false) starred,s.last_attempt,s.next_review,
   (s.next_review is not null and s.next_review<=(((now() at time zone 'Asia/Kolkata')::date+1)::timestamp at time zone 'Asia/Kolkata')) due
 from english.questions q
 left join english.question_state s on s.user_id=auth.uid() and s.question_id=q.question_id
 left join english.difficult_state d on d.user_id=auth.uid() and d.question_id=q.question_id
 where auth.uid() is not null and q.active and english.question_visible_to_user(auth.uid(),q.question_id)
   and not exists(select 1 from english.learning_route_state r where r.user_id=auth.uid() and r.question_id=q.question_id and r.route='fast_track')
)
select jsonb_build_object(
 'due',count(*) filter(where not mastered and attempts>0 and due),'weak',count(*) filter(where not mastered and status in ('Persistent Weak','Weak','Fragile')),
 'persistentWeak',count(*) filter(where not mastered and status='Persistent Weak'),'difficult',count(*) filter(where not mastered and difficult),
 'starred',count(*) filter(where not mastered and starred),'seenBefore',count(*) filter(where not mastered and attempts>0),
 'mastered',count(*) filter(where mastered),'learning',count(*) filter(where not mastered and status in ('Learning','New'))
) from c;
$$;

create or replace function public.english_get_revision_batch(p_mode text default 'smart',p_count integer default 30)
returns jsonb language plpgsql stable security definer
set search_path=pg_catalog,public,english,auth as $$
declare uid uuid:=auth.uid();m text:=lower(btrim(coalesce(p_mode,'smart')));n integer:=greatest(1,least(100,coalesce(p_count,30)));out jsonb;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 if m not in ('smart','due','weak','recall','difficult','random') then raise exception 'Unknown revision mode: %',p_mode; end if;
 with base as (
  select q.question_id,coalesce(s.status,'New') status,coalesce(s.attempts,0) attempts,coalesce(s.wrong,0) wrong,
    coalesce(d.difficult,false) difficult,coalesce(s.last_marked,false) starred,s.last_attempt,s.next_review,
    (s.next_review is not null and s.next_review<=(((now() at time zone 'Asia/Kolkata')::date+1)::timestamp at time zone 'Asia/Kolkata')) due
  from english.questions q
  left join english.question_state s on s.user_id=uid and s.question_id=q.question_id
  left join english.difficult_state d on d.user_id=uid and d.question_id=q.question_id
  where q.active and not coalesce(s.mastered,false)
    and not exists(select 1 from english.learning_route_state r where r.user_id=uid and r.question_id=q.question_id and r.route='fast_track')
 ), filtered as (
  select * from base where
    (m='smart' and attempts>0 and (due or status in ('Persistent Weak','Weak','Fragile') or difficult)) or
    (m='due' and attempts>0 and due) or (m='weak' and status in ('Persistent Weak','Weak','Fragile')) or
    (m='recall' and attempts>0) or (m='difficult' and difficult) or m='random'
 ), ranked as (
  select *,row_number() over(order by case when m='random' then random() else 0 end,
    case when status='Persistent Weak' and due then 10 when status='Persistent Weak' then 9 when status='Weak' and due then 8 when status='Weak' then 7
         when status='Fragile' and due then 6 when due then 5 when status='Fragile' then 4 when difficult then 3 when status='Learning' then 2 else 1 end desc,
    difficult desc,wrong desc,coalesce(next_review,'infinity'::timestamptz),coalesce(last_attempt,'epoch'::timestamptz),question_id)::int ord
  from filtered
 ), chosen as (select * from ranked order by ord limit n)
 select coalesce(jsonb_agg(english.question_payload(uid,c.question_id)||jsonb_build_object(
   'centralRevisionMode',m,'centralRevisionSignals',english.central_revision_signals(c.status,c.due,c.difficult,c.starred,c.wrong,c.next_review),
   'centralRevisionReason',case when c.status='Persistent Weak' then 'Persistent Weak' when c.status='Weak' then 'Weak' when c.status='Fragile' then 'Fragile'
     when c.due then 'Due Spaced Revision' when c.difficult then 'Difficult' else 'Recall Rotation' end) order by c.ord),'[]'::jsonb) into out from chosen c;
 return out;
end $$;

revoke execute on function public.english_get_learning_route_overview() from public,anon;
revoke execute on function public.english_get_fast_track_batch(integer,text) from public,anon;
revoke execute on function public.english_get_fast_track_items(text,text,integer,integer) from public,anon;
revoke execute on function public.english_set_fast_track(text,boolean) from public,anon;
revoke execute on function public.english_resolve_fast_track_failure(text,boolean) from public,anon;
grant execute on function public.english_get_learning_route_overview() to authenticated,service_role;
grant execute on function public.english_get_fast_track_batch(integer,text) to authenticated,service_role;
grant execute on function public.english_get_fast_track_items(text,text,integer,integer) to authenticated,service_role;
grant execute on function public.english_set_fast_track(text,boolean) to authenticated,service_role;
grant execute on function public.english_resolve_fast_track_failure(text,boolean) to authenticated,service_role;
grant execute on function public.english_get_revision_hub() to authenticated,service_role;
grant execute on function public.english_get_revision_batch(text,integer) to authenticated,service_role;
