-- GK V2 read/write surface.  Browser clients use these SECURITY DEFINER
-- functions; the underlying gk schema remains private and RLS-protected.
alter table gk.questions add column if not exists content_lane text;
update gk.questions set content_lane = case when upper(coalesce(content_lane,'')) in ('RAPID','RAPID RECALL') then 'RAPID' else 'MAIN' end where content_lane is null;
alter table gk.questions alter column content_lane set default 'MAIN';
alter table gk.questions alter column content_lane set not null;
create index if not exists gk_questions_lane_idx on gk.questions(content_lane,active,question_id);

create or replace function public.gk_get_lane_batch(p_lane text, p_mode text default 'all', p_count integer default 20)
returns jsonb language plpgsql security definer set search_path=public,gk,pg_temp as $$
declare uid uuid:=auth.uid(); lane text:=upper(btrim(coalesce(p_lane,''))); mode_name text:=lower(btrim(coalesce(p_mode,'all'))); n integer:=greatest(1,least(100,coalesce(p_count,20)));
begin
 if uid is null then raise exception 'authentication required'; end if;
 if lane not in ('MAIN','RAPID') then raise exception 'invalid GK lane'; end if;
 return coalesce((select jsonb_agg(to_jsonb(x) order by x.question_id) from (
   select q.question_id id,q.question_id,q.question,q.option_a,q.option_b,q.option_c,q.option_d,q.correct_option "correctKey",q.content_lane,q.subject,q.topic,q.lecture_no,q.explanation,q.trick,q.related_fact,q.exam_trap,q.concept_id,q.source_label,q.difficulty,
     jsonb_build_array(jsonb_build_object('key','A','text',q.option_a),jsonb_build_object('key','B','text',q.option_b),jsonb_build_object('key','C','text',q.option_c),jsonb_build_object('key','D','text',q.option_d)) options from gk.questions q where q.active and q.content_lane=lane
     order by case when mode_name='unseen' and not exists(select 1 from gk.exposures e where e.user_id=uid and e.question_id=q.question_id) then 0 else 1 end,q.question_id limit n
 ) x), '[]'::jsonb);
end $$;

create or replace function public.gk_get_lecture_batch(p_lecture_key text,p_lane text,p_mode text default 'all',p_count integer default 20) returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$
 select public.gk_get_lane_batch(p_lane,p_mode,p_count); $$;
create or replace function public.gk_get_subject_batch(p_subject text,p_topic text default null,p_lane text default 'MAIN',p_mode text default 'all',p_count integer default 20) returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$
 select coalesce((select jsonb_agg(to_jsonb(q) order by q.question_id) from (select q.question_id id,q.question_id,q.question,q.option_a,q.option_b,q.option_c,q.option_d,q.correct_option "correctKey",q.content_lane,q.subject,q.topic,q.lecture_no,q.explanation,q.trick,q.related_fact,q.exam_trap,q.concept_id,q.source_label,q.difficulty from gk.questions q where q.active and q.content_lane=upper(p_lane) and q.subject=p_subject and (p_topic is null or q.topic=p_topic) order by q.question_id limit greatest(1,least(100,p_count))) q),'[]'::jsonb); $$;
create or replace function public.gk_get_home_snapshot() returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$
 select jsonb_build_object('ok',true,'summary',jsonb_build_object('total',(select count(*) from gk.questions),'eligibleTotal',(select count(*) from gk.questions where active),'main',(select count(*) from gk.questions where content_lane='MAIN'),'rapidRecall',(select count(*) from gk.questions where content_lane='RAPID'),'eligibleMain',(select count(*) from gk.questions where active and content_lane='MAIN'),'eligibleRapidRecall',(select count(*) from gk.questions where active and content_lane='RAPID'),'exposed',(select count(distinct question_id) from gk.exposures where user_id=auth.uid()),'eligibleExposed',(select count(distinct e.question_id) from gk.exposures e join gk.questions q using(question_id) where e.user_id=auth.uid() and q.active),'starred',(select count(*) from gk.question_state where user_id=auth.uid() and starred_at is not null),'difficult',(select count(*) from gk.question_state where user_id=auth.uid() and difficult),'weak',(select count(*) from gk.question_state where user_id=auth.uid() and learning_status in ('Weak','Fragile')),'guessed',(select count(*) from gk.question_state where user_id=auth.uid() and unconfirmed_guess),'due',(select count(*) from gk.question_state where user_id=auth.uid() and next_review<=now()))); $$;

create or replace function public.gk_submit_answer(p_question_id text,p_selected_option text,p_marked_review boolean default false,p_mode text default '',p_attempt_id text default null) returns jsonb language plpgsql security definer set search_path=public,gk,pg_temp as $$
declare uid uuid:=auth.uid(); q gk.questions%rowtype; aid text:=coalesce(nullif(p_attempt_id,''),gen_random_uuid()::text); ok boolean;
begin if uid is null then raise exception 'authentication required'; end if; select * into q from gk.questions where question_id=p_question_id; if not found then raise exception 'question not found'; end if; ok=upper(p_selected_option)=upper(q.correct_option); insert into gk.attempts(attempt_id,user_id,attempted_at,question_id,selected_option,is_correct,marked_review,mode,submission_key) values(aid,uid,now(),q.question_id,upper(p_selected_option),ok,p_marked_review,p_mode,aid) on conflict (submission_key) do nothing; insert into gk.question_state(user_id,question_id,attempts,correct,wrong,last_attempt,last_selected,last_correct,marked_review,exposure_count,first_seen,last_seen) values(uid,q.question_id,1,case when ok then 1 else 0 end,case when ok then 0 else 1 end,now(),upper(p_selected_option),ok,p_marked_review,1,now(),now()) on conflict(user_id,question_id) do update set attempts=gk.question_state.attempts+1,correct=gk.question_state.correct+case when ok then 1 else 0 end,wrong=gk.question_state.wrong+case when ok then 0 else 1 end,last_attempt=now(),last_selected=upper(p_selected_option),last_correct=ok,marked_review=p_marked_review,last_seen=now(); return jsonb_build_object('ok',true,'attempt_id',aid,'correct',ok); end $$;

create or replace function public.gk_set_starred(p_question_id text,p_starred boolean) returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$ update gk.question_state set starred_at=case when p_starred then now() else null end where user_id=auth.uid() and question_id=p_question_id; select jsonb_build_object('ok',true,'starred',p_starred); $$;
create or replace function public.gk_set_difficult(p_question_id text,p_difficult boolean) returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$ insert into gk.question_state(user_id,question_id,difficult) values(auth.uid(),p_question_id,p_difficult) on conflict(user_id,question_id) do update set difficult=excluded.difficult; select jsonb_build_object('ok',true,'difficult',p_difficult); $$;
create or replace function public.gk_set_flag(p_question_id text,p_active boolean,p_reason text default '',p_note text default '') returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$ insert into gk.question_state(user_id,question_id,flag_active,flag_reason,flag_note,flag_updated_at) values(auth.uid(),p_question_id,p_active,p_reason,p_note,now()) on conflict(user_id,question_id) do update set flag_active=excluded.flag_active,flag_reason=excluded.flag_reason,flag_note=excluded.flag_note,flag_updated_at=now(); select jsonb_build_object('ok',true,'flagged',p_active); $$;
create or replace function public.gk_save_note(p_question_id text,p_note text) returns jsonb language sql security definer set search_path=public,gk,pg_temp as $$ insert into gk.user_notes(user_id,question_id,note,updated_at) values(auth.uid(),p_question_id,p_note,now()) on conflict(user_id,question_id) do update set note=excluded.note,updated_at=now(); select jsonb_build_object('ok',true); $$;

grant execute on function public.gk_get_lane_batch(text,text,integer),public.gk_get_lecture_batch(text,text,text,integer),public.gk_get_subject_batch(text,text,text,text,integer),public.gk_get_home_snapshot(),public.gk_submit_answer(text,text,boolean,text,text),public.gk_set_starred(text,boolean),public.gk_set_difficult(text,boolean),public.gk_set_flag(text,boolean,text,text),public.gk_save_note(text,text) to authenticated;
