create or replace function public.english_get_starred_hub(p_from_day integer default null,p_to_day integer default null)
returns jsonb language sql stable security definer set search_path=pg_catalog,public,english,auth as $$
with allc as (select * from english.starred_revision_candidates(auth.uid())),
c as (select * from allc where (p_from_day is null or origin_day>=p_from_day) and (p_to_day is null or origin_day<=p_to_day)),
s as (select count(*)::int active,count(*) filter(where revised_count>0)::int revised,count(*) filter(where never_revised)::int never_revised,count(*) filter(where revised_count=1)::int revised_once,count(*) filter(where revised_count>=2)::int revised_multiple,count(*) filter(where revised_count>0 and coalesce(days_since_revision,0)>=14)::int long_overdue,count(*) filter(where due)::int due,count(*) filter(where state in ('Persistent Weak','Weak','Fragile'))::int weak,count(*) filter(where state='Persistent Weak')::int persistent_weak,count(*) filter(where state='Fragile')::int fragile,count(*) filter(where difficult)::int difficult,count(*) filter(where state='Strong')::int strong,count(*) filter(where state in ('Learning','New'))::int learning from c),
days as (select origin_day,count(*)::int count from allc group by origin_day order by origin_day desc),
cur as (select coalesce((select max(day_no) from english.daily_history where user_id=auth.uid()),(select max(origin_day) from allc),1)::int current_day)
select jsonb_build_object('version','V1','currentDay',cur.current_day,'stats',jsonb_build_object('active',s.active,'revised',s.revised,'neverRevised',s.never_revised,'revisedOnce',s.revised_once,'revisedMultiple',s.revised_multiple,'longOverdue',s.long_overdue,'due',s.due,'weak',s.weak,'persistentWeak',s.persistent_weak,'fragile',s.fragile,'difficult',s.difficult,'strong',s.strong,'learning',s.learning),'available',jsonb_build_object('smart',s.active,'notRevised',s.never_revised,'due',s.due,'weak',s.weak,'difficult',s.difficult,'longest',s.active,'all',s.active),'sizes',jsonb_build_array(10,20,30,50),'history',coalesce((select jsonb_agg(jsonb_build_object('day',origin_day,'label','Day '||origin_day,'count',count) order by origin_day desc) from days),'[]'::jsonb)) from s cross join cur;
$$;
