-- Lossless Maths source migration foundation.
create table if not exists maths.migration_runs (migration_run_id text primary key, source_workbook_id text not null, source_workbook_title text not null, source_role text not null check (source_role in ('current_primary','pre_cleanup_archive')), source_modified_at timestamptz, source_snapshot_at timestamptz not null default now(), source_schema jsonb not null default '{}'::jsonb, importer_version text not null, notes text);
create table if not exists maths.raw_source_rows (migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict, source_sheet text not null, source_row_number integer not null check (source_row_number > 0), source_row jsonb not null, source_row_hash text not null, primary key (migration_run_id, source_sheet, source_row_number));
create index if not exists maths_raw_source_rows_hash_idx on maths.raw_source_rows(source_row_hash);
create table if not exists maths.question_bank_memberships (question_id text not null references maths.questions(question_id) on delete cascade, bank_key text not null, source_bank_value text, source_rule text not null, source_order integer, migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict, primary key (question_id, bank_key));
create table if not exists maths.diagram_assets (question_id text primary key references maths.questions(question_id) on delete cascade, has_diagram boolean not null default false, diagram_type text, original_source_reference text, migrated_asset_reference text, width numeric, height numeric, aspect_ratio numeric, alt_description text, geometry_metadata jsonb, raw_diagram_payload jsonb, migration_status text not null check (migration_status in ('not_applicable','preserved_inline','preserved_reference','unresolved')), provenance jsonb not null default '{}'::jsonb, migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict);
create index if not exists maths_diagram_assets_status_idx on maths.diagram_assets(migration_status);
create table if not exists maths.chapter_plan (source_order integer not null, chapter text not null, target_per_day numeric, status text, introduced text, mastered text, source_row jsonb not null, migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict, primary key (migration_run_id, source_order, chapter));
create table if not exists maths.user_notes (user_id uuid not null references auth.users(id) on delete cascade, question_id text not null references maths.questions(question_id) on delete cascade, note text not null, updated_at timestamptz, pinned boolean not null default false, source_row jsonb not null, migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict, primary key (user_id, question_id));
create table if not exists maths.progress_snapshots (migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict, source_row_number integer not null, source_row jsonb not null, generated_at timestamptz, primary key (migration_run_id, source_row_number));
create table if not exists maths.migration_reconciliation (migration_run_id text not null references maths.migration_runs(migration_run_id) on delete restrict, source_entity text not null, source_count integer not null, target_entity text not null, target_count integer not null, difference integer not null, status text not null check (status in ('pass','warning','fail')), checked_at timestamptz not null default now(), notes text, primary key (migration_run_id, source_entity, target_entity));
alter table maths.migration_runs enable row level security; alter table maths.raw_source_rows enable row level security; alter table maths.question_bank_memberships enable row level security; alter table maths.diagram_assets enable row level security; alter table maths.chapter_plan enable row level security; alter table maths.user_notes enable row level security; alter table maths.progress_snapshots enable row level security; alter table maths.migration_reconciliation enable row level security;
revoke all on maths.migration_runs, maths.raw_source_rows, maths.chapter_plan, maths.progress_snapshots, maths.migration_reconciliation from anon, authenticated;
grant select on maths.question_bank_memberships, maths.diagram_assets to authenticated; grant select, insert, update, delete on maths.user_notes to authenticated;
drop policy if exists maths_question_bank_memberships_authenticated_read on maths.question_bank_memberships; create policy maths_question_bank_memberships_authenticated_read on maths.question_bank_memberships for select to authenticated using (true);
drop policy if exists maths_diagram_assets_authenticated_read on maths.diagram_assets; create policy maths_diagram_assets_authenticated_read on maths.diagram_assets for select to authenticated using (true);
drop policy if exists maths_user_notes_own on maths.user_notes; create policy maths_user_notes_own on maths.user_notes for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);


