-- Harden timer resume, optimistic attempt identity, external staging, and weekly coaching.

create or replace function maths._start_session(p_uid uuid,p_ids text[],p_mode text,p_title text,p_params jsonb default '{}'::jsonb,p_force_memory_reveal boolean default false)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public','maths' as $$
declare sid text:=gen_random_uuid()::text;rendered jsonb;i int:=0;qid text;params_ jsonb:=coalesce(p_params,'{}'::jsonb)||jsonb_build_object('startedAt',now()::text);duration_ int;
begin
if coalesce(array_length(p_ids,1),0)=0 then return jsonb_build_object('ok',false,'message','No eligible questions found.');end if;
duration_:=greatest(0,coalesce(nullif(params_->>'durationSec','')::int,0));if duration_>0 then params_:=params_||jsonb_build_object('deadlineAt',(now()+make_interval(secs=>duration_))::text);end if;
rendered:=maths._render_questions(p_uid,p_ids,p_force_memory_reveal);insert into maths.sessions(session_id,user_id,mode,title,current_index,updated_at,completed,params,rendered_questions,created_at)values(sid,p_uid,p_mode,p_title,0,now(),false,params_,rendered,now());foreach qid in array p_ids loop insert into maths.session_questions(session_id,question_id,position)values(sid,qid,i);i:=i+1;end loop;return maths._get_session(p_uid,sid);end$$;

create or replace function maths._preview_session(p_uid uuid,p_ids text[],p_mode text,p_title text,p_params jsonb default '{}'::jsonb,p_force_memory_reveal boolean default false)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public','maths' as $$
declare sid text:='local-'||md5(p_uid::text||clock_timestamp()::text||coalesce(array_to_string(p_ids,','),''));params_ jsonb:=coalesce(p_params,'{}'::jsonb)||jsonb_build_object('startedAt',now()::text);duration_ int;
begin
if coalesce(array_length(p_ids,1),0)=0 then return jsonb_build_object('ok',false,'message','No eligible questions found.','localSafe',true);end if;duration_:=greatest(0,coalesce(nullif(params_->>'durationSec','')::int,0));if duration_>0 then params_:=params_||jsonb_build_object('deadlineAt',(now()+make_interval(secs=>duration_))::text);end if;return jsonb_build_object('ok',true,'localSafe',true,'sessionId',sid,'mode',p_mode,'title',p_title,'currentIndex',0,'completed',false,'target',array_length(p_ids,1),'params',params_,'questions',maths._render_questions(p_uid,p_ids,p_force_memory_reveal),'attempts','{}'::jsonb,'flags','{}'::jsonb);end$$;

create or replace function public.maths_confirm_diagnosis(p_attempt_id text,p_reason text,p_confidence_response text default null)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public','maths' as $$
declare uid uuid:=maths._require_uid();e maths.performance_evidence%rowtype;reason_ text:=upper(nullif(btrim(p_reason),''));confidence_ text:=lower(nullif(btrim(p_confidence_response),''));
begin
if reason_ not in('CAL','APP','CON','FOR','SILLY','TIME')then raise exception 'Invalid Maths diagnosis';end if;if confidence_ is not null and confidence_ not in('sure','50_50','guess')then raise exception 'Invalid confidence response';end if;
select pe.* into e from maths.performance_evidence pe left join maths.attempts a on a.attempt_id=pe.attempt_id and a.user_id=uid where pe.user_id=uid and(pe.attempt_id=p_attempt_id or a.client_attempt_key=p_attempt_id)order by pe.created_at desc limit 1;if not found then raise exception 'Attempt evidence not found';end if;
update maths.performance_evidence set user_confirmed_reason=reason_,confidence_response=coalesce(confidence_,confidence_response),updated_at=now()where evidence_id=e.evidence_id returning * into e;update maths.repair_queue set status='dismissed',updated_at=now()where user_id=uid and source_evidence_id=e.evidence_id and status in('open','in_progress','waiting_confirmation');perform maths._sync_repair_from_evidence(e.evidence_id);return jsonb_build_object('ok',true,'attemptId',p_attempt_id,'reason',e.final_reason,'confidence',e.confidence_response);end$$;

create or replace function public.maths_record_confidence(p_attempt_id text,p_confidence_response text)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public','maths' as $$
declare uid uuid:=maths._require_uid();c text:=lower(nullif(btrim(p_confidence_response),''));eid uuid;
begin
if c not in('sure','50_50','guess')then raise exception 'Invalid confidence response';end if;select pe.evidence_id into eid from maths.performance_evidence pe left join maths.attempts a on a.attempt_id=pe.attempt_id and a.user_id=uid where pe.user_id=uid and(pe.attempt_id=p_attempt_id or a.client_attempt_key=p_attempt_id)order by pe.created_at desc limit 1;if eid is null then raise exception 'Attempt evidence not found';end if;update maths.performance_evidence set confidence_response=c,updated_at=now()where evidence_id=eid;perform maths._sync_repair_from_evidence(eid);return jsonb_build_object('ok',true,'attemptId',p_attempt_id,'confidence',c);end$$;

create or replace function public.maths_stage_external_mock(p_payload jsonb,p_source_label text default null,p_source_ref text default null)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public','maths' as $$
declare uid uuid:=maths._require_uid();prompt_ text;norm_ text;match_ text;matches_ int;sid uuid;e_id uuid;result_ text;response_ numeric;reason_ text;user_reason_ text;concept_ text;family_ text;
begin
prompt_:=coalesce(nullif(btrim(p_payload->>'prompt'),''),nullif(btrim(p_payload->>'question'),''));if prompt_ is null then raise exception 'External mock payload requires prompt/question text';end if;norm_:=lower(regexp_replace(regexp_replace(prompt_,'\s+',' ','g'),'[^a-zA-Z0-9%./:+*?() -]','','g'));select count(*),min(question_id)into matches_,match_ from maths.runtime_questions where runtime_active and lower(regexp_replace(regexp_replace(prompt,'\s+',' ','g'),'[^a-zA-Z0-9%./:+*?() -]','','g'))=norm_;
insert into maths.external_mock_staging(user_id,source_label,source_ref,extracted_payload,normalized_prompt,matched_question_id,match_confidence,match_method,review_status)values(uid,p_source_label,p_source_ref,p_payload,norm_,case when matches_=1 then match_ end,case when matches_=1 then 1 end,case when matches_=1 then'normalized_exact_prompt'end,case when matches_=1 then'matched'else'needs_review'end)returning stage_id into sid;
if matches_=1 and lower(coalesce(p_payload->>'result',''))in('correct','wrong','seen')then result_:=lower(p_payload->>'result');response_:=greatest(0,least(coalesce(nullif(p_payload->>'responseSec','')::numeric,0),86400));reason_:=upper(nullif(p_payload->>'inferredReason',''));user_reason_:=upper(nullif(p_payload->>'userReason',''));if reason_ not in('CAL','APP','CON','FOR','SILLY','TIME')then reason_:=null;end if;if user_reason_ not in('CAL','APP','CON','FOR','SILLY','TIME')then user_reason_:=null;end if;insert into maths.performance_evidence(user_id,question_id,session_id,evidence_source,inferred_reason,user_confirmed_reason,inference_confidence,correctness,response_sec,baseline_sec,timing_class,slow_correct,confidence_response,metadata)values(uid,match_,null,'external_mock',reason_,user_reason_,case when reason_ is null then null else .65 end,result_,response_,maths._baseline_sec(uid,match_,now()),maths._timing_class(result_,response_,maths._baseline_sec(uid,match_,now())),maths._timing_class(result_,response_,maths._baseline_sec(uid,match_,now()))='correct_slow',case when lower(coalesce(p_payload->>'confidence',''))in('sure','50_50','guess')then lower(p_payload->>'confidence')end,jsonb_build_object('stageId',sid,'sourceLabel',p_source_label,'sourceRef',p_source_ref))returning evidence_id into e_id;select concept_id into concept_ from maths.question_concepts where question_id=match_ and active order by confidence desc limit 1;if concept_ is not null then perform maths._refresh_concept_state(uid,concept_);end if;select family_id into family_ from maths.question_families where question_id=match_ and active limit 1;if family_ is not null then perform maths._refresh_family_state(uid,family_);end if;perform maths._sync_repair_from_evidence(e_id);end if;return jsonb_build_object('ok',true,'stageId',sid,'status',case when matches_=1 then'matched'else'needs_review'end,'matchedQuestionId',case when matches_=1 then match_ end,'matchConfidence',case when matches_=1 then 1 end);end$$;

create or replace function public.maths_get_weekly_leakage()returns jsonb language plpgsql stable security definer set search_path='pg_catalog','public','maths' as $$
declare uid uuid:=maths._require_uid();current_ jsonb;previous_ jsonb;priorities_ jsonb;current_median numeric;previous_median numeric;
begin
with reasons as(select r,count(*)filter(where created_at>=now()-interval '7 days')current_n,count(*)filter(where created_at<now()-interval '7 days' and created_at>=now()-interval '14 days')previous_n from maths.performance_evidence e cross join lateral(select coalesce(e.final_reason,case when e.slow_correct then'TIME'end)r)x where e.user_id=uid and e.created_at>=now()-interval '14 days' and(e.correctness='wrong' or e.slow_correct)and r is not null group by r)select coalesce(jsonb_object_agg(r,current_n),'{}'::jsonb),coalesce(jsonb_object_agg(r,previous_n),'{}'::jsonb)into current_,previous_ from reasons;
select percentile_cont(.5)within group(order by maths._session_score(uid,s.session_id))into current_median from maths.sessions s where s.user_id=uid and lower(coalesce(s.mode,''))='section_sprint' and s.completed and s.updated_at>=now()-interval '7 days';select percentile_cont(.5)within group(order by maths._session_score(uid,s.session_id))into previous_median from maths.sessions s where s.user_id=uid and lower(coalesce(s.mode,''))='section_sprint' and s.completed and s.updated_at<now()-interval '7 days' and s.updated_at>=now()-interval '14 days';
select coalesce(jsonb_agg(jsonb_build_object('reason',reason,'count',n,'action',case reason when'APP'then'Approach recognition'when'CAL'then'Calculation automaticity'when'TIME'then'Timed method selection'when'FOR'then'Formula active recall'when'CON'then'Concept repair'when'SILLY'then'Trap control'end)order by n desc,reason),'[]'::jsonb)into priorities_ from(select key reason,(value::text)::int n from jsonb_each(current_)order by n desc,key limit 3)p;return jsonb_build_object('ok',true,'current7d',current_,'previous7d',previous_,'sprintMedian',jsonb_build_object('current',current_median,'previous',previous_median),'priorities',priorities_);end$$;

revoke all on function maths._start_session(uuid,text[],text,text,jsonb,boolean)from public,anon,authenticated;revoke all on function maths._preview_session(uuid,text[],text,text,jsonb,boolean)from public,anon,authenticated;revoke all on function public.maths_confirm_diagnosis(text,text,text)from public,anon;grant execute on function public.maths_confirm_diagnosis(text,text,text)to authenticated;revoke all on function public.maths_record_confidence(text,text)from public,anon;grant execute on function public.maths_record_confidence(text,text)to authenticated;revoke all on function public.maths_stage_external_mock(jsonb,text,text)from public,anon;grant execute on function public.maths_stage_external_mock(jsonb,text,text)to authenticated;revoke all on function public.maths_get_weekly_leakage()from public,anon;grant execute on function public.maths_get_weekly_leakage()to authenticated;
