"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { gkRpc, isGkLocalSafe, subscribeGkFresh } from "@/lib/gk-rpc";
import { useAuthGuard } from "@/lib/use-auth";
import type { GkQuestion } from "@/lib/gk-types";
import QuestionText from "../question-text";

type PlanAction={key:string;title:string;count:number;mode:string;lane:string};
type Plan={ok:boolean;phase:"EARLY"|"MIDDLE"|"FINAL";counts:{total:number;exposed:number;weak:number;due:number;guessed:number;unseen_teacher:number;current_affairs:number};actions:PlanAction[]};
type Answer={selected:string;correct:boolean;responseMs:number};
type Result={total?:number;attempted?:number;score:number;maxScore:number;correct:number;wrong:number;unattempted:number;accuracy:number;averageTimeMs:number;marksLostWrong?:number;marksLostUnattempted?:number};
type SprintSource="EXAM_MIXED"|"TEACHER_PYQ";
type SprintSession={ok:boolean;sessionId:string;durationSeconds:number;startedAt:string;questions:GkQuestion[];answers?:Record<string,Answer>;completed?:boolean;result?:Result;sourceKind?:SprintSource;actualCount?:number;analysisReady?:boolean};
type SavedSprint={version:2;sessionId:string;paused:boolean;pausedAt:number;pausedTotalMs:number};
type SubjectLoss={subject:string;total:number;attempted:number;correct:number;wrong:number;unattempted:number;accuracy:number;marksLost:number;conceptsNeedingRepair:number};
type Repair={conceptKey:string;conceptId?:string;subject:string;topic:string;questionIds:string[];wrong:number;unattempted:number;slow:number;fastWrong:number;existingState:string;retentionAttempts:number;retentionCorrect:number;teacherPyq:boolean;priorityScore:number;reason:string};
type SprintAnalysis={ok:boolean;sessionId:string;sourceKind:SprintSource;analysisReady:boolean;generatedAt?:string;result:Result;marksLost:{wrong:number;unattempted:number};subjects:SubjectLoss[];repairs:Repair[];questionIssues:Array<{questionId:string;subject:string;topic:string;conceptId?:string;classification:string;responseMs:number;repeatWeakness:boolean;existingUnresolvedGuess:boolean;existingState:string}>;timeSignals?:{slowMs:number;fastMs:number;slowLabel:string;fastWrongLabel:string}};

const KEY="revision:v2:gk:section-sprint:v2",LEGACY_KEY="revision:v2:gk:section-sprint:v1";
const quiz=(p:Record<string,string|number>)=>`/gk/quiz?${new URLSearchParams(Object.entries(p).map(([k,v])=>[k,String(v)]))}`;
function mmss(seconds:number){const s=Math.max(0,Math.ceil(seconds));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
function phaseCopy(p:Plan["phase"]){return p==="EARLY"?"Concept repair first · Topic-wise emphasis":p==="MIDDLE"?"Balanced Topic-wise + Mixed retrieval":"Mixed retrieval + timed transfer + weak repair";}
function scoreAnswers(answers:Record<string,Answer>,total:number):Result{const vals=Object.values(answers),correct=vals.filter(x=>x.correct).length,wrong=vals.length-correct,unattempted=Math.max(0,total-vals.length);return {total,attempted:vals.length,score:Math.round((correct*2-wrong*.5)*100)/100,maxScore:total*2,correct,wrong,unattempted,accuracy:vals.length?Math.round(correct*1000/vals.length)/10:0,averageTimeMs:vals.length?Math.round(vals.reduce((a,x)=>a+x.responseMs,0)/vals.length):0,marksLostWrong:wrong*.5,marksLostUnattempted:unattempted*2};}
function readSaved():SavedSprint|null{try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw) as SavedSprint;if(x?.version===2&&x.sessionId)return x;}const legacy=localStorage.getItem(LEGACY_KEY);return legacy?{version:2,sessionId:legacy,paused:false,pausedAt:0,pausedTotalMs:0}:null;}catch{return null;}}
function writeSaved(x:SavedSprint){try{localStorage.setItem(KEY,JSON.stringify(x));localStorage.removeItem(LEGACY_KEY);}catch{}}
function clearSaved(){try{localStorage.removeItem(KEY);localStorage.removeItem(LEGACY_KEY);}catch{}}
function remaining(session:SprintSession,pausedTotalMs:number,paused:boolean,pausedAt:number){const start=new Date(session.startedAt).getTime(),stop=paused&&pausedAt>0?pausedAt:Date.now(),elapsed=Math.max(0,stop-start-pausedTotalMs);return Math.max(0,session.durationSeconds-elapsed/1000);}
function repairHref(sessionId:string,conceptKey?:string,count=12,title="Sprint Smart Repair"){return quiz({repairSprint:sessionId,...conceptKey?{repairConcept:conceptKey}:{},mode:"sprint_repair",lane:"MIXED",count,title});}

export default function GkSprintPage(){
 const ready=useAuthGuard();
 const[plan,setPlan]=useState<Plan|null>(null),[session,setSession]=useState<SprintSession|null>(null),[answers,setAnswers]=useState<Record<string,Answer>>({}),[index,setIndex]=useState(0),[left,setLeft]=useState(900),[result,setResult]=useState<Result|null>(null),[analysis,setAnalysis]=useState<SprintAnalysis|null>(null),[analysisError,setAnalysisError]=useState(""),[error,setError]=useState(""),[paused,setPaused]=useState(false),[pausedAt,setPausedAt]=useState(0),[pausedTotalMs,setPausedTotalMs]=useState(0),[source,setSource]=useState<SprintSource>("EXAM_MIXED");
 const questionStart=useRef(Date.now()),answersRef=useRef<Record<string,Answer>>({}),finishing=useRef(false);
 useEffect(()=>{answersRef.current=answers},[answers]);
 async function loadAnalysis(sessionId:string,generate=false){if(isGkLocalSafe())return;setAnalysisError("");try{const x=await gkRpc<SprintAnalysis>(generate?"gk_analyze_section_sprint":"gk_get_section_sprint_analysis",{p_session_id:sessionId});if(x?.ok){setAnalysis(x);return;}throw new Error();}catch{setAnalysisError("Your Sprint result is saved. Repair analysis could not refresh yet.");}}
 useEffect(()=>{if(!ready)return;let live=true;const unsub=subscribeGkFresh<Plan>("gk_get_sprint_plan",undefined,x=>{if(live&&x?.ok)setPlan(x)});gkRpc<Plan>("gk_get_sprint_plan").then(x=>{if(live&&x?.ok)setPlan(x)}).catch(()=>{if(live)setError("Sprint plan could not be refreshed.")});const saved=readSaved();if(saved&&!isGkLocalSafe()){gkRpc<SprintSession>("gk_get_section_sprint_session",{p_session_id:saved.sessionId}).then(x=>{if(!live||!x?.ok)return;setSession(x);setSource(x.sourceKind||"EXAM_MIXED");if(x.completed&&x.result){setResult(x.result);clearSaved();void loadAnalysis(x.sessionId,!x.analysisReady);return;}setAnswers(x.answers||{});answersRef.current=x.answers||{};setPaused(saved.paused);setPausedAt(saved.pausedAt);setPausedTotalMs(saved.pausedTotalMs);setLeft(remaining(x,saved.pausedTotalMs,saved.paused,saved.pausedAt));}).catch(clearSaved);}return()=>{live=false;unsub();};},[ready]);
 useEffect(()=>{if(!session||result||paused)return;const tick=()=>{const remain=remaining(session,pausedTotalMs,false,0);setLeft(remain);if(remain<=0)void finish(answersRef.current);};tick();const id=window.setInterval(tick,1000);return()=>window.clearInterval(id);},[session,result,paused,pausedTotalMs]);
 useEffect(()=>{questionStart.current=Date.now();},[index,paused]);
 const q=session?.questions[index],answered=q?answers[q.id]:undefined,answeredCount=Object.keys(answers).length;
 function persistPause(nextPaused:boolean,nextPausedAt:number,nextPausedTotal:number){if(!session||isGkLocalSafe())return;writeSaved({version:2,sessionId:session.sessionId,paused:nextPaused,pausedAt:nextPausedAt,pausedTotalMs:nextPausedTotal});}
 async function startExam(nextSource:SprintSource=source){setError("");setAnalysis(null);setAnalysisError("");finishing.current=false;setSource(nextSource);try{if(isGkLocalSafe()){const questions=nextSource==="TEACHER_PYQ"?await gkRpc<GkQuestion[]>("gk_get_teacher_batch",{p_series_id:"TEACHER_TOPIC_PYQ",p_lecture_key:null,p_mode:"random",p_count:25,p_lane:"MAIN"}):await gkRpc<GkQuestion[]>("gk_get_batch",{p_mode:"random",p_count:25,p_lane:"MAIN"});setSession({ok:true,sessionId:`local-sprint-${Date.now()}`,durationSeconds:900,startedAt:new Date().toISOString(),questions,sourceKind:nextSource,actualCount:questions.length});setAnswers({});answersRef.current={};setIndex(0);setResult(null);setPaused(false);setPausedAt(0);setPausedTotalMs(0);setLeft(900);return;}const x=await gkRpc<SprintSession>("gk_start_section_sprint",{p_count:25,p_source:nextSource});if(!x?.ok||!x.questions?.length)throw new Error();writeSaved({version:2,sessionId:x.sessionId,paused:false,pausedAt:0,pausedTotalMs:0});setSession(x);setAnswers({});answersRef.current={};setIndex(0);setResult(null);setPaused(false);setPausedAt(0);setPausedTotalMs(0);setLeft(x.durationSeconds);}catch{setError(nextSource==="TEACHER_PYQ"?"Teacher PYQ Sprint could not start. There may be no eligible unique Teacher questions right now.":"Section Sprint could not start.");}}
 function pauseExam(){if(!session||paused||result)return;const now=Date.now();setLeft(remaining(session,pausedTotalMs,true,now));setPaused(true);setPausedAt(now);persistPause(true,now,pausedTotalMs);}
 function resumeExam(){if(!session||!paused||result)return;const extra=pausedAt>0?Math.max(0,Date.now()-pausedAt):0,nextTotal=pausedTotalMs+extra;setPausedTotalMs(nextTotal);setPausedAt(0);setPaused(false);setLeft(remaining(session,nextTotal,false,0));questionStart.current=Date.now();persistPause(false,0,nextTotal);}
 function leaveExam(){if(!session){window.location.href="/gk/sprint";return;}if(!paused){const now=Date.now();persistPause(true,now,pausedTotalMs);setPaused(true);setPausedAt(now);}else persistPause(true,pausedAt,pausedTotalMs);window.location.href="/gk/sprint";}
 function choose(key:string){if(!q||answered||result||paused)return;const responseMs=Math.max(0,Date.now()-questionStart.current),next={...answersRef.current,[q.id]:{selected:key,correct:key===q.correctKey,responseMs}};answersRef.current=next;setAnswers(next);}
 async function finish(latest=answersRef.current){if(!session||result||finishing.current)return;finishing.current=true;setError("");try{if(isGkLocalSafe()){setResult(scoreAnswers(latest,session.questions.length));return;}const x=await gkRpc<{ok:boolean;result:Result;learningHistoryChanged:boolean}>("gk_finish_section_sprint",{p_session_id:session.sessionId,p_answers:latest});if(!x?.ok||x.learningHistoryChanged)throw new Error();setResult(x.result);clearSaved();void loadAnalysis(session.sessionId,true);}catch{finishing.current=false;setError("Result save did not complete. Your answers remain on this screen; retry Finish.");}}
 function resetToSprintHome(){finishing.current=false;setSession(null);setAnswers({});answersRef.current={};setIndex(0);setResult(null);setAnalysis(null);setAnalysisError("");setLeft(900);setPaused(false);setPausedAt(0);setPausedTotalMs(0);clearSaved();}
 if(!ready)return <main className="gk-intel-page"><div className="loading-copy">Checking session…</div></main>;
 if(result)return <ResultView result={result} sessionId={session?.sessionId||""} source={session?.sourceKind||source} analysis={analysis} analysisError={analysisError} onRetry={()=>session?.sessionId&&void loadAnalysis(session.sessionId,true)} onRestart={resetToSprintHome}/>;
 if(session&&q)return <main className="gk-sprint-exam">
   <header className="gk-sprint-examhead"><div className="gk-sprint-examidentity"><button className="gk-sprint-back" onClick={leaveExam}>← Sprint</button><div><span>{session.sourceKind==="TEACHER_PYQ"?"Teacher PYQ Sprint":"GK Section Sprint"}</span><b>Question {index+1} of {session.questions.length}</b></div></div><div className="gk-sprint-pause"><button onClick={paused?resumeExam:pauseExam}>{paused?"▶ Resume":"Ⅱ Pause"}</button><div className={left<=120?"gk-sprint-timer is-low":"gk-sprint-timer"}>{mmss(left)}</div></div></header>
   <div className="gk-sprint-progress"><i style={{width:`${((index+1)/session.questions.length)*100}%`}}/></div>
   {error&&<div className="gk-intel-notice">{error}</div>}
   {paused?<section className="gk-sprint-paused"><span>Section Sprint paused</span><h2>Your timer is frozen.</h2><p>Resume when you are free. Your question, answers and remaining time are preserved on this device.</p><button onClick={resumeExam}>Resume Sprint</button></section>:<><section className="gk-sprint-question"><div className="gk-sprint-meta">{q.subject||"GK"}{q.topic?` · ${q.topic}`:""}</div><div className="gk-sprint-questiontext"><QuestionText text={q.question}/></div><div className="gk-sprint-options">{q.options.map(o=><button key={o.key} className={answered?.selected===o.key?"is-selected":""} onClick={()=>choose(o.key)} disabled={!!answered}><b>{o.key}</b><span>{o.text}</span></button>)}</div></section>
   <footer className="gk-sprint-dock"><button onClick={()=>setIndex(x=>Math.max(0,x-1))} disabled={index===0}>← Previous</button><span>{answeredCount}/{session.questions.length} attempted</span>{index===session.questions.length-1?<button className="is-primary" onClick={()=>void finish()}>Finish</button>:<button className="is-primary" onClick={()=>setIndex(x=>Math.min(session.questions.length-1,x+1))}>Next →</button>}</footer></>}
  </main>;
 return <main className="gk-intel-page">
  <section className="gk-intel-title"><div><span>30-Day Exam Readiness</span><h1>SSC GK Sprint</h1><p>{plan?phaseCopy(plan.phase):"Adaptive work based on your current retention evidence."}</p></div><Link href="/gk/intelligence" className="gk-intel-secondary">View readiness</Link></section>
  {error&&<div className="gk-intel-notice">{error}</div>}
  <section className="gk-sprint-feature"><div><span>Exam Simulation</span><h2>25 Questions · 15 Minutes</h2><p>+2 correct · −0.50 wrong · 0 unattempted. Sprint answers remain exam evidence only; adaptive mastery changes only inside the later repair quiz.</p></div><div className="gk-sprint-source-actions"><button className={source==="EXAM_MIXED"?"is-selected":""} onClick={()=>void startExam("EXAM_MIXED")}><b>Exam Mixed</b><small>Canonical Main-lane mix</small></button><button className={source==="TEACHER_PYQ"?"is-selected":""} onClick={()=>void startExam("TEACHER_PYQ")}><b>Teacher PYQ Sprint</b><small>Deduped Teacher PYQ · Main only</small></button></div></section>
  <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Today</span><h2>Recommended work</h2></div>{plan&&<b>{plan.phase} phase</b>}</div><div className="gk-sprint-plan">{(plan?.actions||[]).map(a=>a.key==="section"?<button key={a.key} onClick={()=>void startExam("EXAM_MIXED")}><span>◷</span><div><b>{a.title}</b><small>25Q timed exam transfer</small></div><strong>Start ›</strong></button>:<Link key={a.key} href={quiz({...a.key==="teacher"?{teacherSeries:"TEACHER_TOPIC_PYQ"}:{},mode:a.mode,lane:a.lane,count:Math.max(1,a.count||10),title:a.title})}><span>{a.key==="weak"?"☀":a.key==="night"?"☾":a.key==="teacher"?"▣":a.key==="current"?"◉":"↻"}</span><div><b>{a.title}</b><small>{a.count>0?`${a.count} currently eligible`:"Open recommended lane"}</small></div><strong>›</strong></Link>)}</div></section>
  {plan&&<section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Adaptive emphasis</span><h2>{phaseCopy(plan.phase)}</h2></div></div><div className="gk-intel-week"><div className="gk-intel-metric"><strong>{plan.counts.weak}</strong><span>Weak</span></div><div className="gk-intel-metric"><strong>{plan.counts.due}</strong><span>Due</span></div><div className="gk-intel-metric"><strong>{plan.counts.unseen_teacher}</strong><span>Unseen teacher PYQ</span></div></div></section>}
 </main>;
}

function ResultView({result,sessionId,source,analysis,analysisError,onRetry,onRestart}:{result:Result;sessionId:string;source:SprintSource;analysis:SprintAnalysis|null;analysisError:string;onRetry:()=>void;onRestart:()=>void}){
 const wrongLost=Number(result.marksLostWrong??result.wrong*.5),unattemptedLost=Number(result.marksLostUnattempted??result.unattempted*2),repairs=analysis?.repairs||[];
 return <main className="gk-intel-page gk-sprint-result">
  <section className="gk-intel-title"><div><span>{source==="TEACHER_PYQ"?"Teacher PYQ Sprint Result":"GK Section Sprint Result"}</span><h1>{result.score} / {result.maxScore}</h1><p>Exam evidence stays separate from adaptive mastery. Repair answers below re-enter the normal GK learning system.</p></div><button className="gk-intel-secondary" onClick={onRestart}>Sprint home</button></section>
  <section className="gk-intel-kpis"><div className="gk-intel-metric"><strong>{result.correct}</strong><span>Correct</span></div><div className="gk-intel-metric"><strong>{result.wrong}</strong><span>Wrong</span></div><div className="gk-intel-metric"><strong>{result.unattempted}</strong><span>Unattempted</span></div><div className="gk-intel-metric"><strong>{result.accuracy}%</strong><span>Accuracy</span><small>{(result.averageTimeMs/1000).toFixed(1)}s avg/attempt</small></div></section>
  <section className="gk-sprint-loss-card"><div><span>Marks lost</span><b>{Math.round((wrongLost+unattemptedLost)*100)/100}</b></div><div><small>Wrong answers</small><strong>{wrongLost} marks</strong></div><div><small>Unattempted</small><strong>{unattemptedLost} marks</strong></div></section>
  {analysis?.analysisReady?<>
   <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Where marks were lost</span><h2>Subject loss map</h2></div></div><div className="gk-sprint-loss-list">{analysis.subjects.filter(x=>x.marksLost>0).map(x=><div key={x.subject}><span><b>{x.subject}</b><small>{x.wrong} wrong · {x.unattempted} unattempted · {x.conceptsNeedingRepair} repair concept{x.conceptsNeedingRepair===1?"":"s"}</small></span><strong>{x.marksLost} lost</strong></div>)}</div></section>
   <section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Recommended Repair</span><h2>{repairs.length?"Fix the highest-value losses first":"No concept repair surfaced"}</h2></div>{repairs.length>0&&<b>{repairs.length} concepts</b>}</div>{repairs.length>0?<><Link className="gk-sprint-smart-repair" href={repairHref(sessionId,undefined,12,"Sprint Smart Repair")}>Start Smart Repair <span>›</span></Link><div className="gk-sprint-repair-list">{repairs.slice(0,6).map((r,i)=><article key={r.conceptKey}><div><span>{i+1}. {r.subject}</span><h3>{r.topic}</h3><p>{r.reason}</p></div><Link href={repairHref(sessionId,r.conceptKey,6,`${r.topic} · Sprint Repair`)}>Start Repair</Link></article>)}</div></>:<p className="gk-sprint-clean-result">This Sprint did not produce a wrong or unattempted concept that needs targeted repair.</p>}</section>
   {analysis.questionIssues.some(x=>x.classification.includes("Slow")||x.classification==="Fast Wrong")&&<section className="gk-intel-card"><div className="gk-intel-cardhead"><div><span>Response-time signal</span><h2>Time-heavy / fast incorrect responses</h2></div></div><p className="gk-sprint-signal-copy">These labels use your own Sprint response-time distribution where enough timing evidence exists. They describe response speed only, not psychology or confidence.</p></section>}
  </>:analysisError?<div className="gk-intel-notice"><b>Result saved.</b> {analysisError} <button onClick={onRetry}>Retry analysis</button></div>:!isGkLocalSafe()?<div className="gk-sprint-analysis-loading">Building concept-level repair recommendations…</div>:<div className="gk-intel-notice">Local Safe keeps production exam diagnostics read-only. Result scoring is available locally; repair analysis runs only in production.</div>}
 </main>;
}
