"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { ReactNode, useEffect, useRef, useState } from "react";
import { localProductionSafetyMode, pendingAnswerSaves, prefetchEnglishCore } from "@/lib/supabase";

type Tab = "home" | "practice" | "revision" | "library" | "progress";type Theme = "dark" | "light";
const tabs: { id: Tab; href: string; icon: string; label: string }[] = [{ id: "home", href: "/english", icon: "⌂", label: "Home" },{ id: "practice", href: "/english/practice", icon: "◎", label: "Practice" },{ id: "revision", href: "/english/revision", icon: "↻", label: "Revision" },{ id: "library", href: "/english/library", icon: "▦", label: "Library" },{ id: "progress", href: "/english/progress", icon: "◔", label: "Progress" }];
function tabForPath(pathname: string): Tab {if (pathname === "/english" || pathname.startsWith("/english/daily") || pathname.startsWith("/english/resume") || pathname.startsWith("/english/extra")) return "home";if (pathname === "/english/practice" || /\/(new|topics|sources|demand|bank|targeted|fast-track|exam)(?:\/|$)/.test(pathname)) return "practice";if (pathname === "/english/revision" || pathname.startsWith("/english/revision/") || /\/(starred|difficult|weak|phrasal)(?:\/|$)/.test(pathname)) return "revision";if (pathname === "/english/library" || /\/(saved|hindu|library)(?:\/|$)/.test(pathname)) return "library";if (pathname === "/english/progress" || pathname.startsWith("/english/progress/")) return "progress";return "home";}
function applyTheme(next:Theme,persist=false){document.documentElement.dataset.theme=next;document.documentElement.style.colorScheme=next;const color=next==="light"?"#f5f7fb":"#0d1117";document.querySelectorAll('meta[name="theme-color"]').forEach(el=>el.setAttribute("content",color));if(persist)window.localStorage.setItem("english-theme",next)}

export function EnglishFrame({ children, tab }: { children: ReactNode; tab?: Tab }) {
  const pathname = usePathname();const router=useRouter();const active = tab ?? tabForPath(pathname);const isHome=pathname==="/english";const [theme, setTheme] = useState<Theme>("dark");const [pendingSaves, setPendingSaves] = useState(0);const [syncSaved,setSyncSaved]=useState(false);const [refreshing, setRefreshing] = useState(false);const [localSafe,setLocalSafe]=useState(false);const savedTimer=useRef<number|null>(null);
  useEffect(() => {const saved = window.localStorage.getItem("english-theme");const next: Theme = saved === "light" ? "light" : "dark";setTheme(next);applyTheme(next);setLocalSafe(localProductionSafetyMode());try {const current = new URL(window.location.href);if (current.searchParams.has("_refresh")) {current.searchParams.delete("_refresh");const clean = `${current.pathname}${current.search}${current.hash}`;window.history.replaceState(window.history.state, "", clean);}} catch {}const warm = () => { void prefetchEnglishCore(); };const refreshPending = () => setPendingSaves(pendingAnswerSaves());warm();refreshPending();const warmTimer = window.setInterval(warm, 120000);const saveTimer = window.setInterval(refreshPending, 800);const onVisible = () => { if (!document.hidden) { warm();refreshPending(); } };const onDurable = () => {const nextPending=pendingAnswerSaves();setPendingSaves(nextPending);if(nextPending===0){setSyncSaved(true);if(savedTimer.current)window.clearTimeout(savedTimer.current);savedTimer.current=window.setTimeout(()=>{setSyncSaved(false);savedTimer.current=null;},900);}};window.addEventListener("online", warm);window.addEventListener("ep:answer-durable", onDurable as EventListener);document.addEventListener("visibilitychange", onVisible);return () => {window.clearInterval(warmTimer);window.clearInterval(saveTimer);if(savedTimer.current)window.clearTimeout(savedTimer.current);window.removeEventListener("online", warm);window.removeEventListener("ep:answer-durable", onDurable as EventListener);document.removeEventListener("visibilitychange", onVisible);};}, []);
  useEffect(()=>{if(pathname!=="/english")return;window.history.pushState({...window.history.state,englishHomeGuard:true},"",window.location.href);const onBack=()=>router.replace("/");window.addEventListener("popstate",onBack);return()=>window.removeEventListener("popstate",onBack);},[pathname,router]);
  function toggleTheme() {const next: Theme = theme === "dark" ? "light" : "dark";setTheme(next);applyTheme(next,true);}
  async function hardRefresh() {if (refreshing) return;setRefreshing(true);try {const keys: string[] = [];for (let i = 0; i < window.localStorage.length; i++) {const key = window.localStorage.key(i);if (key?.startsWith("ep:v2:rpc-cache:")) keys.push(key);}keys.forEach(key => window.localStorage.removeItem(key));} catch {}try {if ("caches" in window) {const names = await window.caches.keys();await Promise.allSettled(names.map(name => window.caches.delete(name)));}} catch {}const target = new URL(window.location.href);target.searchParams.set("_refresh", Date.now().toString());window.location.replace(target.toString());}
  return <div className="english-app"><header className="english-header"><Link href="/english" className="english-brand" aria-label="English Mastery home"><strong>English Mastery</strong><span>SSC English practice + revision</span></Link><div className="header-controls">{localSafe&&<span className="sync-pill" title="Localhost safety mode: production learning-data writes are simulated locally and are not sent to Supabase">Local Safe</span>}{pendingSaves>0&&(isHome?<span className="sync-home-pending" title="Answers stored locally and waiting for durable sync"><i/>{pendingSaves} pending</span>:<span className="sync-status-dot sync-pending" role="status" aria-label={`${pendingSaves} answer${pendingSaves===1?"":"s"} pending sync`} title={`${pendingSaves} pending`}/>)}{!isHome&&pendingSaves===0&&syncSaved&&<span className="sync-status-dot sync-saved" role="status" aria-label="Latest answer saved" title="Saved"/>}{isHome&&<Link href="/" className="control-icon root-launcher" aria-label="Open app launcher" title="All Apps">▦</Link>}<button className="control-icon theme-toggle" type="button" aria-label={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"} onClick={toggleTheme}>{theme === "dark" ? "☀" : "☾"}</button><button className={`control-icon hard-refresh ${refreshing ? "refreshing" : ""}`} type="button" aria-label="Hard refresh app" title="Refresh app and cached data" onClick={() => void hardRefresh()} disabled={refreshing}>↻</button></div></header><div className="english-content">{children}</div><nav className="english-nav" aria-label="English navigation">{tabs.map((item) => <Link key={item.id} href={item.href} className={`english-nav-item ${active === item.id ? "active":""}`} aria-current={active === item.id ? "page" : undefined}><b>{item.icon}</b><span>{item.label}</span></Link>)}</nav></div>;
}
export function EnglishLoading({ text = "Loading…" }: { text?: string }) {return <div className="english-app"><div className="loading-shell"><i/><i/><i/><span>{text}</span></div></div>}
