"use client";

import Link from "next/link";
import { Suspense, useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { MathsDiagram } from "@/components/maths-diagram";
import { MathsLoading } from "@/components/maths-frame";
import { mathsCoachRpc } from "@/lib/maths-coach-rpc";
import { refillAiCalculationSprint } from "@/lib/maths-calculation-ai";
import { mathsErrorMessage, mathsLocalSafe, rememberMathsSession, type MathsQuestion, type MathsSession } from "@/lib/maths-rpc";
import { supabaseBrowser } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";

type Reason="CAL"|"APP"|"CON"|"FOR"|"SILLY"|"TIME";
type ExamSession=MathsSession&{remainingSeconds?:number|null;expired?:boolean};
type AttemptResult={ok:boolean;expired?:boolean;message?:string;result?:string;selectedOption?:string;attemptId?:string};
type SprintAnalysis={ok:boolean;score:number;maxScore:number;correct:number;wrong:number;unattempted:number;recoverableMarksEstimate:number;reasons:Record<string,number>;bestNextAction?:string;stability?:unknown};
type ReviewItem={position:number;questionId:string;chapter:string;topic:string;prompt:string;answer:string;explanation:string;correctOption:string;selectedOption?:string|null;selectedOptionText?:string|null;correctOptionText?:string|null;attemptId?:string|null;result:string;responseSec?:number|null;baselineSec?:number|null;inferredReason?:Reason|null;confirmedReason?:Reason|null;finalReason?:Reason|null;slowCorrect?:boolean};
type SprintReview={ok:boolean;items:ReviewItem[]};
type CalcSummary={ok:boolean;attempted:number;correct:number;wrong:number;accuracy:number;qpm:number;medianSec:number;p75Sec:number;p90Sec:number;elapsedSec:number;skills:{skill:string;attempted:number;accuracy:number;medianSec:number;baselineSec:number;band:string}[]};

const POS="maths:exam:v2:pos:";const REVIEW="maths:exam:v2:review:";const VISITED="maths:exam:v2:visited:";
const reasons:Reason[]=["CAL","APP","CON","FOR","SILLY","TIME"];
function clock(v:number|null|undefined){const n=Math.max(0,Math.ceil(Number(v||0)));return`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;}
function readNum(key:string){try{const v=localStorage.getItem(key);return v==null?null:Number(v);}catch{return null;}}
function readSet(key:string){try{const raw=localStorage.getItem(key);return raw?new Set<number>((JSON.parse(raw) as number[]).map(Number)):new Set<number>();}catch{return new Set<number>();}}
function saveRuntime(id:string,index:number,review:Set<number>,visited:Set<number>){try{localStorage.setItem(POS+id,String(index));localStorage.setItem(REVIEW+id,JSON.stringify([...review]));localStorage.setItem(VISITED+id,JSON.stringify([...visited]));}catch{}}
function clearRuntime(id:string){try{localStorage.removeItem(POS+id);localStorage.removeItem(REVIEW+id);localStorage.removeItem(VISITED+id);}catch{}}
async function freshSession(id:string):Promise<ExamSession>{if(mathsLocalSafe())return mathsCoachRpc<ExamSession>("maths_get_session",{p_session_id:id});const{data,error}=await supabaseBrowser().rpc("maths_get_session",{p_session_id:id});if(error)throw error;return data as ExamSession;}
function stateFor(session:ExamSession,i:number,review:Set<number>,visited:Set<number>){const q=session.questions[i],answered=!!q&&!!session.attempts?.[q.questionId];if(review.has(i))return answered?"answered review":"review";if(answered)return"answered";if(visited.has(i))return"visited";return"";}

function QuestionStrip({session,index,review,visited,onJump}:{session:ExamSession;index:number;review:Set<number>;visited:Set<number>;onJump:(i:number)=>void}){return <div className="mexq-strip" aria-label="Question jumping">{session.questions.slice(0,session.target).map((q,i)=><button type="button" key={`${q.questionId}-${i}`} className={`${stateFor(session,i,review,visited)} ${i===index?"current":""}`} onClick={()=>onJump(i)} aria-label={`Question ${i+1}`}>{i+1}</button>)}</div>}
function MapModal({session,index,review,visited,onJump,onClose}:{session:ExamSession;index:number;review:Set<number>;visited:Set<number>;onJump:(i:number)=>void;onClose:()=>void}){return <div className="mexq-map-bg" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="mexq-map" role="dialog" aria-modal="true"><header><div><small>QUESTION MAP</small><strong>Jump to any question</strong></div><button type="button" onClick={onClose}>×</button></header><div className="mexq-map-grid">{session.questions.slice(0,session.target).map((q,i)=><button type="button" key={`${q.questionId}-${i}`} className={`${stateFor(session,i,review,visited)} ${i===index?"current":""}`} onClick={()=>onJump(i)}>{i+1}</button>)}</div><div className="mexq-legend"><span><i className="answered"/>Attempted</span><span><i className="review"/>Review</span><span><i className="visited"/>Visited</span><span><i className="current"/>Current</span></div></section></div>}

function CalcResult({session}:{session:ExamSession}){const[data,setData]=useState<CalcSummary|null>(null);const[error,setError]=useState("");useEffect(()=>{void mathsCoachRpc<CalcSummary>("maths_get_calculation_summary",{p_session_id:session.sessionId}).then(setData).catch(e=>setError(mathsErrorMessage(e)));},[session.sessionId]);if(!data&&!error)return <MathsLoading text="Building Calculation report…"/>;return <section className="mexr-page"><header><Link href="/maths/exam?tab=calculation">← Calculation</Link><div><small>10-MIN SSC CALCULATION</small><h1>Speed report</h1></div></header>{error&&<div className="mex2-error">{error}</div>}{data&&<><div className="mexr-score"><div><b>{data.attempted}</b><small>Attempted</small></div><div><b>{data.accuracy.toFixed(0)}%</b><small>Accuracy</small></div><div><b>{data.qpm.toFixed(1)}</b><small>Q/min</small></div><div><b>{data.medianSec.toFixed(1)}s</b><small>Median</small></div></div><p className="mexr-note">Calculation evidence stays in the separate speed track and does not change Academic readiness.</p><div className="mexr-skills">{data.skills.map(x=><div key={x.skill}><span><b>{x.skill}</b><small>{x.attempted} · {x.accuracy.toFixed(0)}% · {x.medianSec.toFixed(1)}s median</small></span><strong>{x.band}</strong></div>)}</div><Link className="mex2-primary" href="/maths/exam?tab=calculation">Back to Calculation</Link></>}</section>}

function SprintResult({session}:{session:ExamSession}){const[analysis,setAnalysis]=useState<SprintAnalysis|null>(null);const[review,setReview]=useState<ReviewItem[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState("");useEffect(()=>{void Promise.all([mathsCoachRpc<SprintAnalysis>("maths_get_sprint_analysis",{p_session_id:session.sessionId}),mathsCoachRpc<SprintReview>("maths_get_sprint_review",{p_session_id:session.sessionId})]).then(([a,r])=>{setAnalysis(a);setReview(r.items||[])}).catch(e=>setError(mathsErrorMessage(e)));},[session.sessionId]);async function confirm(item:ReviewItem,reason:Reason){if(!item.attemptId)return;setBusy(item.attemptId+reason);try{await mathsCoachRpc("maths_confirm_diagnosis",{p_attempt_id:item.attemptId,p_reason:reason,p_confidence_response:null});setReview(rows=>rows.map(x=>x.questionId===item.questionId?{...x,confirmedReason:reason,finalReason:reason}:x));}catch(e){setError(mathsErrorMessage(e));}finally{setBusy("");}}if(!analysis&&!error)return <MathsLoading text="Analysing marks leakage…"/>;return <section className="mexr-page"><header><Link href="/maths/exam">← Academic</Link><div><small>SSC STANDARD COMPLETE</small><h1>{analysis?`${analysis.score}/50`:"Sprint report"}</h1></div></header>{error&&<div className="mex2-error">{error}</div>}{analysis&&<><div className="mexr-score"><div><b>{analysis.correct}</b><small>Correct</small></div><div><b>{analysis.wrong}</b><small>Wrong</small></div><div><b>{analysis.unattempted}</b><small>Unattempted</small></div><div><b>{analysis.recoverableMarksEstimate}</b><small>Recoverable</small></div></div><div className="mexr-leaks">{reasons.map(r=><div key={r}><span>{r}</span><b>{Number(analysis.reasons?.[r]||0)}</b></div>)}</div>{analysis.bestNextAction&&<p className="mexr-note"><b>Next:</b> {analysis.bestNextAction}</p>}<h2>Review misses & slow answers</h2><div className="mexr-review">{review.length?review.map(item=><article key={`${item.questionId}-${item.position}`}><small>Q{item.position+1} · {item.chapter}{item.topic?` · ${item.topic}`:""}</small><h3>{item.prompt}</h3><p><b>Your answer:</b> {item.selectedOptionText||item.selectedOption||"Unanswered"}</p><p><b>Correct:</b> {item.correctOptionText||item.answer||item.correctOption}</p>{item.explanation&&<p className="explain">{item.explanation}</p>}{item.attemptId&&item.result!=="unattempted"&&<div className="mexr-reasons">{reasons.map(r=><button type="button" className={(item.confirmedReason||item.finalReason||item.inferredReason)===r?"active":""} disabled={!!busy} key={r} onClick={()=>void confirm(item,r)}>{r}</button>)}</div>}</article>):<div className="mexr-clean">No wrong or slow items to review.</div>}</div><Link className="mex2-primary" href="/maths/exam">Back to Academic</Link></>}</section>}

function ExamInner(){
  const ready=useAuthGuard();const search=useSearchParams();const id=search.get("id")||"";const[session,setSession]=useState<ExamSession|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[remaining,setRemaining]=useState<number|null>(null);const[review,setReview]=useState<Set<number>>(new Set());const[visited,setVisited]=useState<Set<number>>(new Set());const[map,setMap]=useState(false);const[confirmFinish,setConfirmFinish]=useState(false);const[refilling,setRefilling]=useState(false);const started=useRef(Date.now());const checkpoint=useRef<Promise<void>>(Promise.resolve());const refillLock=useRef(false);const finishing=useRef(false);
  const saveCheckpoint=useCallback((sid:string,index:number,r:Set<number>,v:Set<number>)=>{saveRuntime(sid,index,r,v);const task=checkpoint.current.catch(()=>undefined).then(async()=>{await mathsCoachRpc("maths_exam_runtime_checkpoint",{p_session_id:sid,p_index:index,p_review:[...r].sort((a,b)=>a-b),p_visited:[...v].sort((a,b)=>a-b)});});checkpoint.current=task.catch(e=>setError(mathsErrorMessage(e,"Position saved locally; server checkpoint will retry on next action.")));return checkpoint.current;},[]);
  const load=useCallback(async()=>{if(!id)throw new Error("Session ID is missing.");const fresh=await freshSession(id);if(fresh.completed){clearRuntime(id);setSession(fresh);return;}const max=Math.max(0,fresh.questions.length-1);const local=readNum(POS+id);const index=Math.max(0,Math.min(local??Number(fresh.currentIndex||0),max));const r=readSet(REVIEW+id);const v=readSet(VISITED+id);const serverR=new Set<number>((fresh.params?.examReview as number[]||[]).map(Number)),serverV=new Set<number>((fresh.params?.examVisited as number[]||[]).map(Number));const rr=r.size?r:serverR;const vv=new Set<number>([...serverV,...v,index]);const next={...fresh,currentIndex:index};setSession(next);setReview(rr);setVisited(vv);setRemaining(fresh.remainingSeconds==null?null:Number(fresh.remainingSeconds));started.current=Date.now();rememberMathsSession(next);void saveCheckpoint(id,index,rr,vv);},[id,saveCheckpoint]);
  useEffect(()=>{if(ready)void load().catch(e=>setError(mathsErrorMessage(e,"Could not restore timed session.")));},[ready,load]);
  const mode=String(session?.mode||"").toLowerCase(),isSprint=mode==="section_sprint",isCalc=mode==="calculation_speed"&&Boolean(session?.params?.calculationTimed),timed=isSprint||isCalc,index=session?Math.max(0,Math.min(Number(session.currentIndex||0),Math.max(0,session.questions.length-1))):0,q=session?.questions[index],attempt=q?session?.attempts?.[q.questionId]:undefined,selected=attempt?.selectedOption||"",answered=session?session.questions.slice(0,session.target).filter(x=>!!session.attempts?.[x.questionId]).length:0,unanswered=session?Math.max(0,session.target-answered):0,deadline=String(session?.params?.deadlineAt||""),aiCalc=isCalc&&Boolean(session?.params?.aiGenerated);
  const finish=useCallback(async(force=false)=>{if(!session||finishing.current)return;if(!force&&isSprint&&unanswered>0){setConfirmFinish(true);return;}finishing.current=true;setBusy(true);setError("");try{await checkpoint.current.catch(()=>undefined);await mathsCoachRpc("maths_finish_session",{p_session_id:session.sessionId});const fresh=await freshSession(session.sessionId);setSession({...fresh,completed:true});clearRuntime(session.sessionId);}catch(e){setError(mathsErrorMessage(e,"Could not finish timed session."));}finally{setBusy(false);finishing.current=false;setConfirmFinish(false);}},[session,isSprint,unanswered]);
  useEffect(()=>{if(!timed||session?.completed||!deadline)return;const tick=()=>{const sec=Math.max(0,(Date.parse(deadline)-Date.now())/1000);setRemaining(sec);if(sec<=0)void finish(true);};tick();const t=setInterval(tick,250);return()=>clearInterval(t);},[timed,deadline,session?.completed,finish]);
  async function move(to:number,source=session!){if(!source)return;const nextIndex=Math.max(0,Math.min(to,Math.max(0,source.questions.length-1))),v=new Set(visited);v.add(nextIndex);const next={...source,currentIndex:nextIndex};setSession(next);setVisited(v);rememberMathsSession(next);started.current=Date.now();void saveCheckpoint(source.sessionId,nextIndex,review,v);}
  async function answer(key?:string){if(!session||!q||attempt||busy)return;setBusy(true);setError("");const elapsed=Math.max(0,(Date.now()-started.current)/1000),client=`mex2-${session.sessionId}-${q.questionId}`;try{const out=await mathsCoachRpc<AttemptResult>("maths_submit_answer",{p_session_id:session.sessionId,p_question_id:q.questionId,p_selected_option:key??null,p_response_sec:Number(elapsed.toFixed(1)),p_client_attempt_key:client});if(out.expired){await load();return;}if(out.ok===false)throw new Error(out.message||"Could not save answer.");const next={...session,attempts:{...(session.attempts||{}),[q.questionId]:{result:"saved",selectedOption:out.selectedOption??key??"",responseSec:elapsed,attemptId:out.attemptId??client}}};setSession(next);rememberMathsSession(next);if(isCalc&&index<next.questions.length-1)setTimeout(()=>void move(index+1,next),90);}catch(e){setError(mathsErrorMessage(e,"Could not save answer."));}finally{setBusy(false);}}
  function toggleReview(){if(!session)return;const r=new Set(review);r.has(index)?r.delete(index):r.add(index);setReview(r);void saveCheckpoint(session.sessionId,index,r,visited);}
  useEffect(()=>{if(!session||!aiCalc||session.completed||refillLock.current||(remaining??0)<=35)return;const gap=session.questions.length-index-1;if(gap>10)return;refillLock.current=true;setRefilling(true);void refillAiCalculationSprint(session.sessionId).then(fresh=>{const merged={...fresh,currentIndex:index};setSession(merged);rememberMathsSession(merged);}).catch(e=>setError(mathsErrorMessage(e,"More calculation questions could not be prepared yet."))).finally(()=>{refillLock.current=false;setRefilling(false);});},[session,aiCalc,index,remaining]);

  if(!ready)return <MathsLoading text="Checking timed session…"/>;if(!session&&!error)return <MathsLoading text="Restoring exact question state…"/>;if(!session)return <div className="mex2-error">{error||"Session not found."}</div>;if(session.completed)return isSprint?<SprintResult session={session}/>:<CalcResult session={session}/>;if(!q)return <div className="mex2-error">No renderable question.</div>;
  const progress=isSprint?Math.min(100,Math.round(((index+1)/Math.max(1,session.target))*100)):Math.min(100,Math.round((600-Math.max(0,remaining??600))*100/600));const marked=review.has(index);
  return <div className={`mexq-page ${isCalc?"calc":"academic"}`}>
    <header className="mexq-head"><div className="mexq-top"><Link href={`/maths/exam${isCalc?"?tab=calculation":""}`}>←</Link><div><strong>{isSprint?"SSC Standard":"SSC Calculation"}</strong><span>{isSprint?"25Q · +2 / −0.5":"10:00 · unlimited stream"}</span></div><b className={(remaining??999)>60?"":"urgent"}>{clock(remaining??Number(session.params?.durationSec||0))}</b></div><div className="mexq-meta"><span>Q {index+1}{isSprint?`/${session.target}`:""}</span><span>{answered} attempted</span>{refilling&&<span>adding more…</span>}</div><div className="mexq-progress"><i style={{width:`${progress}%`}}/></div></header>
    <QuestionStrip session={session} index={index} review={review} visited={visited} onJump={i=>void move(i)}/>
    {error&&<div className="mex2-error">{error}</div>}
    <main className="mexq-card"><div className="mexq-qmeta"><span>{q.chapter||"Maths"}</span>{q.topic&&<span>{q.topic}</span>}<span>{q.questionId}</span></div><div className="mexq-question">{q.prompt}</div>{q.diagram&&<MathsDiagram diagram={q.diagram}/>}<div className="mexq-options">{q.answerMode==="MCQ"?q.options.map(o=><button type="button" key={o.key} disabled={!!attempt||busy} className={selected===o.key?"selected":""} onClick={()=>void answer(o.key)}><b>{o.key}</b><span>{o.text}</span></button>):<button className="mexq-seen" type="button" disabled={!!attempt||busy} onClick={()=>void answer()}>Mark attempted</button>}</div>{isSprint&&<button type="button" className={`mexq-review ${marked?"active":""}`} onClick={toggleReview}>{marked?"◆ Marked for review":"◇ Mark for review"}</button>}</main>
    <nav className="mexq-nav"><button type="button" disabled={index===0||busy} onClick={()=>void move(index-1)}>‹ Previous</button><button type="button" className="questions" onClick={()=>setMap(true)}>Questions</button>{index<session.questions.length-1?<button type="button" disabled={busy} onClick={()=>void move(index+1)}>Next ›</button>:isCalc&&refilling?<button type="button" disabled>Adding…</button>:<button type="button" disabled={busy} onClick={()=>void finish(false)}>Finish</button>}</nav>
    {map&&<MapModal session={session} index={index} review={review} visited={visited} onJump={i=>{setMap(false);void move(i)}} onClose={()=>setMap(false)}/>} 
    {confirmFinish&&<div className="mexq-finish-bg" onMouseDown={e=>{if(e.target===e.currentTarget)setConfirmFinish(false)}}><section><small>FINISH SPRINT</small><h2>{unanswered} unanswered</h2><p>Unanswered questions score zero. Use Questions to jump back, or finish now.</p><div><button type="button" onClick={()=>setConfirmFinish(false)}>Keep solving</button><button type="button" className="danger" onClick={()=>void finish(true)}>Finish now</button></div></section></div>}
  </div>;
}

export default function MathsExamSessionV2(){return <Suspense fallback={<MathsLoading text="Opening timed Maths session…"/>}><ExamInner/></Suspense>}
