"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { rpc } from "@/lib/supabase";
import { makeDisplayOptions, type DisplayOption } from "@/lib/options";

type Question={id:string;category?:string;topic?:string;subtopic?:string;word?:string;question:string;options:{key:string;text:string}[];correctKey?:string;questionType?:string;explanation?:string;tip?:string;usageNote?:string;example?:string;memoryAid?:string;related?:string;source?:string;sourcePage?:string;starred?:boolean;difficult?:boolean;mastered?:boolean};
type Props={title:string;backHref:string;load:()=>Promise<Question[]>;module?:string;emptyText?:string};

export default function QuizRunner({title,backHref,load,module="practice",emptyText="No questions are available for this selection."}:Props){
 const [items,setItems]=useState<Question[]>([]);const [idx,setIdx]=useState(0);const [selected,setSelected]=useState("");const [result,setResult]=useState<{correct:boolean;correctCanonicalKey:string}|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const started=useRef(Date.now());const optionCache=useRef(new Map<string,DisplayOption[]>());
 useEffect(()=>{let live=true;setLoading(true);optionCache.current.clear();load().then(x=>{if(live){setItems(Array.isArray(x)?x:[]);setIdx(0);started.current=Date.now()}}).catch((e:any)=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[load]);
 const q=items[idx];
 const options=useMemo(()=>{if(!q)return[];const hit=optionCache.current.get(q.id);if(hit)return hit;const made=makeDisplayOptions(q.questionType,q.options||[]);optionCache.current.set(q.id,made);return made},[q?.id,q?.questionType,q?.options]);
 const correctDisplayKey=result?options.find(o=>o.canonicalKey===result.correctCanonicalKey)?.key||result.correctCanonicalKey:"";
 function move(next:number){setIdx(next);setSelected("");setResult(null);setError("");started.current=Date.now()}
 async function answer(option:DisplayOption){if(!q||result||busy)return;setSelected(option.key);setBusy(true);try{const out=await rpc<any>("english_submit_answer",{p_question_id:q.id,p_selected_key:option.canonicalKey,p_time_seconds:Math.min(180,(Date.now()-started.current)/1000),p_marked_revision:!!q.starred,p_attempt_id:`v2-${q.id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,p_module:module});setResult({correct:!!out.is_correct,correctCanonicalKey:String(out.correct_key||q.correctKey||"")})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function setFlag(kind:"starred"|"difficult"){if(!q)return;const next=!q[kind];setItems(a=>a.map((x,i)=>i===idx?{...x,[kind]:next}:x));try{await rpc(kind==="starred"?"english_set_starred":"english_set_difficult",kind==="starred"?{p_question_id:q.id,p_starred:next}:{p_question_id:q.id,p_difficult:next})}catch(e:any){setItems(a=>a.map((x,i)=>i===idx?{...x,[kind]:!next}:x));setError(e.message)}}
 if(loading)return <main className="center"><div className="muted">Loading {title}…</div></main>;
 if(!items.length)return <main className="shell"><div className="topbar"><Link className="btn" href={backHref}>← Back</Link></div><div className="card"><h2>{title}</h2><p className="muted">{error||emptyText}</p></div></main>;
 if(!q)return <main className="shell"><div className="card error">Question position is unavailable.</div></main>;
 return <main className="shell quiz"><div className="topbar"><Link className="btn ghost" href={backHref}>← Back</Link><div><div className="brand">{title}</div><div className="muted">{idx+1} / {items.length}</div></div></div><div className="progress"><span style={{width:`${((idx+1)/items.length)*100}%`}}/></div><section className="card stack" style={{marginTop:14}}><div className="row"><span className="pill">{q.category||q.topic||"Practice"}</span>{q.source&&<span className="pill">{q.source}</span>}<span className="spacer"/><button className={`btn ${q.starred?"warn":""}`} onClick={()=>setFlag("starred")}>{q.starred?"★ Starred":"☆ Star"}</button><button className={`btn ${q.difficult?"warn":""}`} onClick={()=>setFlag("difficult")}>{q.difficult?"Difficult ✓":"Difficult"}</button></div>{q.word&&<div className="word">{q.word}</div>}<div className="question">{q.question}</div><div className="options">{options.map(o=>{let cls="option";if(selected===o.key)cls+=" selected";if(result&&o.canonicalKey===result.correctCanonicalKey)cls+=" correct";if(result&&selected===o.key&&o.canonicalKey!==result.correctCanonicalKey)cls+=" wrong";return <button key={o.key} className={cls} onClick={()=>answer(o)} disabled={!!result||busy}><b>{o.key}.</b> {o.text}</button>})}</div>{error&&<div className="error">{error}</div>}{result&&<div className="stack"><div className="row"><strong>{result.correct?"Correct":"Incorrect"}</strong><span className="pill">Answer: {correctDisplayKey}</span></div><div className="explanation">{q.explanation||"No explanation available."}{q.example?`\n\nExample: ${q.example}`:""}{q.usageNote?`\n\nUsage: ${q.usageNote}`:""}{q.tip?`\n\nTip: ${q.tip}`:""}{q.memoryAid?`\n\nMemory aid: ${q.memoryAid}`:""}</div></div>}<div className="row"><button className="btn" disabled={idx===0} onClick={()=>move(idx-1)}>Previous</button><span className="spacer"/><button className="btn primary" disabled={idx===items.length-1} onClick={()=>move(idx+1)}>Next</button></div></section></main>
}
