"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { EnglishLoading } from "@/components/english-frame";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";
import "../saved/mywords-parity.css";

type Saved={id:string;word:string;meaning:string;context:string;status:string;practiceQuestionId:string;gptStatus:string;captureType:string;resolvedType:string;created:string;partOfSpeech?:string;synonyms?:string;antonyms?:string;example?:string;explanation?:string;question?:string;optionA?:string;optionB?:string;optionC?:string;optionD?:string;correctOption?:string};const types=["AUTO","V","SM","OWS","PV","IP"];
function shortDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"})}
export default function WordsPage(){const ready=useAuthGuard(),router=useRouter();const[rows,setRows]=useState<Saved[]>([]);const[detail,setDetail]=useState<Saved|null>(null);const[editing,setEditing]=useState<string|null>(null);const[error,setError]=useState("");const[returnHref,setReturnHref]=useState("/english/library");useEffect(()=>{try{const r=new URLSearchParams(window.location.search).get("return");if(r?.startsWith("/english"))setReturnHref(r)}catch{}},[]);async function refresh(){setRows(await rpc<Saved[]>("english_get_saved_items"))}useEffect(()=>{if(ready)refresh().catch((e:any)=>setError(e.message))},[ready]);async function changeType(id:string,next:string){setRows(a=>a.map(x=>x.id===id?{...x,captureType:next}:x));try{await rpc("english_set_saved_item_type",{p_saved_id:id,p_capture_type:next});await refresh()}catch(e:any){setError(e.message);await refresh()}}if(!ready)return <EnglishLoading text="Checking session…"/>;if(detail)return <Detail item={detail} onBack={()=>setDetail(null)}/>;return <div className="saved-parity-page saved-manage-page"><section className="saved-subhead"><button className="btn ghost saved-back" onClick={()=>router.push(returnHref)}>← Back</button><div><h1>My Words</h1><p>Every word you save appears here automatically.</p></div></section>{error&&<div className="error-box">{error}</div>}<div className="mywords-final-list">{rows.map(item=><article className="mywords-final-row" key={item.id} onClick={()=>setDetail(item)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setDetail(item)}}><div><b>{item.word}</b><div className="mywords-final-status">{/pending/i.test(item.gptStatus||"")?"Pending enrichment":"In Practice"} · {shortDate(item.created)}</div>{editing===item.id&&<div className="capture-types myword-types" onClick={e=>e.stopPropagation()}>{types.map(next=><button key={next} className={`capture-type ${item.captureType===next?"selected":""}`} onClick={()=>void changeType(item.id,next)}>{next==="IP"?"I/P":next}</button>)}</div>}</div><button className="btn ghost mini" onClick={e=>{e.stopPropagation();setEditing(editing===item.id?null:item.id)}}>Edit</button></article>)}</div></div>}
function Detail({item,onBack}:{item:Saved;onBack:()=>void}){const options:[[string,string|undefined],[string,string|undefined],[string,string|undefined],[string,string|undefined]]=[["A",item.optionA],["B",item.optionB],["C",item.optionC],["D",item.optionD]];const correct=String(item.correctOption||"").trim().toUpperCase().replace(/[^A-D].*$/,"").charAt(0);const block=(label:string,value?:string)=>!String(value||"").trim()?null:<div className="myword-detail-block"><small>{label}</small><div>{value}</div></div>;return <div className="saved-parity-page saved-detail-page"><section className="saved-subhead mywords-detail-head"><button className="btn ghost saved-back" onClick={onBack}>← My Words</button><div><h1>{item.word}</h1><p>GPT enrichment · view only</p></div></section><article className="myword-detail-card"><div><div className="myword-detail-word">{item.word}</div>{(item.partOfSpeech||item.resolvedType)&&<div className="myword-detail-type">{item.partOfSpeech||item.resolvedType}</div>}</div>{block("Meaning",item.meaning||item.context)}{item.question&&<div className="myword-detail-block"><small>Practice question</small><div className="myword-detail-question">{item.question}</div><div className="myword-detail-options">{options.map(([key,text])=>text?<div key={key} className={`myword-detail-option ${correct===key?"correct":""}`}><b>{key}.</b> {text}</div>:null)}</div></div>}{block("Explanation",item.explanation)}{block("Example",item.example)}{block("Synonyms",item.synonyms)}{block("Antonyms",item.antonyms)}{block("Context",item.context)}</article></div>}
