"use client";

import { useEffect, useRef, useState } from "react";
import { gkRpc, isGkLocalSafe, pendingGkMutations } from "@/lib/gk-rpc";
import { loadFreshGkQuestions } from "@/lib/gk-session-freshness";
import { useAuthGuard } from "@/lib/use-auth";
import PauseSheet from "@/components/pause-sheet";
import { canAutoRestoreGkPaused, clearGkPaused, consumeGkReloadIntent, readGkPaused, saveGkPaused, type GkPausedAnswer } from "@/lib/gk-session";
import { makeDisplayOptions, restoreDisplayOptions, type DisplayOption } from "@/lib/options";
import type { GkLane,GkQuestion } from "@/lib/gk-types";
import QuestionText from "../question-text";
import styles from "../gk.module.css";
import polish from "../gk-lively-quiz.module.css";

type DisplayQuestion=GkQuestion&{displayOptions:DisplayOption[]};
type Answers=Record<string,GkPausedAnswer>;
type Meta={lane:GkLane;mode:string;title:string};
type DailyPayload={ok:boolean;sessionId:string;title:string;mode:string;position?:number;answers?:Answers;optionOrders?:Record<string,string[]>;questions:GkQuestion[]};
type ResumePayload={ok:boolean;session:null|{sessionId:string;title:string;mode:string;position:number;answers?:Answers;optionOrders?:Record<string,string[]>;params?:Record<string,unknown>;questions:GkQuestion[]}};

function makeSessionId(){return `gk-session-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
function hydrateQuestions(rows:GkQuestion[],orders?:Record<string,string[]>):DisplayQuestion[]{return (rows||[]).map(q=>{const order=orders?.[q.id];const displayOptions=order?restoreDisplayOptions(q.options||[],order):makeDisplayOptions(q.content_type,q.options||[],false,q.question);return {...q,displayOptions};});}
function optionOrders(rows:DisplayQuestion[]){return rows.reduce<Record<string,string[]>>((out,q)=>{out[q.id]=q.displayOptions.map(o=>o.canonicalKey);return out;},{});}
function RichText({text}:{text:string}){const parts=String(text||"").split(/(\*\*[^*]+\*\*)/g);return <>{parts.map((part,i)=>/^\*\*[^*]+\*\*$/.test(part)?<strong key={i}>{part.slice(2,-2)}</strong>:<span key={i}>{part}</span>)}</>}
function intelNumber(v:unknown){return Number(v||0);}
function FeedbackSection({title,text}:{title:string;text?:string}){if(!text)return null;const tone=title==="Related Facts"?polish.facts:title==="Exam Trap"?polish.trap:title==="Memory / Trick"?polish.memory:polish.explanation,icon=title==="Related Facts"?"↗":title==="Exam Trap"?"!":title==="Memory / Trick"?"✦":"💡";return <div className={`${polish.feedbackCard} ${tone}`}><h4><span className={polish.icon}>{icon}</span>{title}</h4><p><RichText text={text}/></p></div>}

export default function GkQuiz(){
 const ready=useAuthGuard();
 const submitLocks=useRef(new Set<string>());
 const[params,setParams]=useState<URLSearchParams|null>(null),[meta,setMeta]=useState<Meta>({lane:"MIXED",mode:"all",title:"GK Practice"}),[sessionId,setSessionId]=useState(""),[qs,setQs]=useState<DisplayQuestion[]>([]),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Answers>({}),[error,setError]=useState(false),[loading,setLoading]=useState(true),[noteOpen,setNoteOpen]=useState(false),[note,setNote]=useState(""),[pauseOpen,setPauseOpen]=useState(false),[intelOpen,setIntelOpen]=useState(false),[intel,setIntel]=useState<Record<string,unknown>|null>(null),[pending,setPending]=useState(0),[flagOpen,setFlagOpen]=useState(false),[flagReason,setFlagReason]=useState(""),[settling,setSettling]=useState(false);
 useEffect(()=>{if(ready)setParams(new URLSearchParams(window.location.search));},[ready]);
 useEffect(()=>{if(!ready||!params)return;const activeParams=params;let alive=true;async function load(){setLoading(true);setError(false);try{
   const stored=readGkPaused(),reloadIntent=consumeGkReloadIntent(),explicitLocalResume=activeParams.get("resume")==="1";
   if(stored&&(explicitLocalResume||canAutoRestoreGkPaused(stored,window.location.search,reloadIntent))){const rows=hydrateQuestions(stored.questions as GkQuestion[],stored.optionOrders);if(!alive)return;setSessionId(stored.sessionId);setMeta({lane:stored.lane,mode:stored.mode,title:stored.title});setQs(rows);setIndex(Math.min(stored.index,Math.max(0,rows.length-1)));setAnswers(stored.answers||{});setLoading(false);return;}
   if(activeParams.get("remoteResume")==="1"){const x=await gkRpc<ResumePayload>("gk_get_resume_session");if(x.session){const lane=(String(x.session.params?.lane||"MIXED").toUpperCase() as GkLane),rows=hydrateQuestions(x.session.questions,x.session.optionOrders);if(!alive)return;setSessionId(x.session.sessionId);setMeta({lane:["MAIN","RAPID","MIXED"].includes(lane)?lane:"MIXED",mode:x.session.mode||"practice",title:x.session.title||"GK Practice"});setQs(rows);setIndex(Math.min(Number(x.session.position||0),Math.max(0,rows.length-1)));setAnswers(x.session.answers||{});setLoading(false);return;}}
   const lane=((activeParams.get("lane")||"MIXED").toUpperCase() as GkLane),mode=activeParams.get("mode")||"all",title=activeParams.get("title")||"GK Practice",scope=activeParams.get("scope")==="1",rawCount=Number(activeParams.get("count")||20),count=Math.max(1,Math.min(scope?1000:100,rawCount));setMeta({lane,mode,title});
   if(activeParams.get("source")==="daily"&&!isGkLocalSafe()){const x=await gkRpc<DailyPayload>("gk_start_daily",{p_count:count});const rows=hydrateQuestions(x.questions,x.optionOrders);if(!alive)return;setSessionId(x.sessionId);setMeta({lane:"MIXED",mode:"daily",title:x.title||title});setQs(rows);setIndex(Math.min(Number(x.position||0),Math.max(0,rows.length-1)));setAnswers(x.answers||{});setLoading(false);return;}
   const concept=activeParams.get("concept")||"",lecture=activeParams.get("lecture")||"",teacherSeries=activeParams.get("teacherSeries")||"",part=Number(activeParams.get("part")||0);let rows:GkQuestion[];
   if(teacherSeries){const args={p_series_id:teacherSeries,p_lecture_key:lecture||null,p_mode:mode,p_count:count,p_lane:lane};rows=await loadFreshGkQuestions({name:"gk_get_teacher_batch",args,requested:count,load:expanded=>gkRpc<GkQuestion[]>("gk_get_teacher_batch",{...args,p_count:expanded})});}
   else if(lecture&&part>0&&lane!=="MIXED")rows=await gkRpc<GkQuestion[]>("gk_get_lecture_part_batch",{p_lecture_key:lecture,p_lane:lane,p_part:part,p_part_size:20});
   else if(concept){const args={p_concept_id:concept,p_mode:mode,p_count:count,p_lane:lane};rows=await loadFreshGkQuestions({name:"gk_get_concept_batch",args,requested:count,load:expanded=>gkRpc<GkQuestion[]>("gk_get_concept_batch",{...args,p_count:expanded})});}
   else if(scope){const args={p_mode:mode,p_count:count,p_lane:lane,p_subject:activeParams.get("subject")||null,p_topic:activeParams.get("topic")||null,p_lecture_key:lecture||null,p_library_key:activeParams.get("library")||null,p_ca_months:activeParams.get("months")?Number(activeParams.get("months")):null,p_ca_category:activeParams.get("caCategory")||null};rows=await loadFreshGkQuestions({name:"gk_get_scope_batch",args,requested:count,load:expanded=>gkRpc<GkQuestion[]>("gk_get_scope_batch",{...args,p_count:expanded})});}
   else{const args={p_mode:mode,p_count:count,p_lane:lane,p_subject:activeParams.get("subject")||null,p_topic:activeParams.get("topic")||null,p_lecture_key:lecture||null,p_library_key:activeParams.get("library")||null,p_demand_id:activeParams.get("demand")||null,p_ca_months:activeParams.get("months")?Number(activeParams.get("months")):null,p_ca_category:activeParams.get("caCategory")||null};rows=await loadFreshGkQuestions({name:"gk_get_batch",args,requested:count,load:expanded=>gkRpc<GkQuestion[]>("gk_get_batch",{...args,p_count:expanded})});}
   if(!alive)return;submitLocks.current.clear();setSessionId(makeSessionId());setQs(hydrateQuestions(rows));setIndex(0);setAnswers({});setLoading(false);
  }catch{if(alive){setError(true);setLoading(false);}}}void load();return()=>{alive=false};},[ready,params]);
 useEffect(()=>{if(!qs.length||loading||!sessionId||typeof window==="undefined")return;saveGkPaused({sessionId,title:meta.title,lane:meta.lane,mode:meta.mode,index,questions:qs,answers,optionOrders:optionOrders(qs),query:window.location.search,savedAt:Date.now()});},[qs,index,answers,loading,meta,sessionId]);
 useEffect(()=>{if(loading||typeof window==="undefined")return;const onBack=()=>{setPauseOpen(true);window.history.pushState({gkQuiz:true},"");};window.history.pushState({gkQuiz:true},"");window.addEventListener("popstate",onBack);return()=>window.removeEventListener("popstate",onBack);},[loading]);
 useEffect(()=>{const refresh=()=>setPending(pendingGkMutations());refresh();window.addEventListener("revision:gk-sync-pending",refresh as EventListener);window.addEventListener("revision:gk-mutation-durable",refresh as EventListener);return()=>{window.removeEventListener("revision:gk-sync-pending",refresh as EventListener);window.removeEventListener("revision:gk-mutation-durable",refresh as EventListener);};},[]);
 const q=qs[index],answered=q?answers[q.id]:undefined;
 useEffect(()=>{setNote(q?.state?.note||"");setNoteOpen(false);setIntelOpen(false);setIntel(null);setFlagOpen(false);setFlagReason(q?.state?.flagReason||"");if(!q?.id||!sessionId)return;void gkRpc("gk_record_exposure",{p_question_id:q.id,p_session_id:sessionId,p_mode:meta.mode});},[q?.id,sessionId,meta.mode]);
 async function answer(o:DisplayOption){if(!q||answered||submitLocks.current.has(q.id))return;const questionId=q.id;submitLocks.current.add(questionId);const canonical=o.canonicalKey,correct=canonical===q.correctKey,attemptId=`gk-${questionId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;setAnswers(a=>({...a,[questionId]:{selected:canonical,displaySelected:o.key,correct,correctKey:q.correctKey,attemptId,guessed:false}}));try{await gkRpc("gk_submit_answer",{p_question_id:questionId,p_selected_option:canonical,p_marked_review:!!q.state?.starred,p_attempt_id:attemptId,p_mode:meta.mode,p_session_id:sessionId});}catch{submitLocks.current.delete(questionId);setAnswers(a=>{const next={...a};delete next[questionId];return next;});setError(true);}}
 async function toggleStar(){if(!q)return;const next=!q.state?.starred;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,starred:next,starredAt:next?new Date().toISOString():null}}:v));try{await gkRpc("gk_set_starred",{p_question_id:q.id,p_starred:next});}catch{setError(true);}}
 async function toggleDifficult(){if(!q)return;const next=!q.state?.difficult;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,difficult:next}}:v));try{await gkRpc("gk_set_difficult",{p_question_id:q.id,p_difficult:next});}catch{setError(true);}}
 async function markGuessed(){if(!q||!answered?.attemptId||answered.guessed)return;setAnswers(a=>({...a,[q.id]:{...a[q.id],guessed:true}}));setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,guessedAttempts:Number(v.state?.guessedAttempts||0)+1,unconfirmedGuess:true}}:v));try{await gkRpc("gk_mark_guessed",{p_question_id:q.id,p_attempt_id:answered.attemptId,p_guessed:true});}catch{setError(true);}}
 async function clearFlag(){if(!q)return;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,flagged:false,flagReason:""}}:v));try{await gkRpc("gk_set_flag",{p_question_id:q.id,p_active:false,p_reason:"",p_note:""});}catch{setError(true);}}
 async function saveFlag(){if(!q)return;const reason=flagReason.trim()||"Review requested";setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,flagged:true,flagReason:reason}}:v));setFlagOpen(false);try{await gkRpc("gk_set_flag",{p_question_id:q.id,p_active:true,p_reason:reason,p_note:""});}catch{setError(true);}}
 async function saveNote(){if(!q)return;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,note}}:v));setNoteOpen(false);try{await gkRpc("gk_save_note",{p_question_id:q.id,p_note:note});}catch{setError(true);}}
 async function openIntelligence(){setIntelOpen(true);if(!q||intel)return;try{setIntel(await gkRpc<Record<string,unknown>>("gk_get_question_intelligence",{p_question_id:q.id,p_session_id:sessionId}));}catch{setError(true);}}
 function sessionPayload(completed=false){return {p_session_id:sessionId,p_title:meta.title,p_mode:meta.mode,p_position:index,p_answers:answers,p_option_orders:optionOrders(qs),p_question_ids:qs.map(x=>x.id),p_completed:completed,p_params:{lane:meta.lane,query:typeof window!=="undefined"?window.location.search:""}};}
 function exitPaused(){if(qs.length&&typeof window!=="undefined")saveGkPaused({sessionId,title:meta.title,lane:meta.lane,mode:meta.mode,index,questions:qs,answers,optionOrders:optionOrders(qs),query:window.location.search,savedAt:Date.now()});void gkRpc("gk_save_session",sessionPayload(false));window.location.href="/gk?tab=home";}
 function go(next:number){const target=Math.max(0,Math.min(qs.length-1,next));if(target===index)return;setSettling(true);requestAnimationFrame(()=>{setIndex(target);window.scrollTo({top:0,behavior:"instant"});window.setTimeout(()=>setSettling(false),90);});}
 function finish(){void gkRpc("gk_save_session",sessionPayload(true));clearGkPaused();window.location.href="/gk?tab=home";}
 if(!ready||!params)return <main className={styles.quiz}><div className="loading-copy">Checking session…</div></main>;
 if(loading)return <main className={styles.quiz}><header className={styles.quizHead}><div className={styles.quizHeadRow}><div className={styles.quizTitle}><b>{meta.title}</b><div className={styles.quizCounter}>Preparing your revision set…</div></div></div><div className={styles.progress}><i style={{width:"18%"}}/></div></header><div className={styles.loadingCard}>Loading questions…</div></main>;
 if(!q)return <main className={styles.quiz}><header className={styles.quizHead}><button className={styles.back} onClick={()=>window.location.href="/gk?tab=practice"}>← Back</button></header><div className={styles.notice}>{error?"Quiz could not load. Reopen this route to retry.":"No eligible questions are available for this route right now."}</div></main>;
 const pct=((index+1)/Math.max(1,qs.length))*100,last=index===qs.length-1,state=q.state||{},correctDisplay=answered?(q.displayOptions.find(o=>o.canonicalKey===answered.correctKey)?.key||answered.correctKey):"",source=[q.source_label,q.source_page?`Page ${q.source_page}`:""].filter(Boolean).join(" · ");
 return <main className={styles.quiz}>
  <header className={styles.quizHead}><div className={styles.quizHeadRow}><div className={styles.quizTitle}><b>{meta.title}</b><div className={styles.quizCounter}>Question {index+1} of {qs.length}</div></div></div><div className={styles.progress}><i style={{width:`${pct}%`}}/></div><div className={styles.quizMeta}>{q.subject&&<span className={styles.metaTag}>{q.subject}</span>}{q.topic&&<span className={styles.metaTag}>{q.topic}</span>}<button className={styles.infoTag} onClick={()=>void openIntelligence()}>{String(state.learningState||state.status||"New")} ⓘ</button></div></header>
  {(error||pending>0||isGkLocalSafe())&&<div className={styles.notice}>{isGkLocalSafe()?"Local Safe · production learning data will not be changed.":pending>0?`${pending} save${pending===1?"":"s"} pending · retrying automatically.`:"A save will retry automatically."}</div>}
  <div className={`${polish.stage} ${settling?polish.stageSettling:""}`}>
   <section className={styles.question}><QuestionText text={q.question}/></section>
   <div className={styles.options}>{q.displayOptions.map(o=>{const correct=!!answered&&o.canonicalKey===answered.correctKey,wrong=!!answered&&o.key===answered.displaySelected&&!answered.correct;return <button key={o.key} className={`${styles.option} ${correct?styles.correct:""} ${wrong?styles.wrong:""}`} onClick={()=>answer(o)} disabled={!!answered}><span className={styles.optionKey}>{o.key}</span><span>{o.text}</span></button>})}</div>
   {answered&&<section className={styles.answerPanel}><div className={styles.feedbackStatus}>{answered.correct?"✓ Correct":"✕ Incorrect"}{correctDisplay?` · Correct option ${correctDisplay}`:""}</div><FeedbackSection title="Explanation" text={q.explanation}/><FeedbackSection title="Related Facts" text={q.related_fact}/><FeedbackSection title="Exam Trap" text={q.exam_trap}/><FeedbackSection title="Memory / Trick" text={q.trick}/>{source&&<div className={polish.sourceCard}><h4>Source</h4><div>{source}</div></div>}<div className={styles.explanationNoteRow}><button className={`${styles.noteAfter} ${state.note?styles.noteAfterActive:""}`} onClick={()=>setNoteOpen(true)}>📝 {state.note?"Edit Note":"Add Note"}</button></div><div className={styles.saveStatus}>{isGkLocalSafe()?"Local Safe · answer kept out of production learning data":pending>0?"Save pending · retrying automatically":"Saved / sync clear"}</div><button className={`${styles.guessAfter} ${answered.guessed||state.unconfirmedGuess?styles.guessAfterActive:""}`} onClick={()=>void markGuessed()} disabled={!!answered.guessed}>{answered.guessed||state.unconfirmedGuess?"✓ Marked as guessed":"? I guessed this"}</button><button className={styles.intelligenceButton} onClick={()=>void openIntelligence()}>ⓘ Question Intelligence</button></section>}
  </div>
  {intelOpen&&<div className={styles.modal} onClick={e=>{if(e.target===e.currentTarget)setIntelOpen(false)}}><div className={styles.sheet}><h3>{String(state.learningState||state.status||"New")} ⓘ</h3><div className={styles.simpleList}><div className={styles.listCard}><span><b>Seen {intelNumber(state.exposureCount)}× · Attempted {intelNumber(state.attempts)}×</b><small>{intelNumber(state.retentionAttempts)} spaced recalls · {intelNumber(state.retentionAccuracy)}% retention</small></span></div><div className={styles.listCard}><span><b>Evidence state</b><small>{state.due?"Due now":"Not due"} · {state.difficult?"Difficult marked":"Not Difficult"} · {state.starred?"Starred":"Not Starred"} · {state.unconfirmedGuess?"Unresolved guess":"No unresolved guess"}</small></span></div><div className={styles.listCard}><span><b>Why selected</b><small>{String(intel?.selectionReason||"Practice route")}</small></span></div>{q.concept_id&&<div className={styles.listCard}><span><b>Concept</b><small>{q.concept_id}</small></span></div>}</div><button className={styles.sheetClose} onClick={()=>setIntelOpen(false)}>Close</button></div></div>}
  {noteOpen&&<div className={styles.modal} onClick={e=>{if(e.target===e.currentTarget)setNoteOpen(false)}}><div className={`${styles.sheet} ${styles.noteSheet}`}><h3>📝 Personal Note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Write the exact fact you want to remember"/><button onClick={()=>void saveNote()}>Save Note</button><button className={styles.sheetClose} onClick={()=>setNoteOpen(false)}>Cancel</button></div></div>}
  {flagOpen&&<div className={styles.modal} onClick={e=>{if(e.target===e.currentTarget)setFlagOpen(false)}}><div className={`${styles.sheet} ${styles.noteSheet}`}><h3>⚑ Flag question</h3><textarea value={flagReason} onChange={e=>setFlagReason(e.target.value)} placeholder="Wrong answer/key? · Explanation unclear · Outdated fact · Formatting/diagram issue · Other"/><button onClick={()=>void saveFlag()}>Save Flag</button><button className={styles.sheetClose} onClick={()=>setFlagOpen(false)}>Cancel</button></div></div>}
  <footer className={styles.quizDock}><div className={styles.dockTools}><button className={`${styles.dockTool} ${state.starred?styles.dockToolActive:""}`} onClick={()=>void toggleStar()}>{state.starred?"★ Starred":"☆ Star"}</button><button className={`${styles.dockTool} ${state.flagged?styles.dockToolActive:""}`} onClick={()=>state.flagged?void clearFlag():setFlagOpen(true)}>⚑ Flag</button><button className={`${styles.dockTool} ${state.difficult?styles.dockToolActive:""}`} onClick={()=>void toggleDifficult()}>◆ Difficult</button><button className={styles.dockTool} onClick={()=>setPauseOpen(true)}>Ⅱ Pause</button></div><div className={styles.dockNav}><button onClick={()=>go(index-1)} disabled={index===0}>← Previous</button>{last?<button onClick={finish}>Finish</button>:<button onClick={()=>go(index+1)}>Next →</button>}</div></footer>
  <PauseSheet open={pauseOpen} onSave={exitPaused} onCancel={()=>setPauseOpen(false)}/>
 </main>;
}
