"use client";

import { useEffect, useState } from "react";
import { gkRpc, isGkLocalSafe, pendingGkMutations } from "@/lib/gk-rpc";
import { useAuthGuard } from "@/lib/use-auth";
import PauseSheet from "@/components/pause-sheet";
import { clearGkPaused, readGkPaused, saveGkPaused, type GkPausedAnswer } from "@/lib/gk-session";
import { makeDisplayOptions, restoreDisplayOptions, type DisplayOption } from "@/lib/options";
import type { GkLane,GkQuestion } from "@/lib/gk-types";
import styles from "../gk.module.css";

type DisplayQuestion=GkQuestion&{displayOptions:DisplayOption[]};
type Answers=Record<string,GkPausedAnswer>;
type Meta={lane:GkLane;mode:string;title:string};
type DailyPayload={ok:boolean;sessionId:string;title:string;mode:string;position?:number;answers?:Answers;optionOrders?:Record<string,string[]>;questions:GkQuestion[]};
type ResumePayload={ok:boolean;session:null|{sessionId:string;title:string;mode:string;position:number;answers?:Answers;optionOrders?:Record<string,string[]>;params?:Record<string,unknown>;questions:GkQuestion[]}};

function makeSessionId(){return `gk-session-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
function hydrateQuestions(rows:GkQuestion[],orders?:Record<string,string[]>):DisplayQuestion[]{return (rows||[]).map(q=>{const order=orders?.[q.id];const displayOptions=order?restoreDisplayOptions(q.options||[],order):makeDisplayOptions(q.content_type,q.options||[],false,q.question);return {...q,displayOptions};});}
function optionOrders(rows:DisplayQuestion[]){return rows.reduce<Record<string,string[]>>((out,q)=>{out[q.id]=q.displayOptions.map(o=>o.canonicalKey);return out;},{});}
function RichText({text}:{text:string}){const parts=String(text||"").split(/(\*\*[^*]+\*\*)/g);return <>{parts.map((part,i)=>/^\*\*[^*]+\*\*$/.test(part)?<strong key={i}>{part.slice(2,-2)}</strong>:<span key={i}>{part}</span>)}</>}
function QuestionText({text}:{text:string}){const raw=String(text||"");const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let rendered=lines;if(lines.length<=1){const t=raw.trim();const hits=[...t.matchAll(/(?:^|\s)(\d+)\.\s+/g)];const nums=hits.map(x=>Number(x[1]));const sequential=hits.length>=2&&Number(hits[0].index||0)===0&&nums[0]===1&&nums.every((x,i)=>i===0||x===nums[i-1]+1);if(sequential)rendered=t.replace(/\s+(?=\d+\.\s)/g,"\n").split("\n");}
 return <>{rendered.map((line,i)=>{const hit=line.match(/^(\d+\.)(\s*)(.*)$/);return hit?<span className={styles.statement} key={i}><strong>{hit[1]}</strong><span>{hit[3]}</span></span>:<span className={rendered.length>1?styles.statement:undefined} key={i}>{line}</span>;})}</>}
function intelNumber(v:unknown){return Number(v||0);}

export default function GkQuiz(){
 const ready=useAuthGuard();const[params,setParams]=useState<URLSearchParams|null>(null);const[meta,setMeta]=useState<Meta>({lane:"MIXED",mode:"all",title:"GK Practice"});const[sessionId,setSessionId]=useState("");const[qs,setQs]=useState<DisplayQuestion[]>([]);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Answers>({});const[error,setError]=useState(false);const[loading,setLoading]=useState(true);const[noteOpen,setNoteOpen]=useState(false);const[note,setNote]=useState("");const[pauseOpen,setPauseOpen]=useState(false);const[intel,setIntel]=useState<Record<string,unknown>|null>(null);const[pending,setPending]=useState(0);
 useEffect(()=>{if(ready)setParams(new URLSearchParams(window.location.search));},[ready]);
 useEffect(()=>{if(!ready||!params)return;const activeParams=params;let alive=true;async function load(){setLoading(true);try{
   const stored=readGkPaused();if(activeParams.get("resume")==="1"&&stored){const rows=hydrateQuestions(stored.questions as GkQuestion[],stored.optionOrders);if(!alive)return;setSessionId(stored.sessionId);setMeta({lane:stored.lane,mode:stored.mode,title:stored.title});setQs(rows);setIndex(Math.min(stored.index,Math.max(0,rows.length-1)));setAnswers(stored.answers||{});setLoading(false);return;}
   if(activeParams.get("remoteResume")==="1"){const x=await gkRpc<ResumePayload>("gk_get_resume_session");if(x.session){const lane=(String(x.session.params?.lane||"MIXED").toUpperCase() as GkLane);const rows=hydrateQuestions(x.session.questions,x.session.optionOrders);if(!alive)return;setSessionId(x.session.sessionId);setMeta({lane:["MAIN","RAPID","MIXED"].includes(lane)?lane:"MIXED",mode:x.session.mode||"practice",title:x.session.title||"GK Practice"});setQs(rows);setIndex(Math.min(Number(x.session.position||0),Math.max(0,rows.length-1)));setAnswers(x.session.answers||{});setLoading(false);return;}}
   const lane=((activeParams.get("lane")||"MIXED").toUpperCase() as GkLane);const mode=activeParams.get("mode")||"all";const title=activeParams.get("title")||"GK Practice";const count=Math.max(1,Math.min(100,Number(activeParams.get("count")||20)));setMeta({lane,mode,title});
   if(activeParams.get("source")==="daily"&&!isGkLocalSafe()){const x=await gkRpc<DailyPayload>("gk_start_daily",{p_count:count});const rows=hydrateQuestions(x.questions,x.optionOrders);if(!alive)return;setSessionId(x.sessionId);setMeta({lane:"MIXED",mode:"daily",title:x.title||title});setQs(rows);setIndex(Math.min(Number(x.position||0),Math.max(0,rows.length-1)));setAnswers(x.answers||{});setLoading(false);return;}
   const concept=activeParams.get("concept")||"";
   const rows=concept
     ? await gkRpc<GkQuestion[]>("gk_get_concept_batch",{p_concept_id:concept,p_mode:mode,p_count:count,p_lane:lane})
     : await gkRpc<GkQuestion[]>("gk_get_batch",{p_mode:mode,p_count:count,p_lane:lane,p_subject:activeParams.get("subject")||null,p_topic:activeParams.get("topic")||null,p_lecture_key:activeParams.get("lecture")||null,p_library_key:activeParams.get("library")||null,p_demand_id:activeParams.get("demand")||null,p_ca_months:activeParams.get("months")?Number(activeParams.get("months")):null,p_ca_category:activeParams.get("caCategory")||null});
   if(!alive)return;setSessionId(makeSessionId());setQs(hydrateQuestions(rows));setIndex(0);setAnswers({});setLoading(false);
 }catch{if(alive){setError(true);setLoading(false);}}}void load();return()=>{alive=false};},[ready,params]);
 useEffect(()=>{if(!qs.length||loading||!sessionId||typeof window==="undefined")return;saveGkPaused({sessionId,title:meta.title,lane:meta.lane,mode:meta.mode,index,questions:qs,answers,optionOrders:optionOrders(qs),query:window.location.search,savedAt:Date.now()});},[qs,index,answers,loading,meta,sessionId]);
 useEffect(()=>{if(loading||typeof window==="undefined")return;const onBack=()=>{setPauseOpen(true);window.history.pushState({gkQuiz:true},"");};window.history.pushState({gkQuiz:true},"");window.addEventListener("popstate",onBack);return()=>window.removeEventListener("popstate",onBack);},[loading]);
 useEffect(()=>{const refresh=()=>setPending(pendingGkMutations());refresh();window.addEventListener("revision:gk-sync-pending",refresh as EventListener);window.addEventListener("revision:gk-mutation-durable",refresh as EventListener);return()=>{window.removeEventListener("revision:gk-sync-pending",refresh as EventListener);window.removeEventListener("revision:gk-mutation-durable",refresh as EventListener);};},[]);
 const q=qs[index],answered=q?answers[q.id]:undefined;
 useEffect(()=>{setNote(q?.state?.note||"");setNoteOpen(false);setIntel(null);if(!q?.id||!sessionId)return;void gkRpc("gk_record_exposure",{p_question_id:q.id,p_session_id:sessionId,p_mode:meta.mode});},[q?.id,sessionId,meta.mode]);
 async function answer(o:DisplayOption){if(!q||answered)return;const canonical=o.canonicalKey;const correct=canonical===q.correctKey;const attemptId=`gk-${q.id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;setAnswers(a=>({...a,[q.id]:{selected:canonical,displaySelected:o.key,correct,correctKey:q.correctKey,attemptId,guessed:false}}));try{await gkRpc("gk_submit_answer",{p_question_id:q.id,p_selected_option:canonical,p_marked_review:!!q.state?.starred,p_attempt_id:attemptId,p_mode:meta.mode,p_session_id:sessionId});}catch{setError(true);}}
 async function toggleStar(){if(!q)return;const next=!q.state?.starred;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,starred:next,starredAt:next?new Date().toISOString():null}}:v));try{await gkRpc("gk_set_starred",{p_question_id:q.id,p_starred:next});}catch{setError(true);}}
 async function toggleDifficult(){if(!q)return;const next=!q.state?.difficult;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,difficult:next}}:v));try{await gkRpc("gk_set_difficult",{p_question_id:q.id,p_difficult:next});}catch{setError(true);}}
 async function toggleGuess(){if(!q||!answered?.correct||!answered.attemptId)return;const next=!answered.guessed;setAnswers(a=>({...a,[q.id]:{...a[q.id],guessed:next}}));setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,unconfirmedGuess:next||v.state?.unconfirmedGuess,guessedAttempts:Math.max(0,Number(v.state?.guessedAttempts||0)+(next?1:-1))}}:v));try{await gkRpc("gk_mark_guessed",{p_question_id:q.id,p_attempt_id:answered.attemptId,p_guessed:next});}catch{setError(true);}}
 async function toggleFlag(){if(!q)return;const next=!q.state?.flagged;const reason=next?(q.state?.flagReason||"Review requested"):"";setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,flagged:next,flagReason:reason}}:v));try{await gkRpc("gk_set_flag",{p_question_id:q.id,p_active:next,p_reason:reason,p_note:""});}catch{setError(true);}}
 async function saveNote(){if(!q)return;setQs(x=>x.map(v=>v.id===q.id?{...v,state:{...v.state,note}}:v));setNoteOpen(false);try{await gkRpc("gk_save_note",{p_question_id:q.id,p_note:note});}catch{setError(true);}}
 async function loadIntelligence(){if(!q||intel)return;try{const x=await gkRpc<Record<string,unknown>>("gk_get_question_intelligence",{p_question_id:q.id,p_session_id:sessionId});setIntel(x);}catch{setError(true);}}
 function sessionPayload(completed=false){return {p_session_id:sessionId,p_title:meta.title,p_mode:meta.mode,p_position:index,p_answers:answers,p_option_orders:optionOrders(qs),p_question_ids:qs.map(x=>x.id),p_completed:completed,p_params:{lane:meta.lane,query:typeof window!=="undefined"?window.location.search:""}};}
 function exitPaused(){if(qs.length&&typeof window!=="undefined")saveGkPaused({sessionId,title:meta.title,lane:meta.lane,mode:meta.mode,index,questions:qs,answers,optionOrders:optionOrders(qs),query:window.location.search,savedAt:Date.now()});void gkRpc("gk_save_session",sessionPayload(false));window.location.href="/gk?tab=home";}
 function go(next:number){setIndex(Math.max(0,Math.min(qs.length-1,next)));window.scrollTo({top:0,behavior:"smooth"});}
 function finish(){void gkRpc("gk_save_session",sessionPayload(true));clearGkPaused();window.location.href="/gk?tab=home";}
 if(!ready||!params)return <main className={styles.quiz}><div className="loading-copy">Checking session…</div></main>;
 if(loading)return <main className={styles.quiz}><div className="loading-copy">Loading {meta.title}…</div></main>;
 if(!q)return <main className={styles.quiz}><div className={styles.quizTop}><button className={styles.back} onClick={()=>window.location.href="/gk?tab=practice"}>‹ GK</button></div><div className={styles.notice}>{error?"GK questions couldn’t load. Reopen this route to retry.":"No eligible questions are available for this route right now."}</div></main>;
 const pct=((index+1)/Math.max(1,qs.length))*100,last=index===qs.length-1;const state=q.state||{};
 return <main className={styles.quiz}>
  <header className={styles.quizTop}><div className={styles.quizTopLine}><button className={styles.back} onClick={()=>setPauseOpen(true)}>‹ GK</button><strong>{meta.title}</strong><span>{index+1}/{qs.length}</span></div><div className={styles.progress}><i style={{width:`${pct}%`}}/></div></header>
  {(error||pending>0||isGkLocalSafe())&&<div className={styles.notice}>{isGkLocalSafe()?"Local Safe: this quiz is read-only against production learning data.":pending>0?`${pending} GK save${pending===1?"":"s"} pending sync. You can keep studying.`:"A GK save will retry automatically."}</div>}
  <div className={styles.context}><span className={styles.chip}>{q.content_lane||meta.lane}</span>{q.subject&&<span className={styles.chip}>{q.subject}</span>}{q.topic&&<span className={styles.chip}>{q.topic}</span>}{q.lecture_no!==undefined&&q.lecture_no!==null&&<span className={styles.chip}>Lecture {q.lecture_no}</span>}<span className={styles.chip}>{q.id}</span><span className={styles.chip}>{state.learningState||state.status||"New"}</span>{state.due&&<span className={styles.chip}>Due</span>}</div>
  <section className={styles.question}><QuestionText text={q.question}/></section>
  <div className={styles.options}>{q.displayOptions.map(o=>{const correct=!!answered&&o.canonicalKey===answered.correctKey;const wrong=!!answered&&o.key===answered.displaySelected&&!answered.correct;return <button key={o.key} className={`${styles.option} ${correct?styles.correct:""} ${wrong?styles.wrong:""}`} onClick={()=>answer(o)} disabled={!!answered}><span className={styles.optionKey}>{o.key}</span><span>{o.text}</span></button>})}</div>
  {answered&&<><section className={styles.explain}><h3>{answered.correct?"Correct · lock the fact":"Review · correct the recall"}</h3>{q.explanation&&<p><RichText text={q.explanation}/></p>}{q.related_fact&&<p><span className={styles.explainLabel}>Related Facts: </span><RichText text={q.related_fact}/></p>}{q.exam_trap&&<p><span className={styles.explainLabel}>Exam Trap: </span><RichText text={q.exam_trap}/></p>}{q.trick&&<p><span className={styles.explainLabel}>Memory / Trick: </span><RichText text={q.trick}/></p>}</section>
   <div className={styles.tools}><button className={`${styles.tool} ${state.starred?styles.activeTool:""}`} onClick={toggleStar}>★ Star</button><button className={`${styles.tool} ${state.difficult?styles.activeTool:""}`} onClick={toggleDifficult}>◆ Difficult</button><button className={`${styles.tool} ${answered.guessed?styles.activeTool:""}`} onClick={toggleGuess} disabled={!answered.correct}>? Guessed</button><button className={`${styles.tool} ${state.flagged?styles.activeTool:""}`} onClick={toggleFlag}>⚑ Flag</button><button className={`${styles.tool} ${(state.note||note)?styles.activeTool:""}`} onClick={()=>setNoteOpen(x=>!x)}>▤ Note</button></div>
   {noteOpen&&<section className={styles.explain}><h3>Personal note</h3><textarea className={styles.note} value={note} onChange={e=>setNote(e.target.value)} placeholder="Write the exact fact you want to remember"/><button className="btn primary" onClick={saveNote}>Save note</button></section>}
   <details className={styles.intelligence} onToggle={e=>{if((e.currentTarget as HTMLDetailsElement).open)void loadIntelligence()}}><summary>ⓘ Question Intelligence</summary><div className={styles.intelligenceBody}><div className={styles.intelItem}><b>{String(state.learningState||state.status||"New")}</b><span>Learning state</span></div><div className={styles.intelItem}><b>{intelNumber(state.attempts)}</b><span>Attempts</span></div><div className={styles.intelItem}><b>{intelNumber(state.retentionAttempts)}</b><span>Retention attempts</span></div><div className={styles.intelItem}><b>{intelNumber(state.retentionAccuracy)}%</b><span>Retention accuracy</span></div><div className={styles.intelItem}><b>{intelNumber(state.exposureCount)}</b><span>Exposure count</span></div><div className={styles.intelItem}><b>{state.unconfirmedGuess?"Unconfirmed":"Clear"}</b><span>Guess status</span></div>{intel&&<><div className={styles.intelItem}><b>{String(intel.selectionReason||"—")}</b><span>Selection reason</span></div><div className={styles.intelItem}><b>{q.concept_id||"—"}</b><span>Concept</span></div></>}</div></details>
  </>}
  <footer className={styles.dock}><div className={styles.dockInner}><button onClick={()=>go(index-1)} disabled={index===0}>‹ Previous</button><button onClick={()=>setPauseOpen(true)}>Ⅱ Pause</button>{last?<button onClick={finish}>Finish ✓</button>:<button onClick={()=>go(index+1)}>Next ›</button>}</div></footer>
  <PauseSheet open={pauseOpen} onSave={exitPaused} onCancel={()=>setPauseOpen(false)}/>
 </main>;
}