"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { LearnerRow, OverviewCard, PageHeader } from "@/components/learner-ui";
import { confusionLabel, learnerGroup, learnerName } from "@/lib/learner-label";
import { learnerErrorMessage, rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";

type Activity={id:number;type:string;title:string;detail?:string;questionId?:string;at:string};
type Signals={today_activity?:{count:number;items:Activity[]}};
type Focus={questionId:string;name:string;skillFamily?:string;nextReview?:string};
type Confusion={confusionId:string;primaryName:string;relatedName:string;primaryQuestionId?:string;relatedQuestionId?:string};
type Hub={summary:{dueNow:number;confusions:number};confusions:Confusion[];needLearning:Focus[];transferChecks:Focus[];retentionChecks:Focus[];recovered:{name:string}[]};
type Label={questionId:string;displayName:string;topic?:string;conceptName?:string};
type Row={key:string;title:string;detail:string;status?:string;group:string;href?:string;tone:"fix"|"soon"|"good"|"later"};
type Section="today"|"fix"|"soon"|"good"|"later";
const due=(d?:string)=>!d||new Date(d).getTime()<=Date.now();
const href=(id:string,title:string)=>`/english/targeted?question=${encodeURIComponent(id)}&title=${encodeURIComponent(title)}`;

export default function LearningInsightsPage(){
 const ready=useAuthGuard(),[hub,setHub]=useState<Hub|null>(null),[signals,setSignals]=useState<Signals|null>(null),[labels,setLabels]=useState<Record<string,Label>>({}),[section,setSection]=useState<Section|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!ready)return;let alive=true;Promise.all([rpc<Hub>("english_get_targeted_mastery"),rpc<Signals>("english_get_learning_signal_summary")]).then(async([h,s])=>{if(!alive)return;setHub(h);setSignals(s);const ids=[...h.needLearning,...h.transferChecks,...h.retentionChecks].map(x=>x.questionId).concat(...h.confusions.map(x=>[x.primaryQuestionId,x.relatedQuestionId].filter(Boolean) as string[]),...(s.today_activity?.items||[]).map(x=>x.questionId||"")).filter(Boolean);if(ids.length)try{const out=await rpc<{items:Label[]}>("english_get_question_labels",{p_question_ids:[...new Set(ids)].slice(0,120)});if(alive)setLabels(Object.fromEntries((out.items||[]).map(x=>[x.questionId,x])))}catch{}}).catch((e:any)=>alive&&setError(learnerErrorMessage(e,"Could not load Learning Insights."))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[ready]);
 const rows=useMemo(()=>{if(!hub)return {fix:[] as Row[],soon:[] as Row[],good:[] as Row[],later:[] as Row[],today:[] as Row[]};const named=(f:Focus)=>learnerName(labels[f.questionId],f.name),focus=(items:Focus[],kind:Exclude<Section,"today">,detail:string,status?:string):Row[]=>items.map(f=>({key:`${kind}-${f.questionId}`,title:named(f),detail,status,group:learnerGroup(labels[f.questionId]?.topic||f.skillFamily),href:href(f.questionId,named(f)),tone:kind}));const conf:Row[]=hub.confusions.map(c=>({key:`c-${c.confusionId}`,title:confusionLabel(c.primaryName,c.relatedName),detail:"You flagged this confusion",status:"Ready now",group:"Confusions",href:`/english/targeted?confusion=${encodeURIComponent(c.confusionId)}`,tone:"fix" as const}));return {fix:[...conf,...focus(hub.transferChecks.filter(x=>due(x.nextReview)),"fix","Fresh understanding check","Ready now"),...focus(hub.retentionChecks.filter(x=>due(x.nextReview)),"fix","Spaced recall is ready","Ready now"),...focus(hub.needLearning.filter(x=>due(x.nextReview)),"fix","Focused repair from recent evidence","Ready now")],soon:focus(hub.transferChecks.filter(x=>x.nextReview&&!due(x.nextReview)),"soon","A fresh check is coming up"),good:hub.recovered.map((x,i)=>({key:`good-${i}-${x.name}`,title:learnerName(undefined,x.name),detail:"Recent evidence is better than before",group:"Improving",tone:"good" as const})),later:focus(hub.retentionChecks.filter(x=>x.nextReview&&!due(x.nextReview)),"later","Fresh proof completed"),today:(signals?.today_activity?.items||[]).map(x=>({key:`today-${x.id}`,title:learnerName(labels[x.questionId||""],cleanTitle(x.title)),detail:activityText(x),status:time(x.at),group:"Today",href:x.questionId?href(x.questionId,learnerName(labels[x.questionId],x.title)):undefined,tone:"soon" as const}))}},[hub,signals,labels]);
 if(!ready)return null;if(section)return <Category section={section} rows={rows[section]} onBack={()=>setSection(null)}/>;
 return <main className="top-level-parity learner-rebuild-page"><PageHeader back={<Link href="/english/revision" className="back-link">← Revision</Link>} eyebrow="Your study plan" title="Learning Insights" subtitle="See what needs attention and why."/>{error&&<div className="error-box">{error}</div>}{loading?<div className="loading-copy">Refreshing your learning plan…</div>:<><div className="learner-overview-stack"><OverviewCard tone="neutral" title="Today" subtitle="See what changed in your learning plan." count={signals?.today_activity?.count??0} onClick={()=>setSection("today")}/><OverviewCard tone="fix" title="Fix Now" subtitle="Mistakes, confusion and uncertain answers." count={rows.fix.length} onClick={()=>setSection("fix")}/><OverviewCard tone="soon" title="Check Soon" subtitle="Fresh checks that will strengthen recall." count={rows.soon.length} onClick={()=>setSection("soon")}/><OverviewCard tone="good" title="Improving" subtitle="Concepts with stronger recent evidence." count={rows.good.length} onClick={()=>setSection("good")}/><OverviewCard tone="later" title="Scheduled for Later" subtitle="Spaced recall waiting for the right time." count={rows.later.length} onClick={()=>setSection("later")}/></div><details className="insights-how-details learner-section"><summary><span><b>How your learning plan works</b><small>Why something appears now, soon, or later.</small></span></summary><div className="insights-how-copy"><p><b>Fix Now</b> prioritises mistakes, uncertainty and confusions.</p><p><b>Check Soon</b> asks for independent proof of understanding.</p><p><b>Scheduled for Later</b> protects retention by waiting before testing again.</p></div></details></>}</main>;
}
function Category({section,rows,onBack}:{section:Section;rows:Row[];onBack:()=>void}){const meta:Record<Section,[string,string]>={today:["Today","What changed in your learning plan."],fix:["Fix Now","Items that can improve your score now."],soon:["Check Soon","Fresh checks coming up."],good:["Improving","Recent evidence is better than before."],later:["Scheduled for Later","Checks waiting for the right recall time."]};const [title,subtitle]=meta[section],groups=rows.reduce<Record<string,Row[]>>((all,row)=>{(all[row.group]??=[]).push(row);return all},{});return <main className="top-level-parity learner-rebuild-page"><button className="learner-back" type="button" onClick={onBack}>← Learning Insights</button><PageHeader title={title} subtitle={subtitle}/>{rows.length?Object.entries(groups).map(([group,items])=><section className="learner-section" key={group}><div className="learner-section-head"><div><h2>{group}</h2><p>{items.length} item{items.length===1?"":"s"}</p></div></div><div className="learner-row-list">{items.map(row=><LearnerRow key={row.key} title={row.title} subtitle={row.detail} status={row.status} tone={row.tone} onClick={row.href?()=>location.assign(row.href!):undefined}/>)}</div></section>):<div className="learner-empty">Nothing is here right now.</div>}</main>}
function cleanTitle(value:string){return String(value||"Learning update").replace(/background analysis|targeted|route event|semantic processing/gi,"").replace(/\s+→\s+/g," ").trim()||"Learning update"}
function activityText(x:Activity){if(x.type.includes("guess"))return"You marked this as guessed. A fresh understanding check was added.";if(x.type.includes("confusion"))return"You flagged a confusion for focused practice.";return String(x.detail||"Your learning plan was updated.").replace(/background analysis|targeted|route event|semantic processing/gi,"learning plan")}
function time(value:string){const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):undefined}
