"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import QuizRunner from "@/components/quiz-runner";
import { EnglishLoading } from "@/components/english-frame";
import { LearnerRow, OverviewCard, PageHeader } from "@/components/learner-ui";
import { confusionLabel, learnerGroup, learnerName } from "@/lib/learner-label";
import { learnerErrorMessage, rpc } from "@/lib/supabase";
import { subscribeTargetedDurability, targetedLiveRpc, targetedSessionRpc } from "@/lib/targeted-reliability";
import { useAuthGuard } from "@/lib/use-auth";

type Summary={dueNow:number;confusions:number};
type Confusion={confusionId:string;primaryName:string;relatedName:string;primaryQuestionId?:string;relatedQuestionId?:string;note?:string};
type FocusRow={questionId:string;name:string;skillFamily?:string;nextReview?:string};
type Hub={ok:boolean;summary:Summary;confusions:Confusion[];needLearning:FocusRow[];transferChecks:FocusRow[];retentionChecks:FocusRow[]};
type QuestionLabel={questionId:string;displayName:string;topic?:string;conceptName?:string};
type LabelsResponse={items:QuestionLabel[]};
type Kind="due_now"|"confusion"|"need_learning"|"transfer_check"|"retention_check";
type View="fix-now"|"confusions"|"waiting";
type Practice={title:string;kind?:Kind;confusionId?:string;questionId?:string;nonce:string};
type Item={key:string;title:string;reason:string;status?:string;kind:Kind;questionId?:string;confusionId?:string;tone:"fix"|"later"};
const freshNonce=()=>`${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const due=(value?:string)=>!value||new Date(value).getTime()<=Date.now();

export default function TargetedMasteryPage(){
 const ready=useAuthGuard(),[hub,setHub]=useState<Hub|null>(null),[labels,setLabels]=useState<Record<string,QuestionLabel>>({}),[view,setView]=useState<View|null>(null),[practice,setPractice]=useState<Practice|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const handled=useRef(false);
 const loadLabels=useCallback(async(next:Hub)=>{const ids=[...next.needLearning,...next.transferChecks,...next.retentionChecks].map(x=>x.questionId).concat(...next.confusions.map(x=>[x.primaryQuestionId,x.relatedQuestionId].filter(Boolean) as string[]));if(!ids.length)return;try{const out=await rpc<LabelsResponse>("english_get_question_labels",{p_question_ids:[...new Set(ids)].slice(0,120)});setLabels(Object.fromEntries((out.items||[]).map(x=>[x.questionId,x])))}catch{}},[]);
 const refresh=useCallback(async()=>{try{setError("");const next=await targetedLiveRpc<Hub>("english_get_targeted_mastery");setHub(next);void loadLabels(next)}catch(e:any){setError(learnerErrorMessage(e,"Could not load Targeted Mastery."))}finally{setLoading(false)}},[loadLabels]);
 useEffect(()=>{if(!ready)return;void refresh();return subscribeTargetedDurability(()=>void refresh())},[ready,refresh]);
 const start=(title:string,kind?:Kind,confusionId?:string,questionId?:string)=>setPractice({title,kind,confusionId,questionId,nonce:freshNonce()});
 const name=(row:FocusRow)=>learnerName(labels[row.questionId],row.name);
 const items=useMemo(()=>{if(!hub)return {fix:[] as Item[],waiting:[] as Item[]};const from=(rows:FocusRow[],kind:Kind,ready:boolean,tone:Item["tone"],reason:string)=>rows.filter(x=>ready===due(x.nextReview)).map(x=>({key:`${kind}-${x.questionId}`,title:name(x),reason,status:ready?"Ready now":`Next check: ${friendlyDate(x.nextReview)}`,kind,questionId:x.questionId,tone}));const conf=hub.confusions.map(c=>({key:`c-${c.confusionId}`,title:confusionLabel(c.primaryName,c.relatedName),reason:"You flagged this confusion",status:"Ready now",kind:"confusion" as Kind,confusionId:c.confusionId,tone:"fix" as const}));return {fix:[...conf,...from(hub.transferChecks,"transfer_check",true,"fix","Fresh understanding check"),...from(hub.retentionChecks,"retention_check",true,"fix","Spaced recall is ready"),...from(hub.needLearning,"need_learning",true,"fix","Focused repair from recent evidence")],waiting:from(hub.retentionChecks,"retention_check",false,"later","Fresh proof completed")}},[hub,labels]);
 useEffect(()=>{if(!hub||handled.current)return;handled.current=true;const q=new URLSearchParams(location.search),v=q.get("view") as View|null;if(q.get("start")==="focused")start("Targeted Mastery","due_now");else if(q.get("confusion")){const c=hub.confusions.find(x=>x.confusionId===q.get("confusion"));start(c?confusionLabel(c.primaryName,c.relatedName):"Your Confusion","confusion",q.get("confusion")||undefined)}else if(q.get("question"))start(learnerName(labels[q.get("question")!],q.get("title")||undefined),undefined,undefined,q.get("question")||undefined);else if(v&&["fix-now","confusions","waiting"].includes(v))setView(v)},[hub,labels]);
 const load=useCallback(()=>!practice?Promise.resolve([]):practice.questionId?targetedSessionRpc<any[]>("english_get_targeted_question",{p_question_id:practice.questionId}):practice.kind==="due_now"?targetedSessionRpc<any[]>("english_get_targeted_due_session",{p_count:15,p_session_nonce:practice.nonce}):targetedSessionRpc<any[]>("english_get_targeted_session",{p_count:15,p_kind:practice.kind??null,p_confusion_id:practice.confusionId??null,p_session_nonce:practice.nonce}),[practice]);
 if(!ready)return <EnglishLoading text="Checking session…"/>;if(practice)return <QuizRunner title={practice.title} backHref="/english/targeted" load={load} module="targeted" onExit={()=>{setPractice(null);void refresh()}} onFinish={refresh}/>;
 if(view&&hub)return <Detail view={view} hub={hub} items={view==="waiting"?items.waiting:items.fix} onBack={()=>setView(null)} onStart={start}/>;
 const s=hub?.summary;
 return <main className="top-level-parity targeted-mastery-page learner-rebuild-page"><PageHeader back={<Link href="/english/practice" className="back-link">← Practice</Link>} eyebrow="Focused practice" title="Targeted Mastery" subtitle="Focused practice from mistakes, uncertainty and confusions."/>{error&&<div className="error-box">{error}</div>}{loading?<EnglishLoading text="Ranking focused practice…"/>:<><section className="targeted-command-card learner-command-card"><div><span className="learner-eyebrow">Ready now</span><div className="targeted-due-line"><strong>{s?.dueNow??0}</strong><span>questions are ready now</span></div><p>Start with the items most likely to improve your score now.</p></div><button className="btn primary targeted-start-button" disabled={!s?.dueNow} onClick={()=>start("Targeted Mastery","due_now")}>Start Focused Practice</button></section><div className="learner-overview-stack"><OverviewCard tone="fix" title="Fix Now" subtitle="Mistakes, uncertainty and fresh checks that are ready." count={s?.dueNow??0} onClick={()=>setView("fix-now")}/><OverviewCard tone="soon" title="Your Confusions" subtitle="Clear the meanings or rules you said get mixed up." count={s?.confusions??0} onClick={()=>setView("confusions")}/><OverviewCard tone="later" title="Waiting for Later" subtitle="These are waiting for the right recall time." count={items.waiting.length} onClick={()=>setView("waiting")}/><Link href="/english/revision/ai-intelligence" className="learner-overview-card tone-neutral"><span className="learner-card-icon">◌</span><span className="learner-card-copy"><b>Learning Insights</b><small>See what needs attention and why.</small></span></Link></div></>}</main>;
}
function Detail({view,hub,items,onBack,onStart}:{view:View;hub:Hub;items:Item[];onBack:()=>void;onStart:(title:string,kind?:Kind,confusionId?:string,questionId?:string)=>void}){const rows:Item[]=view==="confusions"?hub.confusions.map(c=>({key:c.confusionId,title:confusionLabel(c.primaryName,c.relatedName),reason:c.note?`You noted: ${c.note}`:"You said these meanings or rules get mixed up.",status:"Ready for focused practice",kind:"confusion" as Kind,confusionId:c.confusionId,tone:"fix" as const})):items;const title=view==="confusions"?"Your Confusions":view==="waiting"?"Waiting for Later":"Fix Now";const subtitle=view==="confusions"?"Clear the meanings or rules you said get mixed up.":view==="waiting"?"Nothing is forgotten here. These are waiting for the right recall time.":"Items that can improve your score now.";return <main className="top-level-parity learner-rebuild-page"><button type="button" className="learner-back" onClick={onBack}>← Targeted Mastery</button><PageHeader title={title} subtitle={subtitle}/>{view==="fix-now"&&rows.length>0&&<button className="btn primary" onClick={()=>onStart("Fix Now","due_now")}>Practice all</button>}<section className="learner-section"><div className="learner-row-list">{rows.length?rows.map(r=><LearnerRow key={r.key} title={r.title} subtitle={r.reason} status={r.status} tone={r.tone} onClick={()=>onStart(r.title,r.kind,r.confusionId,r.questionId)}/>):<div className="learner-empty">Nothing is waiting here right now.</div>}</div></section></main>}
function friendlyDate(value?:string){if(!value)return"Later";const d=new Date(value),now=new Date(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);if(d.toDateString()===tomorrow.toDateString())return"Tomorrow";return d.toLocaleDateString(undefined,{day:"numeric",month:"short"})}
