function bankCoverageCategoryRows_(){const all=allQuestions_().filter(q=>isGenuineBankQuestionV2_(q)),names={};table_(EP.sheets.categories).filter(r=>truthy_(r.Active)).forEach(r=>names[String(r.Category_ID||'').trim()]=String(r.Category_Name||''));const grouped={};all.forEach(q=>{const c=canonicalCategory_(q.topic);if(!grouped[c])grouped[c]=[];grouped[c].push(q)});return Object.keys(grouped).map(id=>({id,name:names[id]||progressCategoryName_(id,grouped[id][0]?.topic),questions:grouped[id]})).sort((a,b)=>{const ao=table_(EP.sheets.categories).find(r=>String(r.Category_ID||'')===a.id),bo=table_(EP.sheets.categories).find(r=>String(r.Category_ID||'')===b.id);return Number(ao?.Display_Order||99)-Number(bo?.Display_Order||99)||a.name.localeCompare(b.name)});}
function getBankCoverageHub(){
  ensurePerformanceModuleColumn_();const facts=performanceFactsV2_(),mastered=currentMasteredMapV2_(),rows=bankCoverageCategoryRows_(),today=todayKey_(),diff=centralDifficultMapV2_();let total=0,exposed=0;
  const categories=rows.map(g=>{const eligible=g.questions.filter(q=>!mastered[q.id]),ids=eligible.map(q=>q.id),exp=ids.filter(id=>facts.seen.has(id)).length,unseen=ids.filter(id=>!facts.seen.has(id)).length,doneToday=new Set(facts.all.filter(a=>a.module==='bankCoverage'&&dateKey_(a.ts)===today&&canonicalCategory_((eligible.find(q=>q.id===a.id)||{}).topic)===g.id).map(a=>a.id)).size,available=Math.max(0,Math.min(10-doneToday,unseen));total+=ids.length;exposed+=exp;return {id:g.id,name:g.name,total:ids.length,exposed:exp,unseen,available,doneToday,coverage:learningPctV2_(exp,ids.length),difficult:ids.filter(id=>!!diff[id]).length,complete:unseen===0};});
  return {date:today,total,exposed,left:Math.max(0,total-exposed),coverage:learningPctV2_(exposed,total),complete:total>0&&exposed>=total,categories:categories.filter(c=>c.total>0)};
}
function getBankCoverageBatch(category){
  const cat=String(category||'').trim(),hub=getBankCoverageHub(),meta=hub.categories.find(c=>c.id===cat);if(!meta||meta.available<=0)return [];const facts=performanceFactsV2_(),mastered=currentMasteredMapV2_(),diff=centralDifficultMapV2_(),group=bankCoverageCategoryRows_().find(g=>g.id===cat);if(!group)return [];const pool=shuffle_(group.questions.filter(q=>!mastered[q.id]&&!facts.seen.has(q.id))).slice(0,meta.available);return pool.map(q=>{const x=serveQuestion_(q);x.difficult=!!diff[q.id];return x;});
}
