const EP_DAILY_RATIONALE_V4='EP_DAILY_RATIONALE_V4';

function getBootstrapV3(){
  ensurePerformanceModuleColumn_();ensureLearningStatusMigration_();const cfg=config_(),all=allQuestions_(),daily=ensureDailyAdaptiveV3_(all,Number(cfg.DAILY_TARGET||120)),mastered=currentMasteredMapV2_(),status=statusMap_(),counts={};all.forEach(q=>{if(!isActive_(q)||mastered[q.id])return;const id=canonicalCategory_(q.topic);counts[id]=(counts[id]||0)+1;});const categories=table_(EP.sheets.categories).filter(r=>truthy_(r.Active)).sort((a,b)=>Number(a.Display_Order||99)-Number(b.Display_Order||99)).map(r=>({id:r.Category_ID,name:r.Category_Name,parent:r.Parent_Category,home:truthy_(r.Home_Visible),count:Number(counts[r.Category_ID]||0)})),today=todayKey_(),hinduToday=table_(EP.sheets.hindu).filter(r=>truthy_(r.Active)&&dateKey_(r.Date)===today).length,recallIds=recallIds_(status),recall=all.filter(q=>isActive_(q)&&!mastered[q.id]&&recallIds.has(q.id)).length,masteredCount=Object.keys(mastered).filter(id=>mastered[id]).length;return {schemaVersion:4,dailyTarget:Number(cfg.DAILY_TARGET||120),extraCounts:String(cfg.EXTRA_COUNTS||'10,20,30,50').split(',').map(Number).filter(Number.isFinite),categories,dailyInfo:daily.info,stats:{dailyTotal:daily.rows.length,dailyCompleted:daily.rows.filter(r=>String(r.Status||'').toLowerCase()==='completed').length,hinduToday,recall,mastered:masteredCount,totalActive:all.filter(q=>isActive_(q)&&!mastered[q.id]).length}};
}
function getDailyBatchV3(){
  const all=allQuestions_(),daily=ensureDailyAdaptiveV3_(all,Number(config_().DAILY_TARGET||120)),map=Object.fromEntries(all.map(q=>[q.id,q])),mastered=currentMasteredMapV2_(),batchDate=daily.rows.length?dateKey_(daily.rows[0].Quiz_Date):todayKey_(),rationale=dailyRationaleSnapshotV4_(daily.rows,all,batchDate),items=rationale.items||{};
  return daily.rows.filter(r=>String(r.Status||'').toLowerCase()!=='completed').map(r=>{const id=String(r.Question_ID||'').trim(),q=map[id];if(!q||!isActive_(q)||mastered[id])return null;const x=serveQuestion_(q),meta=items[id]||[String(r.Reason||'Mixed Revision'),''];x.selectionReason=String(meta[0]||r.Reason||'Mixed Revision');x.selectionReasonCode=dailyReasonCodeV4_(x.selectionReason);x.selectionSignals=String(meta[1]||'').split(',').filter(Boolean);return x;}).filter(Boolean);
}

function ensureDailyAdaptiveV3_(all,target){
  target=Math.max(1,Number(target||120));const today=todayKey_(),s=sheet_(EP.sheets.daily),mastered=currentMasteredMapV2_();let rows=table_(EP.sheets.daily).filter(r=>String(r.Question_ID||'').trim());rows=normalizeDailyRowsV3_(rows,all,mastered,s);rows=syncDailyCompletionsV3_(rows,s);rows=repairSkippedDailyDateV2_(rows,s,today);const batchDate=rows.length?dateKey_(rows[0].Quiz_Date):'';
  if(batchDate&&batchDate!==today){const done=rows.filter(r=>String(r.Status||'').toLowerCase()==='completed').length;if(done<rows.length)return {rows,info:dailyInfoAdaptiveV3_(rows,batchDate,true,target)};archiveDailyV2_(rows,batchDate);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,Math.max(7,s.getLastColumn())).clearContent();const nextDate=addDaysKeyV2_(batchDate,1);rows=createDailyAdaptiveV3_(all,target,nextDate,s);return {rows,info:dailyInfoAdaptiveV3_(rows,nextDate,nextDate!==today,target)};}
  if(batchDate===today&&rows.length)return {rows,info:dailyInfoAdaptiveV3_(rows,today,false,target)};rows=createDailyAdaptiveV3_(all,target,today,s);return {rows,info:dailyInfoAdaptiveV3_(rows,today,false,target)};
}
function normalizeDailyRowsV3_(rows,all,mastered,s){const map=Object.fromEntries(all.map(q=>[q.id,q]));rows.forEach((r,i)=>{const id=String(r.Question_ID||'').trim(),q=map[id],done=String(r.Status||'').toLowerCase()==='completed';if(!done&&(!q||!isActive_(q)||mastered[id])){s.getRange(i+2,5).setValue('Completed');r.Status='Completed';}});return rows;}
function syncDailyCompletionsV3_(rows,s){
  if(!rows.length)return rows;const facts=performanceFactsV2_(),byId=facts.byId||{};rows.forEach((r,i)=>{if(String(r.Status||'').toLowerCase()==='completed')return;const id=String(r.Question_ID||'').trim(),key=dateKey_(r.Quiz_Date);if(!id||!key)return;const p=key.split('-').map(Number),start=new Date(p[0],p[1]-1,p[2],0,0,0,0),hit=(byId[id]||[]).some(a=>a.ts>=start&&String(a.module||'').toLowerCase()==='daily');if(hit){s.getRange(i+2,5).setValue('Completed');r.Status='Completed';}});return rows;
}
function adaptiveCategoryPenaltyV3_(cat,bank,profiles){const ids=bank.filter(q=>learningCategoryKeyV2_(q)===cat).map(q=>q.id),seen=ids.map(id=>profiles[id]).filter(Boolean);if(!seen.length)return .5;const weak=seen.filter(p=>p.state==='Weak'||p.state==='Persistent Weak').length,retN=seen.reduce((n,p)=>n+p.retentionAttempts,0),retC=seen.reduce((n,p)=>n+p.retentionCorrect,0),first=seen.filter(p=>p.firstCorrect).length/seen.length,ret=retN?retC/retN:.5;return Math.max(0,Math.min(1,(weak/seen.length)*.5+(1-first)*.25+(1-ret)*.25));}
function createDailyAdaptiveV3_(all,target,batchDate,s){
  const facts=performanceFactsV2_(),profiles=learningProfilesV2_(facts),mastered=currentMasteredMapV2_(),stars=currentStarredMapV2_(),diff=centralDifficultMapV2_(),base=all.filter(q=>isActive_(q)&&!mastered[q.id]),active=base.filter(q=>{if(isGenuineBankQuestionV2_(q))return true;const p=profiles[q.id]||learningProfileV2_([]);return ['Persistent Weak','Weak','Fragile'].includes(p.state)||!!stars[q.id]||!!diff[q.id];}),penalty={};active.forEach(q=>{const c=learningCategoryKeyV2_(q);if(penalty[c]===undefined)penalty[c]=adaptiveCategoryPenaltyV3_(c,active,profiles)});const scored=[];
  active.forEach(q=>{const p=profiles[q.id]||learningProfileV2_([]),cat=learningCategoryKeyV2_(q),weight=(penalty[cat]||0)*80;let baseScore=0,reason='Mixed Revision';if(p.state==='Persistent Weak'){baseScore=1000;reason='Persistent Weak';}else if(p.state==='Weak'){baseScore=850;reason='Weak';}else if(p.state==='Fragile'){baseScore=700;reason='Fragile';}else if(p.attempts>0&&dailyDueV3_(p,batchDate)){baseScore=560;reason='Due Spaced Revision';}else if(stars[q.id]&&p.attempts>0){baseScore=500;reason='Marked Review';}else if(diff[q.id]&&p.attempts>0){baseScore=480;reason='Difficult Review';}else if(p.attempts===0&&isGenuineBankQuestionV2_(q)){baseScore=250;reason='Controlled New';}else if(p.state==='Learning'){baseScore=180;reason='Learning';}else{baseScore=100;reason='Mixed Revision';}scored.push({q,score:baseScore+weight+Math.random()*25,reason,signals:dailySignalCodesV4_(q,p,batchDate,stars,diff)});});
  scored.sort((a,b)=>b.score-a.score);const selected=scored.slice(0,target);if(selected.length){const out=selected.map(x=>[x.q.id,Math.round(x.score),x.reason,batchDate,'New',x.q.topic||'',x.q.conceptId||'']);s.getRange(2,1,out.length,7).setValues(out);writeDailyRationaleV4_(batchDate,Object.fromEntries(selected.map(x=>[x.q.id,[x.reason,dailyEnsurePrimarySignalV4_(x.reason,x.signals).join(',')]])));}return table_(EP.sheets.daily).filter(r=>dateKey_(r.Quiz_Date)===batchDate&&String(r.Question_ID||'').trim());
}
function dailyDueV3_(p,key){if(!p||!p.lastAttempt)return false;const days={"Persistent Weak":1,"Weak":1,"Fragile":2,"Learning":4,"Strong":14}[p.state]||7,target=new Date(p.lastAttempt.getTime()+days*86400000),parts=String(key||todayKey_()).split('-').map(Number),end=new Date(parts[0],parts[1]-1,parts[2],23,59,59,999);return target<=end;}
function dailyInfoAdaptiveV3_(rows,activeDate,pending,target){
  const x=dailyInfoV2_(rows,activeDate,pending,target),reasons=rows.map(r=>String(r.Reason||''));x.persistentWeakCount=reasons.filter(r=>r==='Persistent Weak').length;x.weakCount=reasons.filter(r=>r==='Weak').length;x.fragileCount=reasons.filter(r=>r==='Fragile').length;x.dueCount=reasons.filter(r=>r==='Due Spaced Revision').length;x.markedReviewCount=reasons.filter(r=>r==='Marked Review').length;x.difficultReviewCount=reasons.filter(r=>r==='Difficult Review').length;x.flaggedCount=x.markedReviewCount+x.difficultReviewCount;x.freshCount=reasons.filter(r=>r==='Controlled New').length;x.learningCount=reasons.filter(r=>r==='Learning').length;x.mixedCount=reasons.filter(r=>r==='Mixed Revision').length;x.selectionMixTotal=x.persistentWeakCount+x.weakCount+x.fragileCount+x.dueCount+x.flaggedCount+x.freshCount+x.learningCount+x.mixedCount;x.carryCount=x.flaggedCount;x.carryForwardRemaining=pending?rows.filter(r=>String(r.Status||'').toLowerCase()!=='completed').length:0;x.adaptive=true;return x;
}

function dailyReasonCodeV4_(reason){return ({'Persistent Weak':'PW','Weak':'W','Fragile':'FR','Due Spaced Revision':'DUE','Marked Review':'STAR','Difficult Review':'DIFF','Controlled New':'NEW','Learning':'LEARN','Mixed Revision':'MIX'})[String(reason||'')]||'MIX';}
function dailySignalCodesV4_(q,p,key,stars,diff){const out=[];if(p.state==='Persistent Weak')out.push('PW');else if(p.state==='Weak')out.push('W');else if(p.state==='Fragile')out.push('FR');else if(p.state==='Learning')out.push('LEARN');if(p.attempts>0&&dailyDueV3_(p,key))out.push('DUE');if(stars&&stars[q.id])out.push('STAR');if(diff&&diff[q.id])out.push('DIFF');if(p.attempts===0&&isGenuineBankQuestionV2_(q))out.push('NEW');if(!out.length)out.push('MIX');return [...new Set(out)];}
function dailyEnsurePrimarySignalV4_(reason,signals){const primary=dailyReasonCodeV4_(reason),out=(signals||[]).slice();if(!out.includes(primary))out.unshift(primary);return [...new Set(out)];}
function readDailyRationaleV4_(){try{const raw=PropertiesService.getScriptProperties().getProperty(EP_DAILY_RATIONALE_V4);if(!raw)return null;const x=JSON.parse(raw);return x&&x.date&&x.items?x:null}catch(e){return null}}
function writeDailyRationaleV4_(date,items){try{PropertiesService.getScriptProperties().setProperty(EP_DAILY_RATIONALE_V4,JSON.stringify({date:String(date||''),items:items||{}}))}catch(e){}return {date:String(date||''),items:items||{}};}
function dailyRationaleSnapshotV4_(rows,all,batchDate){
  rows=rows||[];const ids=rows.map(r=>String(r.Question_ID||'').trim()).filter(Boolean),saved=readDailyRationaleV4_();if(saved&&saved.date===String(batchDate||'')&&ids.every(id=>saved.items&&saved.items[id]))return saved;if(!ids.length)return {date:String(batchDate||''),items:{}};
  const facts=performanceFactsV2_(),profiles=learningProfilesV2_(facts),stars=currentStarredMapV2_(),diff=centralDifficultMapV2_(),qmap=Object.fromEntries((all||[]).map(q=>[q.id,q])),items={};rows.forEach(r=>{const id=String(r.Question_ID||'').trim(),q=qmap[id];if(!id||!q)return;const p=profiles[id]||learningProfileV2_([]),reason=String(r.Reason||'Mixed Revision'),signals=dailyEnsurePrimarySignalV4_(reason,dailySignalCodesV4_(q,p,batchDate,stars,diff));items[id]=[reason,signals.join(',')];});return writeDailyRationaleV4_(batchDate,items);
}
