function getBootstrapV3(){
  ensurePerformanceModuleColumn_();ensureLearningStatusMigration_();const cfg=config_(),all=allQuestions_(),daily=ensureDailyAdaptiveV3_(all,Number(cfg.DAILY_TARGET||120)),mastered=currentMasteredMapV2_(),counts={};all.forEach(q=>{if(!isActive_(q)||mastered[q.id])return;const id=canonicalCategory_(q.topic);counts[id]=(counts[id]||0)+1;});const categories=table_(EP.sheets.categories).filter(r=>truthy_(r.Active)).sort((a,b)=>Number(a.Display_Order||99)-Number(b.Display_Order||99)).map(r=>({id:r.Category_ID,name:r.Category_Name,parent:r.Parent_Category,home:truthy_(r.Home_Visible),count:Number(counts[r.Category_ID]||0)})),today=todayKey_(),hinduToday=table_(EP.sheets.hindu).filter(r=>truthy_(r.Active)&&dateKey_(r.Date)===today).length,facts=performanceFactsV2_(),profiles=learningProfilesV2_(facts),recall=Object.keys(profiles).filter(id=>profiles[id].attempts>0&&!mastered[id]).length,masteredCount=Object.keys(mastered).filter(id=>mastered[id]).length;return {schemaVersion:4,dailyTarget:Number(cfg.DAILY_TARGET||120),extraCounts:String(cfg.EXTRA_COUNTS||'10,20,30,50').split(',').map(Number).filter(Number.isFinite),categories,dailyInfo:daily.info,stats:{dailyTotal:daily.rows.length,dailyCompleted:daily.rows.filter(r=>String(r.Status||'').toLowerCase()==='completed').length,hinduToday,recall,mastered:masteredCount,totalActive:all.filter(q=>isActive_(q)&&!mastered[q.id]).length}};
}
function getDailyBatchV3(){const all=allQuestions_(),daily=ensureDailyAdaptiveV3_(all,Number(config_().DAILY_TARGET||120)),map=Object.fromEntries(all.map(q=>[q.id,q])),mastered=currentMasteredMapV2_();return daily.rows.filter(r=>String(r.Status||'').toLowerCase()!=='completed').map(r=>map[String(r.Question_ID||'').trim()]).filter(q=>q&&isActive_(q)&&!mastered[q.id]).map(serveQuestion_);}

function ensureDailyAdaptiveV3_(all,target){
  target=Math.max(1,Number(target||120));const today=todayKey_(),s=sheet_(EP.sheets.daily),mastered=currentMasteredMapV2_();let rows=table_(EP.sheets.daily).filter(r=>String(r.Question_ID||'').trim());rows=normalizeDailyRowsV3_(rows,all,mastered,s);rows=syncDailyCompletionsV3_(rows,s);rows=repairSkippedDailyDateV2_(rows,s,today);const batchDate=rows.length?dateKey_(rows[0].Quiz_Date):'';
  if(batchDate&&batchDate!==today){const done=rows.filter(r=>String(r.Status||'').toLowerCase()==='completed').length;if(done<rows.length)return {rows,info:dailyInfoV2_(rows,batchDate,true,target)};archiveDailyV2_(rows,batchDate);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,Math.max(7,s.getLastColumn())).clearContent();const nextDate=addDaysKeyV2_(batchDate,1);rows=createDailyAdaptiveV3_(all,target,nextDate,s);return {rows,info:dailyInfoAdaptiveV3_(rows,nextDate,nextDate!==today,target)};}
  if(batchDate===today&&rows.length)return {rows,info:dailyInfoAdaptiveV3_(rows,today,false,target)};rows=createDailyAdaptiveV3_(all,target,today,s);return {rows,info:dailyInfoAdaptiveV3_(rows,today,false,target)};
}
function normalizeDailyRowsV3_(rows,all,mastered,s){const map=Object.fromEntries(all.map(q=>[q.id,q]));rows.forEach((r,i)=>{const id=String(r.Question_ID||'').trim(),q=map[id],done=String(r.Status||'').toLowerCase()==='completed';if(!done&&(!q||!isActive_(q)||mastered[id])){s.getRange(i+2,5).setValue('Completed');r.Status='Completed';}});return rows;}
function syncDailyCompletionsV3_(rows,s){
  if(!rows.length)return rows;const facts=performanceFactsV2_(),byId=facts.byId||{};rows.forEach((r,i)=>{if(String(r.Status||'').toLowerCase()==='completed')return;const id=String(r.Question_ID||'').trim(),key=dateKey_(r.Quiz_Date);if(!id||!key)return;const p=key.split('-').map(Number),start=new Date(p[0],p[1]-1,p[2],0,0,0,0),hit=(byId[id]||[]).some(a=>a.ts>=start&&String(a.module||'').toLowerCase()==='daily');if(hit){s.getRange(i+2,5).setValue('Completed');r.Status='Completed';}});return rows;
}
function adaptiveCategoryPenaltyV3_(cat,bank,profiles){const ids=bank.filter(q=>canonicalCategory_(q.topic)===cat).map(q=>q.id),seen=ids.map(id=>profiles[id]).filter(Boolean);if(!seen.length)return .5;const weak=seen.filter(p=>p.state==='Weak'||p.state==='Persistent Weak').length,retN=seen.reduce((n,p)=>n+p.retentionAttempts,0),retC=seen.reduce((n,p)=>n+p.retentionCorrect,0),first=seen.filter(p=>p.firstCorrect).length/seen.length,ret=retN?retC/retN:.5;return Math.max(0,Math.min(1,(weak/seen.length)*.5+(1-first)*.25+(1-ret)*.25));}
function createDailyAdaptiveV3_(all,target,batchDate,s){
  const facts=performanceFactsV2_(),profiles=learningProfilesV2_(facts),mastered=currentMasteredMapV2_(),stars=currentStarredMapV2_(),diff=centralDifficultMapV2_(),base=all.filter(q=>isActive_(q)&&!mastered[q.id]),active=base.filter(q=>{if(isGenuineBankQuestionV2_(q))return true;const p=profiles[q.id]||learningProfileV2_([]);return ['Persistent Weak','Weak','Fragile'].includes(p.state)||!!stars[q.id]||!!diff[q.id];}),penalty={};active.forEach(q=>{const c=canonicalCategory_(q.topic);if(penalty[c]===undefined)penalty[c]=adaptiveCategoryPenaltyV3_(c,active,profiles)});const scored=[];
  active.forEach(q=>{const p=profiles[q.id]||learningProfileV2_([]),cat=canonicalCategory_(q.topic),weight=(penalty[cat]||0)*80;let baseScore=0,reason='Mixed Revision';if(p.state==='Persistent Weak'){baseScore=1000;reason='Persistent Weak';}else if(p.state==='Weak'){baseScore=850;reason='Weak';}else if(p.state==='Fragile'){baseScore=700;reason='Fragile';}else if(p.attempts>0&&dailyDueV3_(p,batchDate)){baseScore=560;reason='Due Spaced Revision';}else if(stars[q.id]&&p.attempts>0){baseScore=500;reason='Marked Review';}else if(diff[q.id]&&p.attempts>0){baseScore=480;reason='Difficult Review';}else if(p.attempts===0&&isGenuineBankQuestionV2_(q)){baseScore=250;reason='Controlled New';}else if(p.state==='Learning'){baseScore=180;reason='Learning';}else{baseScore=100;reason='Mixed Revision';}scored.push({q,score:baseScore+weight+Math.random()*25,reason});});
  scored.sort((a,b)=>b.score-a.score);const selected=scored.slice(0,target);if(selected.length){const out=selected.map(x=>[x.q.id,Math.round(x.score),x.reason,batchDate,'New',x.q.topic||'',x.q.conceptId||'']);s.getRange(2,1,out.length,7).setValues(out);}return table_(EP.sheets.daily).filter(r=>dateKey_(r.Quiz_Date)===batchDate&&String(r.Question_ID||'').trim());
}
function dailyDueV3_(p,key){if(!p||!p.lastAttempt)return false;const days={"Persistent Weak":1,"Weak":1,"Fragile":2,"Learning":4,"Strong":14}[p.state]||7,target=new Date(p.lastAttempt.getTime()+days*86400000),parts=String(key||todayKey_()).split('-').map(Number),end=new Date(parts[0],parts[1]-1,parts[2],23,59,59,999);return target<=end;}
function dailyInfoAdaptiveV3_(rows,activeDate,pending,target){const x=dailyInfoV2_(rows,activeDate,pending,target),reasons=rows.map(r=>String(r.Reason||''));x.persistentWeakCount=reasons.filter(r=>r==='Persistent Weak').length;x.weakCount=reasons.filter(r=>r==='Weak').length;x.fragileCount=reasons.filter(r=>r==='Fragile').length;x.dueCount=reasons.filter(r=>r==='Due Spaced Revision').length;x.freshCount=reasons.filter(r=>r==='Controlled New').length;x.carryCount=reasons.filter(r=>r==='Marked Review'||r==='Difficult Review').length;x.adaptive=true;return x;}
