function learningMetricV2_(ids,facts,profiles){
  const unique=[...new Set((ids||[]).map(x=>String(x||'').trim()).filter(Boolean))],total=unique.length;let exposed=0,firstN=0,firstC=0,retN=0,retC=0,afterN=0,afterC=0,weak=0,persistent=0,fragile=0,strong=0,mastered=0;
  unique.forEach(id=>{const p=profiles[id];if(!p||!p.attempts)return;exposed++;firstN++;if(p.firstCorrect)firstC++;retN+=p.retentionAttempts;retC+=p.retentionCorrect;afterN+=p.afterReviewAttempts;afterC+=p.afterReviewCorrect;if(p.state==='Persistent Weak'){persistent++;weak++;}else if(p.state==='Weak')weak++;else if(p.state==='Fragile')fragile++;else if(p.state==='Strong')strong++;if(p.provenMastery)mastered++;});
  const coverage=learningPctV2_(exposed,total),first=learningPctV2_(firstC,firstN),retention=learningPctV2_(retC,retN),after=learningPctV2_(afterC,afterN);
  return {total,encountered:exposed,exposed,left:Math.max(0,total-exposed),percent:coverage,coveragePercent:coverage,firstAttemptAccuracy:first,firstAttemptCount:firstN,firstAttemptCorrect:firstC,retentionAccuracy:retention,retentionAttempts:retN,retentionCorrect:retC,afterReviewAccuracy:after,afterReviewAttempts:afterN,afterReviewCorrect:afterC,weak,persistentWeak:persistent,fragile,strong,mastered,correct:firstC,correctPercent:first,confident:retC,confidentPercent:retention,doubt:weak,doubtPercent:learningPctV2_(weak,Math.max(1,exposed))};
}

function computeLearningProgressV2_(){
  ensureLearningStatusMigration_();const all=allQuestions_(),masteredMap=currentMasteredMapV2_(),bank=all.filter(q=>isGenuineBankQuestionV2_(q)&&!masteredMap[q.id]),facts=performanceFactsV2_(),profiles=learningProfilesV2_(facts),qmap=Object.fromEntries(all.map(q=>[q.id,q])),names={};table_(EP.sheets.categories).forEach(r=>{if(truthy_(r.Active))names[String(r.Category_ID||'').trim()]=String(r.Category_Name||'')});
  const grouped={};bank.forEach(q=>{const cat=canonicalCategory_(q.topic);if(!grouped[cat])grouped[cat]=[];grouped[cat].push(q.id)});const categories=Object.keys(grouped).map(id=>Object.assign({id,name:names[id]||progressCategoryName_(id,(qmap[grouped[id][0]]||{}).topic)},learningMetricV2_(grouped[id],facts,profiles))).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));
  const overall=learningMetricV2_(bank.map(q=>q.id),facts,profiles),today=todayKey_(),starMap=currentStarredMapV2_(),todaySeen=new Set(facts.all.filter(a=>dateKey_(a.ts)===today).map(a=>a.id)),todayFirst=new Set();Object.keys(facts.byId).forEach(id=>{const a=facts.byId[id][0];if(a&&dateKey_(a.ts)===today)todayFirst.add(id)});
  const safePool=fn=>{try{return typeof fn==='function'?(fn()||[]):[]}catch(e){return[]}},newPool=safePool(()=>newPracticePool_('ALL')),demandPool=safePool(()=>demandQuestionPool_('__ALL__').map(x=>x.q)),sourcePool=all.filter(q=>{try{return !!sourceKey_(q)}catch(e){return false}}),savedIds=typeof getMySavedWordQuestionIds==='function'?getMySavedWordQuestionIds():[],hinduPool=all.filter(q=>/^HV20\d{6}_/i.test(String(q.id||''))||String(q.topic||'').toLowerCase().includes('the hindu'));
  const modules={practice:learningMetricV2_(bank.map(q=>q.id),facts,profiles),new:learningMetricV2_(newPool.map(q=>q.id),facts,profiles),demanded:learningMetricV2_(demandPool.map(q=>q.id),facts,profiles),hindu:learningMetricV2_(hinduPool.map(q=>q.id),facts,profiles),sources:learningMetricV2_(sourcePool.map(q=>q.id),facts,profiles),saved:learningMetricV2_(savedIds,facts,profiles)};
  const currentSuppressed=Object.keys(masteredMap).filter(id=>masteredMap[id]).length,provenMastered=Object.keys(profiles).filter(id=>profiles[id]&&profiles[id].provenMastery).length,overview={encountered:overall.exposed,total:overall.total,todayNew:todayFirst.size,starred:Object.keys(starMap).filter(id=>starMap[id]).length,mastered:provenMastered,suppressed:currentSuppressed};
  return Object.assign({schemaVersion:2,date:today,snapshotGeneratedAt:new Date().toISOString(),todayActivity:todaySeen.size,todayNew:todayFirst.size,starredCount:overview.starred,masteredCount:provenMastered,suppressedCount:currentSuppressed,bankExposed:overall.coveragePercent,firstAttemptAccuracy:overall.firstAttemptAccuracy,afterReviewAccuracy:overall.afterReviewAccuracy,retentionAccuracy:overall.retentionAccuracy,weakCount:overall.weak,persistentWeakCount:overall.persistentWeak,fragileCount:overall.fragile,categories,modules,overview},overall);
}

function getLearningProgressSnapshot(){
  const props=PropertiesService.getScriptProperties(),raw=props.getProperty(EP_LEARNING_PROGRESS_KEY);if(raw){try{const p=JSON.parse(raw),age=Date.now()-new Date(p.snapshotGeneratedAt||0).getTime();if(age<15*60*1000)return p;}catch(e){}}
  const p=computeLearningProgressV2_();props.setProperty(EP_LEARNING_PROGRESS_KEY,JSON.stringify(p));return p;
}
function refreshLearningProgressSnapshot(){const p=computeLearningProgressV2_();PropertiesService.getScriptProperties().setProperty(EP_LEARNING_PROGRESS_KEY,JSON.stringify(p));return p;}
