function mySavedRevisionItemsV2_(){
  const words=myWordsRows_().filter(x=>truthy_(x.Active)&&String(x.Practice_Question_ID||'').trim()).sort((a,b)=>new Date(a.Created_At||0)-new Date(b.Created_At||0)),qmap=Object.fromEntries(allQuestions_().map(q=>[q.id,q])),facts=performanceFactsV2_(),profiles=learningProfilesV2_(facts),stars=currentStarredMapV2_(),diff=centralDifficultMapV2_(),mastered=currentMasteredMapV2_(),seen=new Set(),out=[];words.forEach(w=>{const id=String(w.Practice_Question_ID||'').trim();if(!id||seen.has(id))return;const q=qmap[id];if(!q)return;seen.add(id);const date=dateKey_(w.Created_At)||dateKey_(w.Updated_At)||todayKey_(),day=typeof dailyDayNoV2_==='function'?dailyDayNoV2_(date):1,p=profiles[id]||learningProfileV2_([]);out.push({savedId:String(w.Saved_ID||''),id,day,date,word:String(w.Word||q.word||''),q,profile:p,starred:!!stars[id],difficult:!!diff[id],mastered:!!mastered[id],active:isActive_(q)});});return out;
}
function mySavedRevisionStatsV2_(rows){const active=rows.filter(x=>x.active&&!x.mastered);return {saved:rows.length,focus:active.length,newCount:active.filter(x=>x.profile.attempts===0).length,seen:rows.filter(x=>x.profile.attempts>0).length,left:rows.filter(x=>x.profile.attempts===0).length,weak:active.filter(x=>x.profile.state==='Weak'||x.profile.state==='Persistent Weak').length,persistentWeak:active.filter(x=>x.profile.state==='Persistent Weak').length,difficult:active.filter(x=>x.difficult).length,starred:active.filter(x=>x.starred).length,mastered:rows.filter(x=>x.mastered).length};}
function mySavedRevisionCategoryV2_(x){const id=learningCategoryKeyV2_(x.q),name=learningCategoryNameV2_(id,x.q);return {id,name};}
function mySavedRevisionCategoriesV2_(rows){const grouped={};rows.forEach(x=>{const c=mySavedRevisionCategoryV2_(x),k=c.id||c.name||'MISC';if(!grouped[k])grouped[k]={id:k,name:c.name||k,rows:[]};grouped[k].rows.push(x);});return Object.values(grouped).map(g=>{const st=mySavedRevisionStatsV2_(g.rows);return {id:g.id,name:g.name,total:g.rows.length,seen:st.seen,left:st.left,coverage:g.rows.length?Math.round(st.seen*1000/g.rows.length)/10:0};}).sort((a,b)=>b.left-a.left||a.name.localeCompare(b.name));}
function mySavedRevisionHierarchyV2_(rows,currentDay){const groups=[],currentMonth=Math.floor((currentDay-1)/30)+1,currentMonthStart=(currentMonth-1)*30+1,currentBlockStart=Math.floor((currentDay-1)/10)*10+1;for(let d=currentDay;d>=currentBlockStart;d--){const part=rows.filter(x=>x.day===d);if(part.length)groups.push({type:'day',label:'Day '+d,fromDay:d,toDay:d,stats:mySavedRevisionStatsV2_(part)});}for(let start=currentBlockStart-10;start>=currentMonthStart;start-=10){const end=Math.min(start+9,currentDay),part=rows.filter(x=>x.day>=start&&x.day<=end);if(part.length)groups.push({type:'block',label:'Days '+start+'–'+end,fromDay:start,toDay:end,stats:mySavedRevisionStatsV2_(part)});}for(let month=currentMonth-1;month>=1;month--){const start=(month-1)*30+1,end=month*30,part=rows.filter(x=>x.day>=start&&x.day<=end);if(part.length)groups.push({type:'month',label:'Month '+month+' · Days '+start+'–'+end,fromDay:start,toDay:end,stats:mySavedRevisionStatsV2_(part)});}return groups;}
function getMySavedRevisionHub(){const rows=mySavedRevisionItemsV2_(),currentDay=typeof starredRevisionActiveDay_==='function'?starredRevisionActiveDay_():Math.max(1,...rows.map(x=>x.day));return {currentDay,stats:mySavedRevisionStatsV2_(rows),categories:mySavedRevisionCategoriesV2_(rows),groups:mySavedRevisionHierarchyV2_(rows,currentDay)};}
function getMySavedRevisionGroup(fromDay,toDay){const rows=mySavedRevisionItemsV2_().filter(x=>x.day>=Number(fromDay)&&x.day<=Number(toDay)),days=[];for(let d=Number(toDay);d>=Number(fromDay);d--){const part=rows.filter(x=>x.day===d);if(part.length)days.push({day:d,label:'Day '+d,fromDay:d,toDay:d,stats:mySavedRevisionStatsV2_(part)});}return {stats:mySavedRevisionStatsV2_(rows),days};}
function mySavedRevisionScopeV2_(scope){scope=scope||{};const from=Math.max(1,Number(scope.fromDay||1)),to=Math.max(from,Number(scope.toDay||999999));return {fromDay:from,toDay:to};}
function getMySavedRevisionItems(scope,kind){const sc=mySavedRevisionScopeV2_(scope),mode=String(kind||'all').toLowerCase();return mySavedRevisionItemsV2_().filter(x=>x.day>=sc.fromDay&&x.day<=sc.toDay).filter(x=>mode==='mastered'?x.mastered:mode==='difficult'?x.active&&!x.mastered&&x.difficult:true).sort((a,b)=>b.day-a.day||a.word.localeCompare(b.word)).map(x=>({id:x.id,word:x.word,day:x.day,state:x.profile.state,attempts:x.profile.attempts,starred:x.starred,difficult:x.difficult,mastered:x.mastered}));}
function getMySavedRevisionBatch(scope,kind,count){const sc=mySavedRevisionScopeV2_(scope),mode=String(kind||'all').toLowerCase();let rows=mySavedRevisionItemsV2_().filter(x=>x.day>=sc.fromDay&&x.day<=sc.toDay&&x.active&&!x.mastered);if(mode==='new')rows=rows.filter(x=>x.profile.attempts===0);if(mode==='weak')rows=rows.filter(x=>x.profile.state==='Weak'||x.profile.state==='Persistent Weak');if(mode==='difficult')rows=rows.filter(x=>x.difficult);shuffle_(rows);if(['new','weak'].includes(mode)){const n=Math.max(1,Math.min(100,Number(count||10)));rows=rows.slice(0,n);}return rows.map(x=>{const q=serveQuestion_(x.q);q.difficult=!!x.difficult;q.marked=!!x.starred;return q;});}
