function newPracticeLivePool_(wanted){
  const all=allQuestionsRaw_(),status=statusMap_(),key=String(wanted||'ALL').trim()||'ALL',days=Number(config_().NEW_CONTENT_DAYS||7),now=new Date(),cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-Math.max(0,days-1));cutoff.setHours(0,0,0,0);
  const hinduIds=new Set(typeof getSavedHinduQuestionIds==='function'?getSavedHinduQuestionIds():[]),myIds=new Set(typeof getMySavedWordQuestionIds==='function'?getMySavedWordQuestionIds():[]),out=[],seen=new Set();
  all.forEach(q=>{if(!isActive_(q)||(status[q.id]&&status[q.id].mastered))return;const rawCat=canonicalCategory_(q.topic),cat=rawCat==='MISC'?'NOT_SPECIFIED':rawCat,added=recentContentDate_(q),recent=!!added&&added>=cutoff,inHindu=hinduIds.has(q.id),inMine=myIds.has(q.id);let include=false;if(key==='ALL')include=recent||inHindu||inMine;else if(key==='HINDU_WORDS')include=inHindu;else if(key==='MY_SAVED_WORDS')include=inMine;else include=recent&&cat===key;if(include&&!seen.has(q.id)){seen.add(q.id);out.push(q)}});return out;
}
function newPracticeScopedWordPool_(wanted){const all=allQuestionsRaw_(),status=statusMap_(),key=String(wanted||'ALL').trim()||'ALL',hinduIds=new Set(typeof getSavedHinduQuestionIds==='function'?getSavedHinduQuestionIds():[]),myIds=new Set(typeof getMySavedWordQuestionIds==='function'?getMySavedWordQuestionIds():[]);return all.filter(q=>{if(!isActive_(q)||(status[q.id]&&status[q.id].mastered)||!String(q.word||'').trim())return false;const cat=canonicalCategory_(q.topic);if(key==='ALL'||key==='VOC')return cat==='VOC';if(key==='HINDU_WORDS')return hinduIds.has(q.id);if(key==='MY_SAVED_WORDS')return myIds.has(q.id);return cat===key});}
function newPracticeNewWordOrder_(pool,status){const st=status||statusMap_(),b=[[],[],[],[]];pool.forEach(q=>{const s=st[q.id]||{},attempts=Number(s.attempts||0),weak=newPracticeWeak_(s),added=recentContentDate_(q),addedMs=added?added.getTime():0,lastRaw=s.lastAttempt?new Date(s.lastAttempt).getTime():0,item={q,addedMs,last:isNaN(lastRaw)?0:lastRaw};if(attempts<=0&&addedMs)b[0].push(item);else if(attempts<=0)b[1].push(item);else if(weak)b[2].push(item);else b[3].push(item)});b[0].sort((a,z)=>z.addedMs-a.addedMs);b[1].sort((a,z)=>z.addedMs-a.addedMs);b[2].sort((a,z)=>z.last-a.last||z.addedMs-a.addedMs);b[3].sort((a,z)=>z.last-a.last||z.addedMs-a.addedMs);return b.flat().map(x=>x.q);}
function getNewPracticeHubLive(){
  const all=allQuestionsRaw_(),status=statusMap_(),days=Number(config_().NEW_CONTENT_DAYS||7),now=new Date(),cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-Math.max(0,days-1));cutoff.setHours(0,0,0,0),grouped={};
  all.forEach(q=>{if(!isActive_(q)||(status[q.id]&&status[q.id].mastered))return;const added=recentContentDate_(q);if(!added||added<cutoff)return;const rawCat=canonicalCategory_(q.topic),id=rawCat==='MISC'?'NOT_SPECIFIED':rawCat,name=newPracticeCategoryName_(id,q.topic);if(!grouped[id])grouped[id]={id,name,total:0,weak:0,newWords:0,starred:0,latest:''};const g=grouped[id],st=status[q.id]||{},dk=Utilities.formatDate(added,Session.getScriptTimeZone(),'yyyy-MM-dd');g.total++;if(newPracticeWeak_(st))g.weak++;if(String(q.word||'').trim())g.newWords++;if(isStarredStatus_(st))g.starred++;if(!g.latest||dk>g.latest)g.latest=dk;});
  const active=q=>isActive_(q)&&!(status[q.id]&&status[q.id].mastered),vocabAll=all.filter(q=>active(q)&&canonicalCategory_(q.topic)==='VOC'&&String(q.word||'').trim());if(grouped.VOC)grouped.VOC.newWords=vocabAll.length;
  const savedIds=new Set(typeof getSavedHinduQuestionIds==='function'?getSavedHinduQuestionIds():[]),saved=all.filter(q=>savedIds.has(q.id)&&active(q));if(saved.length)grouped.HINDU_WORDS={id:'HINDU_WORDS',name:'Hindu Words',total:saved.length,weak:saved.filter(q=>newPracticeWeak_(status[q.id]||{})).length,newWords:saved.filter(q=>String(q.word||'').trim()).length,starred:saved.filter(q=>isStarredStatus_(status[q.id]||{})).length,latest:'9999-12-31'};
  const myIds=new Set(typeof getMySavedWordQuestionIds==='function'?getMySavedWordQuestionIds():[]),mine=all.filter(q=>myIds.has(q.id)&&active(q));if(mine.length)grouped.MY_SAVED_WORDS={id:'MY_SAVED_WORDS',name:'My Saved Words',total:mine.length,weak:mine.filter(q=>newPracticeWeak_(status[q.id]||{})).length,newWords:mine.filter(q=>String(q.word||'').trim()).length,starred:mine.filter(q=>isStarredStatus_(status[q.id]||{})).length,latest:'9999-12-30'};
  const categories=Object.values(grouped).sort((a,b)=>b.latest.localeCompare(a.latest)||a.name.localeCompare(b.name)),pool=newPracticeLivePool_('ALL');return{days,categories,total:pool.length,weak:pool.filter(q=>newPracticeWeak_(status[q.id]||{})).length,newWords:vocabAll.length,starred:pool.filter(q=>isStarredStatus_(status[q.id]||{})).length};
}
function getNewPracticeItemsLive(category){const status=statusMap_();return newPracticeLivePool_(category||'ALL').map(q=>({id:q.id,word:q.word||'',question:q.question||'',category:canonicalCategory_(q.topic),topic:q.topic||'',subtopic:q.subtopic||'',weak:newPracticeWeak_(status[q.id]||{}),starred:isStarredStatus_(status[q.id]||{}),attempts:Number((status[q.id]||{}).attempts||0),source:q.sourceFile||q.sourceId||'',added:(()=>{const d=recentContentDate_(q);return d?Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd'):''})()}));}
function getNewPracticeBatchLive(category,kind,count){const status=statusMap_(),mode=String(kind||'all').toLowerCase();let pool=mode==='newwords'?newPracticeScopedWordPool_(category||'ALL'):newPracticeLivePool_(category||'ALL');const requested=Math.max(1,Math.min(100,Number(count||10)));if(mode==='newwords')pool=newPracticeNewWordOrder_(pool,status).slice(0,requested);else if(mode==='starred')pool=newPracticeNewWordOrder_(pool.filter(q=>isStarredStatus_(status[q.id]||{})),status).slice(0,requested);else if(mode==='weak'){pool=pool.filter(q=>newPracticeWeak_(status[q.id]||{}));shuffle_(pool);if(Number(count||0)>0)pool=pool.slice(0,requested)}else if(mode==='random'){const now=Date.now(),b=[[],[],[],[],[]];pool.forEach(q=>{const st=status[q.id]||{},added=recentContentDate_(q),days=added?(now-added.getTime())/86400000:999;if(newPracticeWeak_(st))b[0].push(q);else if(days<=7)b[1].push(q);else if(st.marked||String(st.status||'').toLowerCase()==='marked')b[2].push(q);else if(Number(st.attempts||0)>0)b[3].push(q);else b[4].push(q)});b.forEach(shuffle_);pool=b.flat().slice(0,requested)}else if(Number(count||0)>0)pool=pool.slice(0,Math.min(120,Number(count)));return pool.map(serveQuestion_);}
