function newPracticeLivePool_(wanted){
  const all=allQuestionsRaw_(),status=statusMap_(),key=String(wanted||'ALL').trim()||'ALL',days=Number(config_().NEW_CONTENT_DAYS||7),now=new Date(),cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-Math.max(0,days-1));cutoff.setHours(0,0,0,0);
  const hinduIds=new Set(typeof getSavedHinduQuestionIds==='function'?getSavedHinduQuestionIds():[]),myIds=new Set(typeof getMySavedWordQuestionIds==='function'?getMySavedWordQuestionIds():[]),out=[],seen=new Set();
  all.forEach(q=>{if(!isActive_(q)||(status[q.id]&&status[q.id].mastered))return;const rawCat=canonicalCategory_(q.topic),cat=rawCat==='MISC'?'NOT_SPECIFIED':rawCat,added=recentContentDate_(q),recent=!!added&&added>=cutoff,inHindu=hinduIds.has(q.id),inMine=myIds.has(q.id);let include=false;if(key==='ALL')include=recent||inHindu||inMine;else if(key==='HINDU_WORDS')include=inHindu;else if(key==='MY_SAVED_WORDS')include=inMine;else include=recent&&cat===key;if(include&&!seen.has(q.id)){seen.add(q.id);out.push(q)}});return out;
}
function getNewPracticeHubLive(){
  const all=allQuestionsRaw_(),status=statusMap_(),days=Number(config_().NEW_CONTENT_DAYS||7),now=new Date(),cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-Math.max(0,days-1));cutoff.setHours(0,0,0,0),grouped={};
  all.forEach(q=>{if(!isActive_(q)||(status[q.id]&&status[q.id].mastered))return;const added=recentContentDate_(q);if(!added||added<cutoff)return;const rawCat=canonicalCategory_(q.topic),id=rawCat==='MISC'?'NOT_SPECIFIED':rawCat,name=newPracticeCategoryName_(id,q.topic);if(!grouped[id])grouped[id]={id,name,total:0,weak:0,latest:''};const g=grouped[id],st=status[q.id]||{},dk=Utilities.formatDate(added,Session.getScriptTimeZone(),'yyyy-MM-dd');g.total++;if(newPracticeWeak_(st))g.weak++;if(!g.latest||dk>g.latest)g.latest=dk;});
  const savedIds=new Set(typeof getSavedHinduQuestionIds==='function'?getSavedHinduQuestionIds():[]),saved=all.filter(q=>savedIds.has(q.id)&&isActive_(q)&&!(status[q.id]&&status[q.id].mastered));if(saved.length)grouped.HINDU_WORDS={id:'HINDU_WORDS',name:'Hindu Words',total:saved.length,weak:saved.filter(q=>newPracticeWeak_(status[q.id]||{})).length,latest:'9999-12-31'};
  const myIds=new Set(typeof getMySavedWordQuestionIds==='function'?getMySavedWordQuestionIds():[]),mine=all.filter(q=>myIds.has(q.id)&&isActive_(q)&&!(status[q.id]&&status[q.id].mastered));if(mine.length)grouped.MY_SAVED_WORDS={id:'MY_SAVED_WORDS',name:'My Saved Words',total:mine.length,weak:mine.filter(q=>newPracticeWeak_(status[q.id]||{})).length,latest:'9999-12-30'};
  const categories=Object.values(grouped).sort((a,b)=>b.latest.localeCompare(a.latest)||a.name.localeCompare(b.name)),pool=newPracticeLivePool_('ALL');return{days,categories,total:pool.length,weak:pool.filter(q=>newPracticeWeak_(status[q.id]||{})).length};
}
function getNewPracticeItemsLive(category){const status=statusMap_();return newPracticeLivePool_(category||'ALL').map(q=>({id:q.id,word:q.word||'',question:q.question||'',category:canonicalCategory_(q.topic),topic:q.topic||'',subtopic:q.subtopic||'',weak:newPracticeWeak_(status[q.id]||{}),attempts:Number((status[q.id]||{}).attempts||0),source:q.sourceFile||q.sourceId||'',added:(()=>{const d=recentContentDate_(q);return d?Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd'):''})()}));}
function getNewPracticeBatchLive(category,kind,count){const status=statusMap_(),mode=String(kind||'all').toLowerCase();let pool=newPracticeLivePool_(category||'ALL');if(mode==='weak')pool=pool.filter(q=>newPracticeWeak_(status[q.id]||{}));const requested=Math.max(1,Math.min(100,Number(count||10)));if(mode==='random'){const now=Date.now(),b=[[],[],[],[],[]];pool.forEach(q=>{const st=status[q.id]||{},added=recentContentDate_(q),days=added?(now-added.getTime())/86400000:999;if(newPracticeWeak_(st))b[0].push(q);else if(days<=7)b[1].push(q);else if(st.marked||String(st.status||'').toLowerCase()==='marked')b[2].push(q);else if(Number(st.attempts||0)>0)b[3].push(q);else b[4].push(q)});b.forEach(shuffle_);pool=b.flat().slice(0,requested)}else if(mode==='weak'){shuffle_(pool);if(Number(count||0)>0)pool=pool.slice(0,requested)}else if(Number(count||0)>0)pool=pool.slice(0,Math.min(120,Number(count)));return pool.map(serveQuestion_);}
