import { createClient } from "npm:@supabase/supabase-js@2";

// This endpoint is scheduler-only. It deliberately accepts the private runtime token,
// not a browser JWT, and never exposes a service-role credential to the client.
const cors={"Access-Control-Allow-Origin":"null","Access-Control-Allow-Headers":"content-type, x-english-context-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const MODEL="gpt-5.6-luna", OPENAI_URL="https://api.openai.com/v1/responses";
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const err=(e:unknown)=>e instanceof Error?e.message:String(e||"Unknown revision worker error");
const text=(p:any)=>typeof p?.output_text==="string"?p.output_text:(p?.output||[]).flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==="output_text")?.text||"";
const item={question:{type:"string",minLength:8},optionA:{type:"string",minLength:1},optionB:{type:"string",minLength:1},optionC:{type:"string",minLength:1},optionD:{type:"string",minLength:1},correctKey:{type:"string",enum:["A","B","C","D"]},explanation:{type:"string",minLength:20}};
const draftSchema={type:"object",additionalProperties:false,required:Object.keys(item),properties:item};
const criticSchema={type:"object",additionalProperties:false,required:["item","exactlyOneCorrect","closeDistractors","notObviouslyEliminable","explanationMatches","noStaleExplanation","noAmbiguity","faithfulConcept","fairDifficulty","sscDifficultyFit","obviousElimination","difficultyArtificial","distractorCloseness","realisticTrapCount","qualityScore","rationale"],properties:{item:{type:"object",additionalProperties:false,required:Object.keys(item),properties:item},exactlyOneCorrect:{type:"boolean"},closeDistractors:{type:"boolean"},notObviouslyEliminable:{type:"boolean"},explanationMatches:{type:"boolean"},noStaleExplanation:{type:"boolean"},noAmbiguity:{type:"boolean"},faithfulConcept:{type:"boolean"},fairDifficulty:{type:"boolean"},sscDifficultyFit:{type:"boolean"},obviousElimination:{type:"boolean"},difficultyArtificial:{type:"boolean"},distractorCloseness:{type:"number"},realisticTrapCount:{type:"integer"},qualityScore:{type:"number"},rationale:{type:"string"}}};
const reviewSchema={type:"object",additionalProperties:false,required:["verdict","exactlyOneCorrect","recommendedCorrectKey","ambiguous","explanationConsistent","confidence","rationale"],properties:{verdict:{type:"string",enum:["valid","issue_suspected"]},exactlyOneCorrect:{type:"boolean"},recommendedCorrectKey:{type:"string",enum:["A","B","C","D",""]},ambiguous:{type:"boolean"},explanationConsistent:{type:"boolean"},confidence:{type:"number"},rationale:{type:"string"}}};
const revisionGeneratePrompt=`Repair one SSC CGL English MCQ only within intentRules. Preserve requiredCorrectKey. For repair-only requests preserve stem/correct option; for explanation-only preserve all options. Return only the schema.`;
const revisionCriticPrompt=`Act as independent SSC CGL final gate. Return a safe revised item only if it has exactly one answer, close realistic distractors, matching non-stale explanation, no ambiguity, concept fidelity and fair difficulty. qualityScore >= .85 only for a safe proposal.`;
const qualityReviewPrompt=`Independently audit the canonical question. Do not rewrite it. Determine whether it is valid or issue_suspected and return only the schema.`;
async function ai(name:string,schema:any,instructions:string,input:any,effort:"low"|"medium"){
 const key=Deno.env.get("OPENAI_API_KEY"); if(!key)throw new Error("AUTH_CONFIG: OPENAI_API_KEY is not configured");
 const c=new AbortController(),timer=setTimeout(()=>c.abort(),24000); try{const r=await fetch(OPENAI_URL,{method:"POST",signal:c.signal,headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,reasoning:{effort},max_output_tokens:2600,instructions,input:JSON.stringify(input),text:{format:{type:"json_schema",name,strict:true,schema}}})});const p=await r.json();if(!r.ok)throw new Error(r.status===429?"RATE_LIMIT":r.status>=500?"PROVIDER_5XX":`NETWORK_TRANSIENT: ${p?.error?.message||r.status}`);const out=text(p);if(!out)throw new Error("MALFORMED_OUTPUT: no structured output");return {data:JSON.parse(out),model:String(p.model||MODEL),usage:p.usage||{}}}catch(e:any){if(e?.name==="AbortError")throw new Error("AI_TIMEOUT: background AI request timed out safely");throw e}finally{clearTimeout(timer)}}
async function noThrow(db:any,fn:string,args:Record<string,unknown>){try{await db.rpc(fn,args)}catch{}}
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors}); if(req.method!=="POST")return reply({error:"Method not allowed"},405);
 const token=String(req.headers.get("x-english-context-token")||"").trim(),url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
 if(!token)return reply({error:"Unauthorized"},401); if(!url||!key)return reply({error:"Unavailable"},503);
 const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); let body:any={};try{body=await req.json()}catch{}
 const limit=Math.max(1,Math.min(1,Number(body.revisionLimit)||1)); const claimed=await db.rpc("english_question_revision_claim_dedicated",{p_token:token,p_limit:limit}); if(claimed.error)return reply({error:claimed.error.message},500);
 let processed=0,failed=0; for(const job of claimed.data?.items||[]){try{const d=await ai("english_question_revision_draft",draftSchema,revisionGeneratePrompt,job,"low");const f=await ai("english_question_revision_critic",criticSchema,revisionCriticPrompt,{...job,draft:d.data},"medium");const source=Array.isArray(job.bankReferences)&&job.bankReferences.length?"bank_informed_ai":"ai_last_resort";const done=await db.rpc("english_apply_question_revision_result",{p_token:token,p_proposal_id:job.proposalId,p_item:f.data.item,p_critic:f.data,p_source:source,p_model:f.model,p_usage:{generator:d.usage,critic:f.usage}});if(done.error)throw new Error(done.error.message);processed++}catch(e){failed++;await noThrow(db,"english_fail_question_revision",{p_token:token,p_proposal_id:job.proposalId,p_error:err(e)})}}
 const reviews=await db.rpc("english_question_quality_review_claim",{p_token:token,p_limit:1});let reviewed=0,reviewFailed=0;for(const job of reviews.data?.items||[]){try{const f=await ai("english_question_quality_review",reviewSchema,qualityReviewPrompt,job,"medium");const done=await db.rpc("english_apply_question_quality_review_result",{p_token:token,p_review_id:job.reviewId,p_critic:f.data,p_model:f.model,p_usage:f.usage});if(done.error)throw new Error(done.error.message);reviewed++}catch(e){reviewFailed++;await noThrow(db,"english_fail_question_quality_review",{p_token:token,p_review_id:job.reviewId,p_error:err(e)})}}
 await noThrow(db,"english_log_worker_metrics",{p_token:token,p_metrics:{lane:"revision_dedicated",revisions:{claimed:(claimed.data?.items||[]).length,processed,failed},qualityReviews:{claimed:(reviews.data?.items||[]).length,processed:reviewed,failed:reviewFailed}},p_elapsed_ms:0});
 return reply({ok:true,lane:"revision_dedicated",revisions:{processed,failed},qualityReviews:{processed:reviewed,failed:reviewFailed}});
});
