"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import QuizRunner from "@/components/quiz-runner";
import { EnglishLoading } from "@/components/english-frame";
import { rpc } from "@/lib/supabase";
import { useAuthGuard } from "@/lib/use-auth";

type OriginRow={origin:string;total:number;mastered:number;remaining:number};
type Overview={ok:boolean;fastTrack:{total:number;readyToVerify:number;waiting:number;mastered:number;remaining:number;origins:OriginRow[]}};
type Item={id:string;word?:string;question?:string;category?:string;topic?:string;correctKey?:string;explanation?:string;example?:string;fastTrackStatus?:string;fastTrackOrigins?:string[];fastTrackReason?:string;fastTrackEnteredAt?:string;fastTrackNextCheck?:string;fastTrackMasteredAt?:string;routeHistory?:Array<{at:string;type:string;from?:string;to?:string;origin?:string;reason?:string}>};
type Browse={origin:string|null;status:"all"|"remaining"|"mastered";rows:Item[];loading:boolean};
const sizes=[10,20,30,50,100];

export default function FastTrackPage(){
 const ready=useAuthGuard();const[overview,setOverview]=useState<Overview|null>(null);const[size,setSize]=useState(30);const[running,setRunning]=useState(false);const[details,setDetails]=useState(false);const[browse,setBrowse]=useState<Browse|null>(null);const[error,setError]=useState("");
 const refresh=useCallback(()=>rpc<Overview>("english_get_learning_route_overview").then(setOverview),[]);
 useEffect(()=>{if(ready)refresh().catch((e:any)=>setError(e.message));},[ready,refresh]);
 const load=useCallback(()=>rpc<any[]>("english_get_fast_track_batch",{p_count:size,p_origin:null}),[size]);
 async function openBrowse(origin:string|null,status:Browse["status"]="all"){setBrowse({origin,status,rows:[],loading:true});try{const rows=await rpc<Item[]>("english_get_fast_track_items",{p_origin:origin,p_status:status,p_limit:200,p_offset:0});setBrowse({origin,status,rows,loading:false});}catch(e:any){setError(e.message||String(e));setBrowse(null);}}
 async function changeStatus(status:Browse["status"]){if(!browse)return;await openBrowse(browse.origin,status);}
 if(!ready)return <EnglishLoading text="Checking session…"/>;
 if(running)return <QuizRunner title="Fast Track Mastery" backHref="/english/fast-track" load={load} module="fasttrack" fastTrackMode onExit={()=>{setRunning(false);void refresh()}} onFinish={refresh}/>;
 if(browse)return <section className="route-page"><div className="route-head"><button className="btn ghost" onClick={()=>setBrowse(null)}>← Fast Track</button><div><span className="eyebrow">Fast Track inventory</span><h1>{browse.origin||"All Fast Track"}</h1><p>{browse.loading?"Loading…":`${browse.rows.length} loaded`}</p></div></div><div className="route-tabs">{(["all","remaining","mastered"] as const).map(x=><button key={x} className={`btn ghost ${browse.status===x?"active":""}`} onClick={()=>void changeStatus(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>{!browse.loading&&browse.rows.length===0?<div className="empty-state"><h2>No items here</h2><p className="muted">This view is currently clear.</p></div>:<div className="route-inventory">{browse.rows.map((x,i)=><article className="route-item" key={x.id||i}><div className="route-item-top"><div><span className="eyebrow">{x.category||x.topic||"English"}</span><h3>{x.word||x.question||x.id}</h3></div><span className="pill">{x.fastTrackStatus||"Fast Track"}</span></div>{x.word&&x.question?<p>{x.question}</p>:null}{x.explanation&&<div className="route-explanation"><b>Explanation</b><span>{x.explanation}</span></div>}{x.example&&<div className="route-explanation"><b>Example</b><span>{x.example}</span></div>}<div className="route-meta"><span>Origin: {(x.fastTrackOrigins||[]).join(" · ")||"—"}</span><span>Reason: {x.fastTrackReason||"—"}</span>{x.fastTrackEnteredAt&&<span>Moved: {new Date(x.fastTrackEnteredAt).toLocaleDateString("en-IN")}</span>}{x.fastTrackMasteredAt&&<span>Mastered: {new Date(x.fastTrackMasteredAt).toLocaleDateString("en-IN")}</span>}{x.fastTrackNextCheck&&<span>Next check: {new Date(x.fastTrackNextCheck).toLocaleDateString("en-IN")}</span>}</div>{x.routeHistory?.length?<details className="route-history"><summary>Route history</summary>{x.routeHistory.map((h,j)=><div key={j}><b>{h.type}</b><span>{h.reason||`${h.from||"—"} → ${h.to||"—"}`}</span><small>{new Date(h.at).toLocaleString("en-IN")}</small></div>)}</details>:null}</article>)}</div>}</section>;
 const ft=overview?.fastTrack;
 return <section className="route-page"><div className="route-head"><Link className="btn ghost" href="/english/revision">← Revision</Link><div><span className="eyebrow">Cheap verification · Central Intelligence</span><h1>Fast Track Mastery</h1><p>I probably know this — verify it cheaply.</p></div></div>{error&&<div className="error-box">{error}</div>}<section className="route-summary"><Metric label="Ready" value={ft?.readyToVerify??"—"}/><Metric label="Mastered" value={ft?.mastered??"—"}/><Metric label="Remaining" value={ft?.remaining??"—"}/></section><section className="route-start"><h2>Start Fast Track</h2><p>Intentional verification only. This is not a compulsory daily target.</p><div className="route-sizes">{sizes.map(n=><button key={n} className={`btn ghost ${size===n?"active":""}`} onClick={()=>setSize(n)}>{n}</button>)}</div><button className="btn primary full-width" disabled={!ft?.readyToVerify} onClick={()=>setRunning(true)}>Start {size}</button><button className="btn ghost full-width" onClick={()=>setDetails(x=>!x)}>{details?"Hide details":"View"}</button></section>{details&&<section className="route-details"><div className="section-title-line"><h2>Fast Track Details</h2><button className="btn ghost mini" onClick={()=>void openBrowse(null)}>All questions</button></div><div className="route-table"><div className="route-table-head"><span>Origin</span><span>Total</span><span>Mastered</span><span>Remaining</span></div>{ft?.origins?.map(row=><button className="route-table-row" key={row.origin} onClick={()=>void openBrowse(row.origin)}><b>{row.origin}</b><span>{row.total}</span><span>{row.mastered}</span><span>{row.remaining} ›</span></button>)}</div></section>}</section>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div><span>{label}</span><b>{value}</b></div>}
